### ISSUE TITLE
Bug Found in Simple contacts app (share button are not working)

### ISSUE THREAD

**Issue by rizwankhan003** [SimpleMobileTools/Simple-Contacts#100]
#### Expected behavior
I expected that when I click on share button then they will allow me to share my contact to my friends through whatsup and facebook. When clicking on this button it should work properly.
#### Actual behavior
When i open simple contacts and select a contact that i wanted to share with my friends but when i click on share button are not working others buttons are working properly only share button are not working properly.

#### How to reproduce
+ Download simple contacts through F-Droid

+ installed the app and run it

+ Click  on any contact that you wanted to share

+ Now click on share button 

+ Note the bug

---

* Device:  HUAWEI Mate 10 lite
* Operating system: Android version 7.0

#### Recording Of The Bug
[](<iframe width="640" height="360" src="https://www.youtube.com/embed/QvnW8ZH7Y8A?ecver=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>)
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@rizwankhan/bug-found-in-simple-contacts-app-share-button-are-not-working">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tibbi** [comment]
What app version do you have? Is it broken for every contact, or only some specific ones? Do they maybe have something in common, like a special characters or so?
