### ISSUE TITLE
Contact list empty

### ISSUE THREAD

**Issue by toby63** [SimpleMobileTools/Simple-Contacts#1000]
I don't exactly know what has caused this, but my contact list is now empty ("No contacts found"), even though it should have dozens of contacts.

What makes this even stranger is that the call history still shows the names of my contacts.

Any idea how I can debug this?

I use Simple Contacts 6.22.4 Pro from F-Droid.

**Comment by tibbi** [comment]
was it working well before the update? Did you have the contacts stored at "Phone storage (not visible by other apps)", or some other place like SIM, Phone or so?

**Comment by toby63** [comment]
> was it working well before the update?

Yes and I guess it used to work even with the update as F-Droid says the update was already available in June, but I can't say for sure, when it stopped working.
I am sure it worked on and before 14th of July (I did not receive or started calls after that, because I also use different communication methods and devices).

I noticed that your calendar app was updated (Simple Calendar Pro) on 18th of July, but could another App interfere with this?
Or could this be a different problem, such as a background system service?

> Did you have the contacts stored at "Phone storage (not visible by other apps)", or some other place like SIM, Phone or so?

I am not sure, but I don't remember changing anything, so I assume the standard option was used (if that exists).

**Comment by tibbi** [comment]
calendar and contacts arent unrelated. Havent you filtered out some contact sources at the top Menu -> Filter?

**Comment by toby63** [comment]
> Havent you filtered out some contact sources at the top Menu -> Filter?

Two sources are enabled:
- Phone (0)
- Phone Storage (not visible by other apps) (0)

**Comment by tibbi** [comment]
well, you dont have any contacts.. Do any other apps show them?

**Comment by toby63** [comment]
No. Thats the point, they don't exist anymore and I certainly did not delete them.

**Comment by tibbi** [comment]
well, that isnt an issue in the app then, hard to say what happened there though

**Comment by toby63** [comment]
> well, that isnt an issue in the app then, hard to say what happened there though

very unfortunate, but thanks for your time.
