### ISSUE TITLE
Better wording on "Add to contact" button

### ISSUE THREAD

**Issue by Cwpute** [SimpleMobileTools/Simple-Contacts#1003]
As of now the button to add a new contact to our contacts list is called "Add to contact". To me, this wording can be a little confusing, as that singular "contact" may suggest there was a single contact selected before one way or another, and that button allows to add *additional* information to that contact.
While that is a possible option, it's far from the most common use cases, when users want to create a *new* contact rather than add information to an already existing one.

I'd suggest we simply change the wording to "Add to contacts", changing the noun to plural, as it makes it more clear this action is not targetting a particular, already exisitng contact, but rather the whole contacts list as a whole.

**Comment by tibbi** [comment]
the current one is good, thanks though
