### ISSUE TITLE
[feature request] Option to hide groups from the main view

### ISSUE THREAD

**Issue by xxxxme** [SimpleMobileTools/Simple-Contacts#1005]
Add an option to hide certain groups from the main "Contacts" view. For example, I have quite a few work-related numbers, all saved in a group "work". I would prefer not to see these when scrolling through the main contacts list and I always access them through the Groups tab. I would like to be able to long press on a group and choose to hide/unhide the contacts in it from the main list.

**Comment by tibbi** [comment]
that isnt on the roadmap
