### ISSUE TITLE
Initiating a phone call from the contacts app isn't possible when using multiple SIM cards

### ISSUE THREAD

**Issue by TripleWhy** [SimpleMobileTools/Simple-Contacts#1007]
I use two SIM cards. I used to be able to make phone calls from the contacts app. Now, when I try to call someone, it shows the popup to select which SIM card I want to use, but both options are grayed out, and I can only go back. To to make a call, I have to go to my dailer and find the contact from there. Which kinda makes the contacts app useless. (The dailer brings up the same popup, but the options are enabled.)

Repro:
1. Insert 2 SIM cards.
2. Open contacts app and select a contact.
3. Click call.
4. The popup opens.

Expected: I can tap a SIM card and make a call.
Actual: I can't select a SIM card.

Version: 6.22.4 from F-Droid
Android version: 13
Android kernel version: 5.4.210
Android build number: 61.2.F.0.223

**Comment by tibbi** [comment]
arent you using Google Phone as the calling app? It seems to be an issue on their side

**Comment by TripleWhy** [comment]
I am using [this one](https://play.google.com/store/apps/details?id=com.google.android.dialer) from google.
