### ISSUE TITLE
Add gps Icon for access GPS defaut app / Ajouter une icon pour acceder a l'application GPS par defaut

### ISSUE THREAD

**Issue by Plumf** [SimpleMobileTools/Simple-Contacts#101]
**English**
Proposition : add GPS's icon (next to SMS, Phone and mail icons) when adress is present in contact's card and open the GPS. If there are lot of adresse open a windows with all proposition.

**French**
Proposition : ajouter une icone de GPS (a côté des icones téléphones | SMS | Mail) lorsqu'une adresse est présente dans la fiche du contact afin d'ouvrir le GPS. Dans le cas ou il y a en a plusieurs faire une proposition entre les adresses

**Comment by tibbi** [comment]
in the next version address at the View screen will be clickable, that will open the map then

**Comment by Plumf** [comment]
And it's same for agenda, or I do post one issue ? thank you
