### ISSUE TITLE
[Feature Request] Allow changing contact display name

### ISSUE THREAD

**Issue by K4LCIFER** [SimpleMobileTools/Simple-Contacts#1011]
Currently, Simple-Contacts seems to ignore the `FN` VCard field, and only displays the `N` fields. What this then means is that your contacts will always show the extremely verbose form of their names, i.e. Prefix + Firstname + Middle Name + Last Name. You should be able to set an alternative contact name by specifying something in the `FN` field that will take priority over the `N` fields.

**Comment by K4LCIFER** [comment]
> that isnt planned

How come? I understand completely if you're simply too busy to implement it, but why close it so that no one else can? This makes me think that you don't want the feature at all, and, if so, I'm very curious as to why. I feel that it's pretty basic functionality.

**Comment by tibbi** [comment]
this is a simple app and what you are asking for is way too advanced

**Comment by K4LCIFER** [comment]
> what you are asking for is way too advanced

A custom contact name is too advanced of a feature...? It's part of [the vCard standard](https://datatracker.ietf.org/doc/html/rfc6350). And it also must be mentioned that according to the spec, supporting `FN` is a requirement to meet the base requirements of the spec:
> This property is based on the semantics of the X.520 Common Name attribute [[CCITT.X520.1988](https://datatracker.ietf.org/doc/html/rfc6350#ref-CCITT.X520.1988)].  The property MUST be present in the vCard object.
