### ISSUE TITLE
Call button in the contact list

### ISSUE THREAD

**Issue by bb1a2** [SimpleMobileTools/Simple-Contacts#1014]
Like this
![](https://static.techspot.com/articles-info/1408/images/2017-05-26-image-2.png)

Currently, you always have to open the contact details to call, which is cumbersome if you make a lot of calls.

Thanks

**Comment by bb1a2** [comment]
Alternatively, you can make a call by tapping the contact photo/letter.

**Comment by tibbi** [comment]
you can already change what happens on contact click in the app settings

**Comment by bb1a2** [comment]
> you can already change what happens on contact click in the app settings

But if you do, opening contact details requires multiple taps :) With this feature, you can have the best of both worlds.

Thanks
