### ISSUE TITLE
Hide selected contacts

### ISSUE THREAD

**Issue by bb1a2** [SimpleMobileTools/Simple-Contacts#1016]
When I use the app(*), I always have to sift through countless random contacts. For these contacts (80%), I only store their number for when they call, but I almost never initiate the call. The remaining contacts (20%) is the people I actually call.

So, I suggest an option to hide a contact from the list so that their ID would show when they call but they don't clutter the list.

I don't see Favorites as an appropriate solution for this, because you lose your actual favorites (1%) among the 20%, and because of new numbers (it is much easier to hide a newly-created contact in the 20% than to go through the full 100% and open each one to check if you need to favorite them).

---

(*) like:
- scrolling the contact list
- using the dialer (T9 matching)
- searching contacts

**Comment by tibbi** [comment]
no idea what this is about sadly..

**Comment by bb1a2** [comment]
> no idea what this is about sadly..

If you are a designer or a freelancer, you want to keep the contact details of previous clients (in case they call you), but you don't want a giant contacts list to sift through every time you try to call a friend or a current client.
