### ISSUE TITLE
Show call recordings for people in the contacts

### ISSUE THREAD

**Issue by mpeter50** [SimpleMobileTools/Simple-Contacts#1020]
Call recording is a popular feature, whether it is done by the system built-in dialer or a 3rd party solution.
But other than Xiaomi's contacts app, I did not see any that could show all previous recordings for the corresponding contact entry. However app that is not just closed source, but as I know it is not even possible to install that on non-Xiaomi phones.

I think it would be a very useful feature if Simple Contacts could show a list of all previous call recordings for the opened contact, even if Simple Dialer does not support call recording, because there are already useful tools for that.

Some of the more popular solutions that I know of that allow contact recording:
- AOSP dialer
- MIUI Dialer
- [Basic Call Recorder](https://github.com/chenxiaolong/BCR)
- [Axet'sa call recorder](https://gitlab.com/axet/android-call-recorder)

**Comment by tibbi** [comment]
that cannot really be done
