### ISSUE TITLE
Emailaddresses missing on contact card

### ISSUE THREAD

**Issue by FRvanderVeen** [SimpleMobileTools/Simple-Contacts#1021]
I configured SimpleContacts to show the email fields. When I open my contacts I do not see an emailaddress, while I'm sure this contact has an emailaddress.
This contact exists in multiple addressbooks (whatsapp, signal and one synced with davx5).
When I click on the specific addressbook (which opens the edit screen) the emailaddresses show up.
When I disable "merge duplicate contacts" and open the contact the addresses also show up.

**Comment by tibbi** [comment]
the contact is apparently stored multiple times and not all instances have an email

**Comment by FRvanderVeen** [comment]
That's true. But there is also only 1 instance of the contact that has a birthday and address filled. And these are shown. While email is not. That seems illogical to me
