### ISSUE TITLE
The app always asks which phone app to use

### ISSUE THREAD

**Issue by omar-mohy** [SimpleMobileTools/Simple-Contacts#1022]
This issue (https://github.com/SimpleMobileTools/Simple-Dialer/issues/138) was present in the simple dialer app and was fixed in simple dialer 5.18.0, but it is still present in the contacts app.

**Comment by omar-mohy** [comment]
![Screenshot_20230830_203750](https://github.com/SimpleMobileTools/Simple-Contacts/assets/28865681/274a925b-3d07-46ea-a782-832c69d4b3ad)
![Screenshot_20230830-203438](https://github.com/SimpleMobileTools/Simple-Contacts/assets/28865681/2bd7483f-3fb2-4025-afb3-0a9646a39bf7)


I meant this button in the contact details screen.

**Comment by omar-mohy** [comment]
I tested it again (on Android 9) and this behavior is the same in both the dialer and contacts app.

Tapping the call button in the contact details screen of either app (dialer or contacts) will result in this behavior, but tapping a contact from favorites or call history in the dialer app behaves as expected.

**Comment by tibbi** [comment]
what app versions are you using at all?

**Comment by omar-mohy** [comment]
Any updates?

**Comment by tibbi** [comment]
should work just fine already
