### ISSUE TITLE
Please please please put this information in the target selector

### ISSUE THREAD

**Issue by dgtlmoon** [SimpleMobileTools/Simple-Contacts#1030]
So regular use case, I have a new phone, and i'm importing VCF, for hours I cant figure out why I have *only* this "contacts" app as a target and that the phone does not offer me to use itself as a target (so that the contacts will also display in signal/whatsapp)

I saw this https://github.com/SimpleMobileTools/Simple-Contacts/issues/881#issuecomment-1249109717

**"just create a single contact on "Phone", you dont have to use that app afterwise."**

Please put this in the dialog chooser, I'm very sure this is going to save a LOT of github issues from being created, this is totally non obvious behaviour

( Why I only have  "Phone storage (not visible by other apps)"  as an option ) 

Please, in the list, or make some popup thing that says "Please be sure to have atleast 1 entry in contacts book on your phone if it doesnt display as a target"

**Comment by dgtlmoon** [comment]
If you solve this UI problem, I'll send $30 USD to your project :)

**Comment by tibbi** [comment]
public contact sources are already selected by default, its works just fine. Thanks

**Comment by dgtlmoon** [comment]
> public contact sources are already selected by default, its works just fine. Thanks

it doesnt work just fine already, or i wouldnt have taken the time to create this issue... as I wrote, it never offered me the public contact sources @tibbi please re-read and re-open this issue

**Comment by tibbi** [comment]
you mean that you cannot create contacts under Phone or some other casual place? Havent you disabled some system services or tweaked your device, like rooting?
