### ISSUE TITLE
[Feature request] Set default storage for new contacts in options

### ISSUE THREAD

**Issue by inson1** [SimpleMobileTools/Simple-Contacts#1041]
Right now default storage is set to last created contact storage.

**Comment by NikMAX2077** [comment]
> Right now default storage is set to last created contact storage.

Quite counterintuitive. I didn't have the option to save contacts to DEVICE until I created one contact through the system app

+1

**Comment by inson1** [comment]
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
