### ISSUE TITLE
Difference between "DEVICE" and "Phone Storage"

### ISSUE THREAD

**Issue by XSpielinbox** [SimpleMobileTools/Simple-Contacts#1048]
Hi,
thank you for creating this awesome app!

I have one major question though:
I get, that "Phone storage (not visible by other apps)" is not visible by other apps as the name implies, except other SimpleMobileTools apps, if one sets this in the contacts. I also assume that one does not need the Contacts permission for this to work.
All along I have always granted Contacts permission and saved contacts to "Phone Storage", where it was then visible to all apps on the system with Contacts permission.
Since about a week or month or so it now suddenly creates contacts in a new location called "DEVICE", however.
This location also seems to be shared across all apps with Contacts permission.

What is the difference between this "DEVICE" and "Phone Storage" location? When should I use which of these two? Why did "Device" just suddenly appear?

I am using Version 6.22.7 Pro from F-Droid on CalyxOS version 4.14.0 (Android 13). I have been using the latest available version of Simple Contacts on CalyxOS for the last half year or so.

**Comment by tibbi** [comment]
there is likely no difference. Those names havent been set by us, we just show whatever the system gives us.
