### ISSUE TITLE
Wrong import of a few contacts (name with the : character)

### ISSUE THREAD

**Issue by morfikov** [SimpleMobileTools/Simple-Contacts#105]
I noticed that some contacts aren't properly imported from the .vcf file. Basically when a contact has a name of "word1: word2 word3", the second phrase is dropped entirely, and after importing such contact, you simply get "word1 word3". It looks like the `:` character causes the problem here.

**Comment by tibbi** [comment]
importing/exporting has been rewritten from scratch recently, retest with 4.4.0 please.
