### ISSUE TITLE
Temporarily disable the spam filter

### ISSUE THREAD

**Issue by s9gf4ult** [SimpleMobileTools/Simple-Contacts#1056]
It is very often situation when I am waiting for a call, so I need to disable the spam filter (the "block all unknown phones" setting) and then not to forget to turn it back. It would be great to have a quick button "Waiting for a call" which disables the spam filter for a period of time. Like an hour or a day (better to have setting for that). It would be even better to have a quick action (long tap menu) for that.

**Comment by Aga-C** [comment]
Blocking contacts is not in this app. It should be reported in https://github.com/SimpleMobileTools/Simple-Dialer.
