### ISSUE TITLE
[Bug] App refuses to open, crashes immediately (v6.22.7)

### ISSUE THREAD

**Issue by tezrilet** [SimpleMobileTools/Simple-Contacts#1059]
**OS:** LineageOS 19.1 (Android 12)
**Source:** F-Droid

I was adding a contact to my list, but when I added a photo, instead of using the normal crop option I used the original size. The photo was 4624x3468 pixels. After exiting the app, it now always crashes when I try to open it. I tried updating after https://github.com/SimpleMobileTools/Simple-Contacts/issues/1025, but it did not work for me.

**Comment by Maxitendo1** [comment]
@tezrilet SimpleMobileTools apps were sold to ad and spyware company. Fork is here:

https://github.com/FossifyOrg

**Comment by tezrilet** [comment]
I'm aware, but thanks. I should've mentioned it here earlier and closed this one, but I made an issue there, still waiting on a resolution:
https://github.com/FossifyOrg/Contacts/issues/38
