### ISSUE TITLE
Proposal icon / Logo For The Application Simple-Contacts

### ISSUE THREAD

**Issue by tufotech** [SimpleMobileTools/Simple-Contacts#107]
Hallo @simplemobiletools

I'm a graphic designer, I want your permission to design  logo and icon for the Simple-Contacts app,  Hope you give me permission to create a logo for the app.

Best Regards

**Comment by tibbi** [comment]
Hey, Im not looking for a new logo now, thanks though.

**Comment by tufotech** [comment]
I just wanted to offer you a new logo for your application, sir

may i create a new logo for your app.

**Comment by tibbi** [comment]
you can, but you should know that I wont use it :)

**Comment by tufotech** [comment]
well sir, i will make it, and you do not need to use, i just want to make logo design for you, as a little extra my contribution in opensource world, :)
thank you

**Comment by tufotech** [comment]
hi sir .. this is the latest logo design i made for your application, if you do not like the design you can give input to me and this design do not need you use in your application if you object. thanks for permission to create your application logo,

![untitled-12](https://user-images.githubusercontent.com/16377865/37873274-659dd61e-3043-11e8-9e47-a5ec35c6023b.png)

**Comment by tibbi** [comment]
well it doesnt really resonate a contacts app whatsoever to me :)
