### ISSUE TITLE
If phone permission is denied, dial number 

### ISSUE THREAD

**Issue by Hocceruser** [SimpleMobileTools/Simple-Contacts#111]
### Steps to reproduce:
Deny phone permission and try to call somebody

### Actual behavior:
An error message is shown

### Expected behavior:
Simply use an intent with [ACTION_DIAL](https://developer.android.com/reference/android/content/Intent.html#ACTION_DIAL) instead of [ACTION_CALL](https://developer.android.com/reference/android/content/Intent.html#ACTION_CALL), as only ACTION_CALL requires this permission.

Code reference:
https://github.com/SimpleMobileTools/Simple-Contacts/blob/0ae8c8a98f72c07bf24edc54c9be74fc0f40c847/app/src/main/kotlin/com/simplemobiletools/contacts/extensions/Activity.kt#L24

**Comment by tibbi** [comment]
Nice one! I didnt really research that, good to know :)

**Comment by Hocceruser** [comment]
Thank you!!! That was quite fast (also #110)! Now this app does not need any permissions any more to work!
