### ISSUE TITLE
DAVDroid Contacts

### ISSUE THREAD

**Issue by wbrawner** [SimpleMobileTools/Simple-Contacts#112]
I'm unable to add contacts to my Nextcloud address book that's synced through DAVDroid. I am able to do so through the default (Samsung) contacts app though

**Comment by michaelof** [comment]
ADD works FINE for me on:

Simple-Contacts 3.5.1 from F-Droid
Android 6.0
Contacts from Nextcloud 13.0.1, synced via DavDroid (1.10.1.1-ose, F-Droid)

**Comment by andreapx** [comment]
I can see only 2 contacts from my NextCloud address book. On the default Android contacts app I can see them all.

**Comment by andreapx** [comment]
The strange thing is that I can see all my starred contacts!

P.s. Sorry, but I'm not able to edit my previous comment.

**Comment by michaelof** [comment]
Hmm. You said that the contacts are visible in your phone's native app, means that the sync itself between Neztcloud and your phone via DavDroid works. 

Anything "special" with the not visible contacts? Special Characters? Special charset? Your own Nextcloud instance?

**Comment by tibbi** [comment]
I dont know, Ill take a look at it soon.
