### ISSUE TITLE
Clicking the star icon on a contact detail does not add the contact to the favorites list

### ISSUE THREAD

**Issue by codaphrenic** [SimpleMobileTools/Simple-Contacts#114]
#### Expected behavior
I expect that when i click the star(favorite) icon on a selected contact, the contact is immediately added to my favorite list.

#### Actual behavior

Clicking the star icon performs no function in particular.

#### How to reproduce
* download the app from fdroid store
* launch app and allow permissions if prompted
* Scroll through contacts and select any of your choice, it should show **details** at the top bar
* Click on the star (favorite) icon and you'll discover there is no function performed.

***

* Device: TECNO-L8Plus 
* Operating system: Android 5.1

* Application: Simple Contacts
* version: 3.4.0

#### Recording Of The Bug

<sub>
<center>
The video shows that other icons when clicked, performed a function. But the star(favorite) icon doesn't do a thing.
</center>
</sub>

<center>
https://youtu.be/LhT6ZhJXj1o
</center>
 

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fego/clicking-the-star-icon-on-a-contact-detail-does-not-add-the-contact-to-the-favorites-list">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tibbi** [comment]
thats the view screen, go in Edit for modifications
