### ISSUE TITLE
Filter contacts by groups

### ISSUE THREAD

**Issue by patchuss** [SimpleMobileTools/Simple-Contacts#116]
Hey! Thank you for your great app! It would be great if it was possible to filter the contacts also by groups,  not only by address book, so that I can show or hide certain groups in the main window.

**Comment by tibbi** [comment]
You have groups on the 3rd tab already, I dont want to add filtering by that too.

**Comment by marc-straube** [comment]
I was going to propose the same. I have a big archive group I'd love to hide.
