### ISSUE TITLE
Logo proposal for Simple-Contacts

### ISSUE THREAD

**Issue by baranpirincal** [SimpleMobileTools/Simple-Contacts#122]
Hello! I wanted to design a logo for Simple-Contacts. I hope you like it!

If you liked, I will send you editable/original source and .png format files. If there's something you want to change I can do it. Have a nice day!

![logo2](https://user-images.githubusercontent.com/37786733/38466303-ebb56482-3b2f-11e8-9bb7-dec46a611f74.jpg)

![logo](https://user-images.githubusercontent.com/37786733/38466304-f263f5b4-3b2f-11e8-8fc3-41ceb4d97e72.jpg)

**Comment by tibbi** [comment]
Hey, thanks, but Im currently not looking for new logos.
