### ISSUE TITLE
UTF8 letters not ranked per alphabetical order

### ISSUE THREAD

**Issue by FrancoisMz** [SimpleMobileTools/Simple-Contacts#131]
Names containing UTF characters (e.g. à, ç, ê, ę, ł, ś) are not ranked correctly in the alphabetical order: I would expect them to be ranked among the a, c, e, e, l, s letters.
Instead, they are flushed to the bottom of the alphabet.
This applies for initials as well as letters inside a name.

Would it be possible to a correct sorting ?

v3.5.1

**Comment by El-Gavy** [comment]
I am in high need of this fix too ! :-)

**Comment by Reue** [comment]
FrancoisMz: you forgot characters like "â", "ã", "á", "é", "ú", "ó", "ç", etc... The sort order is a complete mess. A total no sense. I've never seen anything like this in all my life.

**Comment by El-Gavy** [comment]
@Reue sorry but your comment seems quite agressive. Please take in consideration the fact that @tibbi is alone to fix and improve all the simple mobile tools (if i'm not mistaken) before posting such a harsh comment.

**Comment by JakeOnestone** [comment]
This problem also affects German umlauts: äöüßÄÖÜ

**Comment by michaelof** [comment]
@tibbi 

Hi Tibor, not sure if you prefer re-opening or a new issue, but as the subject of this issue is very generic: 
Found that sort order of contact GROUPS is also affected, for German umlauts, guess same root cause.

Simple Contacts v4.4.0

**Comment by tibbi** [comment]
aha right, I can take a look at it. Thanks

**Comment by ouzowtf** [comment]
I think a simple " should be sorted above a name starting with "a" too.

**Comment by tibbi** [comment]
you mean an apostrophe? I dont really like that, we will see in the future.
