### ISSUE TITLE
"Generic search" of UTF letters not possible

### ISSUE THREAD

**Issue by FrancoisMz** [SimpleMobileTools/Simple-Contacts#132]
I don't know how to call this feature, so let me try to explain it...

When names include UTF characters (e.g. à, ç, ê, ę, ł, ś), it is easier to type these letters in plain ascii (without the diacritics) to make a quicker search.
However, the search tool will not include the above characters if a, c, e, e, l or s is typed.
It is necessary to type the exact characters to find them.

Would it be possible to include this ?

**Comment by Reue** [comment]
This is not a "feature request". This is a bug, and a bad one...
