### ISSUE TITLE
(Small) Feature request: Contact field "website"

### ISSUE THREAD

**Issue by michaelof** [SimpleMobileTools/Simple-Contacts#134]
Simple-Contacts 3.5.1 from F-Droid
Android 6.0
Contacts from Nextcloud 13.0.1, synced via DavDroid (1.10.1.1-ose, F-Droid)

It would be nice to have a contact's field for "website" available.

**Comment by tibbi** [comment]
this has just been added in 3.5.2. It is however disabled by default, so enable it in Settings -> Manage fields... Thanks
