### ISSUE TITLE
Unable to choose photo 

### ISSUE THREAD

**Issue by tykees** [SimpleMobileTools/Simple-Contacts#144]
I am unable to choose picture from my gallery, each time i try to use the feature, an error message pops up `Cannot load the image`

The behavior is on android 4.4.2 techno y2

App  Version 3.5.3

**Comment by tibbi** [comment]
Is the photo on an SD card? Can you try using a different gallery, to see if it works?

**Comment by tykees** [comment]
the photo is on my mobile not on SD card and i tried the two available galleries on my device but the same thing happened,

**Comment by tibbi** [comment]
when does the message appear? Right as you select "Choose photo" in the Contacts app?

**Comment by tykees** [comment]
Nop! When i clicked on `Choose Photo`, It gave me the option to select picture, which i did select, but after i selected the picture i want to use, option came up to Crop the image, the error pops up when i clicked  on `crop`

**Comment by tibbi** [comment]
what galleries have you tried? Can you try Simple Gallery? https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery I cannot affect others.

**Comment by tibbi** [comment]
okay Ill close this then, as Im not sure what could be wrong with a third party gallery or why it doesnt work. Theres many galleries out there, especially the preinstalled ones.
