### ISSUE TITLE
Groups not exported

### ISSUE THREAD

**Issue by contrapunctus-1** [SimpleMobileTools/Simple-Contacts#146]
v3.5.3 from F-Droid, Nokia 6.1, Android 8.1.

Exporting a contact who is part of a group does not export any group-related data. Importing that contact from the exported file does not add them to the groups they were part of.

(I can see how this can be troublesome in the case of exporting to share a contact with others...but it leaves a user with no way to backup group information, which takes a lot of effort to add for a big phonebook.)

This might be a shortcoming of the vCard format, seeing as the Google contacts app demonstrated the same behavior.

**Comment by Dirkster99** [comment]
I'd like to play with this on a Windows computer to see if I can get a good enough prototype for import/export contacts including groups. I am thinking Xml or SqLite or both 👍 

Is there a "how to" that shows the requirements to get Simple-Contacts installed and developed on a Windows computer?

**Comment by tibbi** [comment]
it is a standard android app, it doesnt require anything else than other projects

**Comment by Dirkster99** [comment]
OK, so I just install Android Studio and should be able to get this to work, right?

I am just asking because one of the batch files shows usage of gradle - but I see now it probably comes with Android Studio I guess... and there are no other project as pre-requisite either, right?

**Comment by tibbi** [comment]
yep, nothing extra. Just run some Hello World project first, to make sure you have the base setup.

**Comment by Dirkster99** [comment]
OK I got it to work in Android Studio and will try to go for SQLite next - I think I'll do a similar function as you already implemented for `exportContacts()` but name it `exportContacts_db()` instead and export into a *.db file. When I use the FilePickerDialog in exportContacts, how do I configure to pick a *.db file instead of a *.vcf file?

```
    private fun exportContacts() {
        FilePickerDialog(this, pickFile = false, showFAB = true) {
            ExportContactsDialog(this, it) { file, contactSources ->
                Thread {
                    ContactsHelper(this).getContacts { allContacts ->
                        val contacts = allContacts.filter { contactSources.contains(it.source) }
                        if (contacts.isEmpty()) {
                            toast(R.string.no_entries_for_exporting)
                        } else {
                            VcfExporter().exportContacts(this, file, contacts as ArrayList<Contact>, true) { result ->
                                toast(when (result) {
                                    VcfExporter.ExportResult.EXPORT_OK -> R.string.exporting_successful
                                    VcfExporter.ExportResult.EXPORT_PARTIAL -> R.string.exporting_some_entries_failed
                                    else -> R.string.exporting_failed
                                })
                            }
                        }
                    }
                }.start()
            }
        }
    }

```

**Comment by tibbi** [comment]
not sure what you mean. Why do you want to export the database in a .db file? Thats not what I want to have + it isnt related to this issue at all.

**Comment by Dirkster99** [comment]
A db file is usually the extension that is used to store in an SQLite format - we can always use a different extension of way of  marking the difference - my intention was to export/import groups and contacts into one file and import them at the destination. It seems to me like this deserves a file format of its own since the *.vcf file does not support this, right?

So, how would you support exporting/importing groups and contacts via one file if not using a different file extenson?

**Comment by tibbi** [comment]
well if groups arent supported, just create a new "GROUPS" tag. I surely wont export contacts as a raw database.

**Comment by Dirkster99** [comment]
Well I can understand what you mean but you should know that SQLite has a universal format that can even be read on a desktop computer when it is created on an Android Device... so, using this would open up a whole new range of possibilities but I don't realy mind - just want to get that export/import of groups to work

- could you be more specific about creating the "GROUPS" tag because thats where you lost me (I thought the vcf file format was fixed and cannot be customized - but I guess I was wrong, right?)

**Comment by tibbi** [comment]
well ye it is a standard format and other apps wont recognize the custom GROUPS tag, but it is still better than nothing. Just separate the groups by a comma.

**Comment by michaelof** [comment]
Hi Tibor and Dirkster99,

my five cents: German Wikipedia page for VCARD/VCF lists CATEGORIES as comma-separated list field, DAVdroid has a mandantory for Nextcloud flag "Groups are contact's categories" and, just verified, Nextcloud's Web-GUI's functionality "Download" creates a VCF file with all contact's groups exported as CATEGORIES.

So I would say existing tag CATEGORIES should be tag of choice for this issue :)

Remark, additional: My stock Contact's app shows assigned Nextcloud groups correctly, at least. But it does NOT export them into VCF, no CATEGORIES tag in VCF, verified. I haven't checked if importing contacts with groups works, as I never uses VCF import, if possible. First/middle/last name assignements are so ugly after VCF imports of stock contacts app, IMHO unusable.

**Comment by Dirkster99** [comment]
OK, I found a solution and put it into this branch
https://github.com/Dirkster99/Simple-Contacts
for review - I've tested the solution and it appears to work for a small number of test users and groups in my Emulators. Can you review this and let me know if you can see 'obvious' problems?

Thanx Dirk

```
BEGIN:VCARD
VERSION:3.0
PRODID:ez-vcard 0.10.4
N:;Test User
TEL;TYPE=cell:125478963
TEL;TYPE=cell:66666
CATEGORIES;GROUP=Testgroup,Testgroup1:
END:VCARD
BEGIN:VCARD
VERSION:3.0
PRODID:ez-vcard 0.10.4
N:User 2;Test
END:VCARD
BEGIN:VCARD
VERSION:3.0
PRODID:ez-vcard 0.10.4
N:User 1;Test
CATEGORIES;GROUP=Testgroup1:
END:VCARD
BEGIN:VCARD
VERSION:3.0
PRODID:ez-vcard 0.10.4
N:User 3;Test
CATEGORIES;GROUP=Testgroup1:
END:VCARD
BEGIN:VCARD
VERSION:3.0
PRODID:ez-vcard 0.10.4
N:User 4;Test
END:VCARD

```

![screenshot](https://user-images.githubusercontent.com/2129700/44992334-3b9f0580-af97-11e8-862f-a72a1f296d15.png)

**Comment by tibbi** [comment]
since you are using "CATEGORIES", you shouldnt use the "GROUP=". Just try exporting some contacts from Google Contacts to see some samples. The code style itself has many issues, it isnt written with the usual code style at all. Fix that first, then I can check the functionality. Thanks

**Comment by michaelof** [comment]
Just to remind: As said before, Google contacts seems NOT to take care of any groups, when importing or exporting contacts as VCARD.

Maybe useful sample instead, created from Nextcloud's web GUI:

`BEGIN:VCARD
VERSION:3.0
FN:Tibor Kaputa 
UID:56b0ada2-e79c-45d2-a813-83e3105fe24e
CATEGORIES:SimpleMobiletoolsHeroes
N:Kaputa;Tibor;;;
REV:20180903T202805Z
EMAIL;TYPE=HOME:recipient@example.com
URL:https://simplemobiletools.github.io/
END:VCARD`

**Comment by Dirkster99** [comment]
@tibbi
I have tried to follow the available style as much as I could, if you see problems in the coding style you should mention the specific issues so I can correct them, Thanx

The way I used CATEGORIES here allows us to use other CATEGORIES for other purposes later on. I think that's a very good approach as far as future extensions go. Can you please indicate in more detail what you want to change here?

Thanx Dirk

**Comment by Dirkster99** [comment]
How can I change the format to `CATEGORIES:Testgroup,Testgroup1` ? I thought this is copntrolled by the ezcard library - I have no idea how to make that change :-(

**Comment by tibbi** [comment]
how would they control it? You are adding it manually at `groupList.addParameter("GROUP", it.title);`

**Comment by Dirkster99** [comment]
OK I adjusted as requested and you have a new pull request from that.
Thanks Dirk

**Comment by tibbi** [comment]
are you using Android Studio with Kotlin related things setup properly? There should be no semicolons in Kotlin + Im getting many warnings about code refactoring, for example replacing `groupList.getValues().add(it.title);` with `groupList.values.add(it.title)`

**Comment by Dirkster99** [comment]
I am not completely sure what warnings you mean. I don't see a build log containing these warnings.

I just see a gray line under each ';' and that line is difficult to see in the black skin version - these lines are sometimes even useless because they hint spellcheck problems on variables and method names :-)

Anyways, I removed the ';' characters and changed to the property access syntax - hope this is fine now

**Comment by tibbi** [comment]
yep it looks great now, thanks
