### ISSUE TITLE
Toggling favorite contact does not work.

### ISSUE THREAD

**Issue by OffifialMITX** [SimpleMobileTools/Simple-Contacts#151]
I can't mark my contacts and I can't unmark it from one of the previous versions by pressing on the star.

Version 3.5.3 from F-Droid
Stock android 5.1.1
Screen resolution of 480x854px

**Comment by tibbi** [comment]
are you at the Edit screen? Thats the only place where you can toggle it by pressing the star. I will be displaying a toast messages in the next version if someone clicks it at the View screen.

**Comment by OffifialMITX** [comment]
Oh, right. Didn't remember that specifically since the top looks exactly the same in both view and edit screens.

I think it might help if in view mode, the star would fill the background of the letter or covered 1/(3²) of the picture at the bottom-right corner.

From what my personal Android UI intuition says, a star is either part of another object or toggleable. But that could be just me.

Maybe you could consider to just make the star active in view mode (maybe long-press), since that's an element where in my opinion there's no loss of important data from changing it accidentily, unlike other edit options.

On April 27, 2018 9:30:47 AM GMT+02:00, Tibor Kaputa <notifications@github.com> wrote:
>are you at the Edit screen? Thats the only place where you can toggle
>it by pressing the star. I will be displaying a toast messages in the
>next version if someone clicks it at the View screen.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SimpleMobileTools/Simple-Contacts/issues/151#issuecomment-384889568

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tibbi** [comment]
for now I just added a toast. Maybe in the future Favorite will be togglable there with autosave, we will see. So far nobody needed it.

**Comment by OffifialMITX** [comment]
Apparently.

On April 27, 2018 10:32:27 AM GMT+02:00, Tibor Kaputa <notifications@github.com> wrote:
>for now I just added a toast. Maybe in the future Favorite will be
>togglable there with autosave, we will see. So far nobody needed it.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SimpleMobileTools/Simple-Contacts/issues/151#issuecomment-384903644

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
