### ISSUE TITLE
Frequently Asked Question (FAQ) Proposal 

### ISSUE THREAD

**Issue by olayhemy** [SimpleMobileTools/Simple-Contacts#152]
Hello there, I'd like to contribute to your awesome project by writing a Frequent Asked Questions for users self-service. Would love to hear from you, thanks.

**Comment by tibbi** [comment]
Hey, do you have any specific question on your mind? Thanks

**Comment by olayhemy** [comment]
Not really, I'm talking of helping you with questions that are likely to be asked over a number of time by users, with their appropriate answers.

**Comment by tibbi** [comment]
well Ive already added a couple questions in some apps, I plan adding more if I figure some out. Then you can suggest some changes. Thanks
