### ISSUE TITLE
i will love to do copywriter for you 

### ISSUE THREAD

**Issue by Hamzeto938** [SimpleMobileTools/Simple-Contacts#157]
I love your application and would want to contribute to it, I'm not a developer but I am good at copywriting. I would love to make a copywrite for your Readme and make a pull request for you to merge. Your response would be highly appreciated. Also I would like to request if we could communicate via email, so I don't have to create issues. Thank you.

**Comment by tibbi** [comment]
well you can try changing whatever you feel like and Ill see if it is ok. Thanks
