### ISSUE TITLE
all contacts gone after update to 4.0.0

### ISSUE THREAD

**Issue by GuitarBilly** [SimpleMobileTools/Simple-Contacts#161]
nokia6   android 7.1.2   SC 4.0.0

hello, today i upgraded Simple Contacts to version 4.0.0 and upon opening the app all content is disappeared.

Tabs contacts, favorites and groups are all empty. Any way to debug and/or restore this?

The default android contact app still has a copy of my contacts.

**Comment by tibbi** [comment]
ye there was a glitch, please update to 4.0.1 whenever possible. Sorry for that

**Comment by GuitarBilly** [comment]
ok i have been able to update again. 

FYI - content is visible on all tabs. i just have duplicates now which seem caused by recent edits to add extras like address, birthday and/or group assignment. These were made before the update to 4.0.x.
i can fix my data manually since they are less than 20 contacts to touch.

**Comment by tibbi** [comment]
ye there were many changes related to contact fetching, some duplicate filtering has been added too. It might need some tweaks in the future, we will see how will it work.

**Comment by JimmyKater** [comment]
Nokia 5, android 8.1, SC 4.0.1 - still no contacts visible

**Comment by tibbi** [comment]
can you try restarting the app? I mean exiting with the Back button and starting again. So it used to work, and after updating you dont see them anymore?

**Comment by JimmyKater** [comment]
did that - no changes... still no contacts visible

**Comment by tibbi** [comment]
try disabling the Contacts permission in your device settings and rerunning the app

**Comment by JimmyKater** [comment]
app asked me to grant access to contacts... which i then did. no changes.

**Comment by tibbi** [comment]
O.o are they contacts stored on your phone only? If you press Filter from the menu, you see just the "Phone Storage (not visible..." option?

**Comment by JimmyKater** [comment]
Only stored on phone (well og course i have a backup somewhere). And yes again... Except for my Gmail-account (which i don't use at all) I only see 'phone storage (not visible top other apps)' option.
I didn't change anything from the version before... Except for giving the app-icon a new color in the new version (I can't remember for sure if the contacts were visible before, I tend to say yes.but this could be misleading).
But all of the contacts are visible in google-contacts, still.

**Comment by tibbi** [comment]
if in Google Contacts you select a contact and edit it, what contact source is written at it? I mean the first field under the photo. Does it say "Device", or some email?

**Comment by JimmyKater** [comment]
It says device

**Comment by tibbi** [comment]
hm ok, please send me an email at hello@simplemobiletools.com, that way I can easily send you a test debug version to see if it will work

**Comment by JimmyKater** [comment]
sent
