### ISSUE TITLE
pictures for contacts could not be loaded

### ISSUE THREAD

**Issue by mdkuser** [SimpleMobileTools/Simple-Contacts#164]
Trying to select a contacts picture from existing file, results in error "picture could not loaded".
However file pernissions and contact permissions are granted.
Trying the same but selecting "take picture" works.

**Comment by tibbi** [comment]
what android OS version do you have? Is the photo on the internal storage, or sd card?

**Comment by mdkuser** [comment]
I am using Android 6.0 with google contact app deactivated.
I tested using pictures from internal store as well as from sdcard.
Both not working.

**Comment by michaelof** [comment]
Android 6.0
simple-contacts 4.0.3
simple-gallery 4.0.0

Adding a contact's photo by "Choose photo" for an existing photo works FINE on my device. 
Maybe an issue with size of selected photo?

**Comment by mdkuser** [comment]
I installed simple-gallery and testes. If I select simple-galery to handle images and image resizing it works for contacts but if I use the preloaded motorola standard gallery the image resize dialog fails with "could not load picture" not an issue using google contact app. However taking contact picture from camera works in simple contacts...

**Comment by mdkuser** [comment]
I installed simple-gallery and testes. If I select simple-galery to handle images and image resizing it works for contacts but if I use the preloaded motorola standard gallery the image resize dialog fails with "could not load picture" not an issue using google contact app. However taking contact picture from camera works in simple contacts...
