### ISSUE TITLE
Normalize the format of phone numbers

### ISSUE THREAD

**Issue by Primokorn** [SimpleMobileTools/Simple-Contacts#169]
Hi,

In France the phone numbers have 10 figures. Example: 01 02 03 04 50
For a better visibility we put spaces every two figures.

Could you force fixed formats based on the countries?
Thank you.

![screenshot_contacts_20180514-173230](https://user-images.githubusercontent.com/5938828/40105321-ea6e28bc-58f2-11e8-94b4-8fc7c834c13c.png)

**Comment by tibbi** [comment]
I dont want to get into that, theres many different rules per country. I want to let the user decide what format he wants to use.

**Comment by Booteille** [comment]
Would you reconsider your position concerning numbers formatting? I guess I am not the only one a bit concerned about the readability of numbers. Could we find an easy to implement solution for that you would agree to implement?

**Comment by tibbi** [comment]
noone else requested it so far, so I guess it is ok. I want to keep it as it is for now, enforcing formats could become really messy.

**Comment by Booteille** [comment]
Okay. I understand. Thanks!
