### ISSUE TITLE
contacts list 

### ISSUE THREAD

**Issue by ergeka** [SimpleMobileTools/Simple-Contacts#171]
Hi,
The contacts list is emptied each time the application is updated except for the SIM card contacts.
Sincerely.
Gérard

version 4.0.3

**Comment by tibbi** [comment]
Hey, not sure what you mean. There have been some contact fetching changes recently, maybe those caused some contacts to appear/disappear. Just use the Menu -> Filter button for selecting which contact sources should be visible. Reopen if you still have some issues. Thanks

**Comment by ergeka** [comment]
All sources are checked (whatsapp, SIM1,Signal,Stockage du téléphone) !
I need to re-import my saved .vcf list from the SD card
... ?

**Comment by ergeka** [comment]
Hi,
an other bug (?) :
When importing a cvs, if the first name is empty I have an error.
-----
begin:vcard
n:Z-MATMUT
tel;home:0123456789
tel;cell:08888888
version:2.1
end:vcard
--> error = java.lang.indexOutOfBoundsExceptions index=1 size=1

-----
begin:vcard
n:Z;MATMUT
tel;home:0123456789
tel;cell:08888888
version:2.1
end:vcard
--> import ok 

Sincerely.
Gérard.
