### ISSUE TITLE
Contacts using the Signal App are listed as duplicates

### ISSUE THREAD

**Issue by Trevonn** [SimpleMobileTools/Simple-Contacts#174]

**Comment by tibbi** [comment]
try filtering them out via Menu -> Filter

**Comment by Trevonn** [comment]
That worked thank you. Hopefully this can be picked up by the "Try filtering out duplicate contacts" option in the future.

**Comment by tibbi** [comment]
well if you check the contact details, what fields do they have different? I guess the Signal contacts have just the basic fields filled?

**Comment by Trevonn** [comment]
Only the Account? field is different, it says Signal otherwise the name, phone number and group fields are filled in.

**Comment by Trevonn** [comment]
On comparing screenshots again only the account field is different.

**Comment by tibbi** [comment]
That is not enough, I guess they differ by some hidden fields then. You can customize what fields are shown at Settings -> Manage shown contact fields.

**Comment by neomodern** [comment]
Same issue with WhatsApp contacts also, can't see any differences other than Account.  Related: #53

**Comment by tibbi** [comment]
try enabling all fields at Settings -> Manage shown contact fields and check then

**Comment by neomodern** [comment]
@tibbi yeah I did that after reading your previous responses, there wasn't any other fields which showed a difference

**Comment by tibbi** [comment]
well thats weird.. Not even some small difference in their names? Maybe some special character?

**Comment by tibbi** [comment]
reopen if still not fixed in 4.0.4. Also if it still happens try exporting contacts in an .ics file and check there what fields are different.

**Comment by genodeftest** [comment]
I am still seeing this issue with version 4.1.0 (F-Droid) on Android 8.1.0.

On my phone, the names are exactly identical (no special characters), but the phone number is listed as "Other" for all my Signal contacts and as "Mobile" for the phone storage contacts. Changing it to "Mobile" for the signal contacts does not fix the issue though.
Signal contacts have nothing but Name (First and second name) and the phone number displayed in Simple-Contacts.

I'd like to export the contact in a .vcf file, but I don't know how to do that. Can you please give me a hint?

Also, please tell me if this should be reported as a separate issue.

**Comment by tibbi** [comment]
there is a menu item "Export contacts to a .vcf file", use that. You can then open the file with any text editor. Contacts are separated by "BEGIN:VCARD" and "END:VCARD" lines, so try finding those duplicate contacts and paste me the values, or send to hello@simplemobiletools.com. Feel free censoring out the names, numbers, addresses etc.

**Comment by genodeftest** [comment]
#244 is blocking me being able to provide more details, sorry.

**Comment by tibbi** [comment]
ok, I plan adding a more advanced duplicate filtering that will detect such cases, I just make sure it wont be too slow. Thanks
