### ISSUE TITLE
Contacts can't detect phone state permission.

### ISSUE THREAD

**Issue by SugaryHull** [SimpleMobileTools/Simple-Contacts#176]
I have all the requested permissions enabled, but Contacts won't add contacts because it doesn't detect the  phone permission. Is anyone else experiencing this?

**Comment by tibbi** [comment]
Im not requesting that permission since it isnt needed and it is a pretty agressive one. Do you get some error? Can you send me a screenshot of it? What app version and Android OS version do you have?

**Comment by SugaryHull** [comment]
It seemed to be working now. Apologies for the misunderstanding.
