### ISSUE TITLE
Organisation field

### ISSUE THREAD

**Issue by AqwelF** [SimpleMobileTools/Simple-Contacts#177]
It will be great if the app can show the organisation (firm they work) field of contacts.

**Comment by tibbi** [comment]
you can enable it in Settings -> Manage shown contact fields

**Comment by AqwelF** [comment]
You right thanks for that. Unless informations ate empty in this field now but exist on my owncloud server and aooears in the default contact app of my rom. I tried to resync them all but the field still empty on simple contact.
