### ISSUE TITLE
Society fields still empty

### ISSUE THREAD

**Issue by AqwelF** [SimpleMobileTools/Simple-Contacts#178]
Refers to #177 
You right thanks for that. Unless informations are empty in this field now but exist on my owncloud server and appears in the default contact app of my rom. I tried to resync them all but the field still empty on simple contact. Any clue ?

**Comment by tibbi** [comment]
not sure what is society about, it seems to be a different one than organization

**Comment by tibbi** [comment]
please retry with 4.4.0 and reopen if it is still broken
