### ISSUE TITLE
Groups tab shows empty groups / categories

### ISSUE THREAD

**Issue by limbusdev** [SimpleMobileTools/Simple-Contacts#186]
App Version: Simple Contacts 4.0.3, retrieved from FDroid

**Expected Behaviour:**

* select Groups tab
* a list of all available groups, existent in the available contacts, is shown
* empty groups are invisible or at least shown in the correct language

**Observed Behaviour:**

* several empty groups are displayed: "Coworkers(), Family(), ..."
* not only are these groups which I never used, they are also shown in the wrong language (I have a category "Familie", which is German for family, which I use - therefore I don't need nor want family)

**Possible Solutions:**

* make empty groups invisible
* offer an option to disable displaying empty groups
* show empty groups, if enabled, in the correct language

PS: great app, hope to see a dialer app soon :)

**Comment by tibbi** [comment]
shouldnt be happening anymore for some time
