### ISSUE TITLE
No "Nickname" field.

### ISSUE THREAD

**Issue by Reue** [SimpleMobileTools/Simple-Contacts#197]
We all have friends or contacts that we know better by their nicknames than by proper names.
Of course, we still have to register their real names, because we often have to address them in a formal way. But it is by their nicknames that most of the time we remember and look for the contacts of these people.
Therefore, as with other programs, this application needs a new field, called "Nickname".

**Comment by kyiami** [comment]
I'm seconding this - it's an important feature of other contact apps that this one's missing.

**Comment by tibbi** [comment]
it has been added already, has to be enabled in the app settings
