### ISSUE TITLE
Lag on open App

### ISSUE THREAD

**Issue by Mannshoch** [SimpleMobileTools/Simple-Contacts#201]
Every time I open this App I have to wait around 5 second until the contacts appear.

**Comment by tibbi** [comment]
it should be better in the next 4.2.0, but it can still be better so Ill keep it open

**Comment by tibbi** [comment]
if it will still be slow in version 4.4.0, can you tell me how many contacts do you have shown? Do you have "Try filtering out duplicate contacts" enabled? If you disable it, how many contacts do you see? What Android OS version do you have?

**Comment by n0-1** [comment]
Hi,

I think this ticket should be reopened - on my phone, displaying the contact list takes about 20s. So does displaying the list of groups and displaying group members after selecting a group to display takes the same time. This pretty much renders the app unusable.

It happens on Android 9 with Simple Contacts version 6.3.1. I have 384 contacts in my list. Filtering duplicate entries is disabled. Show contact thumbnails is is disabled, too.I have three contact sources, but only "Phone Storage" enabled in "Filter" setting.

[Here](http://nwl.cc/~n0-1/simple-contacts.log) is 'adb logcat' output while waiting for contacts list to appear. Can I provide you with anything else?

Thanks, Phil

**Comment by tibbi** [comment]
not sure how could you help now, Ill get back to it soon. Thanks

**Comment by joeyLaus** [comment]
@tibbi thanks for your hard work, hope you can fix this major issue is this is whats preventing me from using the app.

**Comment by joeyLaus** [comment]
Ive noticed it only does this if you use an account (like carddav) and not having the contacts saved locally.

**Comment by tibbi** [comment]
shouldnt be happening anymore

**Comment by GWRon** [comment]
> shouldnt be happening anymore

Still happening in v 6.12.3 Pro (and also was the case in the last free version in the play store).

Starting ... count 12 seconds and then my ~120 contacts are displayed. Tried to filter out all other stuff (device memory, sim1, sim2, whatsapp....), even disabling all of them requires 12 seconds until a "no contacts found ... change filter" message is shown in the list area.
So .. if it does not have to fetch from one of the "sources", why does it take so long?

**Comment by tibbi** [comment]
not sure, do other downloaded Contacts apps work well?

**Comment by GWRon** [comment]
Do you suggest a specific one to try out? I just tried the originally installed google contacts (see my edit - which you might have missed).
> edit: in comparison the google contacts app shows its loading icon for ~200ms and then the list of contacts.

**Comment by GWRon** [comment]
Ok ... found the issue. I have "Protect My Privacy" installed (using edxposed). So my "logcat" contained a few entries of these:
```
07-16 22:21:36.491 23137 25768 E XHookImpl: prov for com.simplemobiletools.contacts.pro could not start a connection
```
I assume the contacts-provider was not that easily to "connect".

Temporary disabling the module and it loaded in milliseconds. Dunno what "google contacts" does different so that it does not have this issue.

**Comment by tibbi** [comment]
well messing with such system things can cause a lot of device specific issues

**Comment by GWRon** [comment]
Yeah, fully understand that and really excuse the time I have stolen you by raising this issue from the dead. If the google contacts app was also slow I would have checked more deeply - but at this was fast loading I thought I simply approach to you asking for help.
Sorry for the inconvenience

**Comment by pwqw** [comment]
Both this app and the Dialer are too slow to open (4-7 seconds)
> The Moto C features a 5-inch FWVGA display, quad-core processor, 1GB of RAM, 16GB of internal storage, 5 MP fixed focus main camera, 2 MP front camera with LED flash, 2350 mAh battery, variants with only 3G or LTE and Android 7.0 Nougat.
