### ISSUE TITLE
No IM field

### ISSUE THREAD

**Issue by Reue** [SimpleMobileTools/Simple-Contacts#202]
Currently we are not limited to contacting people we know by phone or email.
In fact, today we contact many more people via their IM ("Conversations", "Jabber", "Skype", "AIM", "Yahoo", "Hangouts", "ICQ", etc.) then via their phone or email.
So I think this application, like other contact programs, should have an "IM" (Instant messaging) field, where we could introduce the "IMs" that each of our contacts uses.
I suggest, at least, the following IMs and and additional "Custom" IM:
- Conversations
- Jabber
- Skype
- AIM
- Yahoo
- Hangouts
- ICQ
- IRC
Thanks in advance.

**Comment by michaelof** [comment]
Reue,

the way you write issues, the way you expect other people to work for you, the way you ignore previous comments from others about this - your complete behavior simply is DISGUSTING!

Plesse start reading here about the nature of this project: https://en.m.wikipedia.org/wiki/Free_and_open-source_software

And please, take special care about the term "voluntarily", you've probably missed until now: https://en.oxforddictionaries.com/definition/voluntarily

Once you are ready with reading, you'll hopefully be able to understand that's solely Tibor's decision what's a bug in HIS software. Not yours. 

You're free, as it's FOSS, to clone/fork the software and change or extend whatever you like.

Do this, or if you're that dissatisfied with what Simplemobiletools are offering you, stop using it.

But please stop immediately to waste the time who want to contribute or follow this smart little project!!!

Being not able to perform this does not alkie

**Comment by tibbi** [comment]
will be added in 4.4.0
