### ISSUE TITLE
Better vCard Support

### ISSUE THREAD

**Issue by bb1a2** [SimpleMobileTools/Simple-Contacts#205]
Hi,

TEL;CELL;PREF is shown in the app as Other
Multiple identifiers are shown as Other: e.g. TEL;HOME;CELL: or TEL;WORK;VOICE or TEL;WORK;CELL

Thanks

**Comment by tibbi** [comment]
ye that is a more generic issue of supporting custom categories also at emails, addresses etc, it is already reported somewhere
