### ISSUE TITLE
Suggestion for a T-9 dialer

### ISSUE THREAD

**Issue by bb1a2** [SimpleMobileTools/Simple-Contacts#206]
How about showing the little swipe-up bar at the bottom so that dialer can be accessed from anywhere?

![app](https://user-images.githubusercontent.com/38409206/42997391-cac3cd26-8c16-11e8-8a80-2740f6f8d3e8.png)

Thanks

**Comment by tibbi** [comment]
I dont like such behaviour, it will be a new tab
