### ISSUE TITLE
Request: Contacts On Device Only

### ISSUE THREAD

**Issue by 0pLuS0** [SimpleMobileTools/Simple-Contacts#210]
Hello,

If possible in the future, could you also create a version that has all the synchronized code removed, and contacts are only stored on the device?

I know this might seem a little extreme, with the idea, that if someone doesn't want synchronization, then don't enable it. 

But I'm looking at this from the idea that someone gets our phone and turns the sync on and uploads our contacts into Google, or the other accounts you have listed for the app. Well maybe this might not seem likely, but then, nothing is impossible, so I don't want the contacts app to have this ability to sync anywhere.

I've seen crazier things happen, I just had a very well respected Android App, download and install an application on it's own, just crazy! A bug report certainly went out to the developers on this... 

Anyhow...

If you could please offer a version without this, it would be greatly appreciated.

Thanks

**Comment by tibbi** [comment]
the app is not taking care of any synchronization, it is the device. You can disable syncing in the device sync settings. Or store the contacts at "Phone Storage (not visible to other apps)" contact source.

**Comment by 0pLuS0** [comment]
@tibbi So there is nothing at all in this contacts app?

Sorry I guess I don't understand this works then, I assumed the application had to have some sort of sync ability coded into it?

Thanks

**Comment by 0pLuS0** [comment]
@tibbi So there is nothing at all in this contacts app?

Sorry I guess I don't understand how this works then, I assumed the application had to have some sort of sync ability coded into it?

Thanks

**Comment by tibbi** [comment]
no, Im not doing any sync

**Comment by 0pLuS0** [comment]
@tibbi So there is nothing at all in this contacts app?

Sorry I guess I don't understand how this works then, I assumed the application had to have some sort of sync ability coded into it?

I'm running a custom rom, that has the standard contacts on it, but this is from an AOSP based rom, on a phone that runs AndroidOne, so not sure at AOSP level or Android One there's a difference with the contact apps? I just wanted something secure, so maybe this contacts on the ROM is as secure as Simple Contacts?

Thanks

**Comment by 0pLuS0** [comment]
@tibbi sorry for the posts... :(

I'm running a custom rom, that has the standard contacts on it, but this is from an AOSP based rom, on a phone that runs AndroidOne, so not sure at AOSP level or Android One there's a difference with the contact apps? 

I just wanted something secure, so maybe this contacts on the ROM is as secure as Simple Contacts?

Thanks

**Comment by 0pLuS0** [comment]
@tibbi sorry for the posts... :(

I'm running a custom rom, AospExtened that has the standard contacts on it, but this is an AOSP based rom, for the Mi A1, so not sure at AOSP level or Android One there's a difference with the contact apps? 

I just wanted something secure, so maybe this contacts on the ROM is as secure as Simple Contacts?

Thanks

**Comment by tibbi** [comment]
the app works the same way on every android version. If you have some extra secure OS maybe it has syncing disabled by default, not sure. Look around at your account device settings.

**Comment by 0pLuS0** [comment]
@tibbi I have the sync disabled, but I like you are making FOSS apps, so I will install your contacts and calendar, anything else if you make...

Thank you very much for these apps, keep up the great work! :+1:

**Comment by tibbi** [comment]
alright thanks, enjoy

**Comment by 0pLuS0** [comment]
Oh Simple Calendar too...

Sheesh even on custom roms, I don't install any Gapps, but you still get a few of the basics... :(

Thank goodness for Terminal Debloater... :+1: 

I like to be GoogleFree! By the way, that might change if the EU wins over this new Google Trustsuit... hmm

One screen shot coming up!


![screen](https://user-images.githubusercontent.com/36190223/43124722-7c974d86-8f17-11e8-9515-089ce9b8ce25.jpg)



THANKS again! :+1:

**Comment by tibbi** [comment]
in the Calendar you have to explicitly "CalDAV sync" in the app settings for the sync, that is not enabled by default as it works in a whole different way

**Comment by 0pLuS0** [comment]
I don't use Sync on any of my devices, I have no need for it, but thanks for the heads up...

By the way, PLEASE consider making a phone app?

----> ```Simple Dialer``` 👍

**Comment by 0pLuS0** [comment]
I don't use Sync on any of my devices, I have no need for it, but thanks for the heads up...

By the way, PLEASE consider making a phone app?

----> ```Simple Dialer``` 👍 

I'm into being as ```Google Free``` and all microG, Xposed 100% FOSS!

**Comment by 0pLuS0** [comment]
I don't use Sync on any of my devices, I have no need for it, but thanks for the heads up...

By the way, PLEASE consider making a phone app?

----> ```Simple Dialer``` 👍 

I'm into being as ```Google Free``` and all microG, Xposed 100% FOSS!

Almost forgot to mention, I installed your Gallery, I like it!

I tried the camera, doesn't work on my phone, and I didn't find the Simple Clock working as well as the Google Clock. When I set the alarm on the Simple Clock it didn't ring... hmm

Thanks

**Comment by 0pLuS0** [comment]
I look foward to seeing the ```Simple Dialer``` 

Well the stock Android Clock worked and the alarm rang, and Simple didn't. 

So if the system default clock was bad, then it shouldn't ring too, I don't see that one works, and one doesn't and then we call that a system error, unless the Simple Clock works in a different manner?

I just look at it, since the Android Clock worked, the Simple Clock should of...

hmm

**Comment by tibbi** [comment]
aha, thought you mean that Google Clock didnt work well either. Well if you read through the Google Clock reviews it is broken to a lot of people, they just cannot make it fully reliable either. Ill see how can I improve it further.

**Comment by 0pLuS0** [comment]
Ahh ok, the less Google the better! WoOT :1

**Comment by 0pLuS0** [comment]
Ahh ok, well the less Google apps for me, the better.

Thanks
