### ISSUE TITLE
Format non us phone number 

### ISSUE THREAD

**Issue by benjaminabel** [SimpleMobileTools/Simple-Contacts#213]
Hello I'm French and the phone numbers are displayed in an English way: 

061-123-1234

Instead of: 06-11-23-12-34.

if prefix is given(+33) format is +33611231234. I don't know if there is an iso for this.

**Comment by tibbi** [comment]
Im not formatting the numbers in any way, I just display whatever is stored in the device. I can keep it here for future reference.

**Comment by benjaminabel** [comment]
In fact this formatting has been done when exporting my contacts from the g00gle contacts! Thanks for your answer and these apps.
