### ISSUE TITLE
Importing contacts with more than two parts of a name breaks editing

### ISSUE THREAD

**Issue by kyiami** [SimpleMobileTools/Simple-Contacts#216]
Don't have a screenshot for privacy, sorry. 

I migrated my contacts made in the default Samsung contacts app over to Simple Contacts. 90% of the contacts worked, but ones with more than two parts of a name (for example, two last names) didn't. 

They show up normally at first glance, but when on the profile page or the editing page, anything in between the first and last name is both uneditable and does not show on the profile page, but stays on the contacts list.

I suggest grouping all names past the first one into the surname category, with spaces separating them. Side note - dashes work perfectly.

**Comment by Finnerale** [comment]
This is not a bug, but rather a hidden feature. In the settings you can 'Manage shown contact fields' and the middle name is hidden by default.

**Comment by kyiami** [comment]
Hmm, it probably would be better if the middle name and prefix were enabled by default.

**Comment by tibbi** [comment]
importing/exporting has been rewritten from scratch, please retry with 4.3.x
