### ISSUE TITLE
Two contacts about one person 

### ISSUE THREAD

**Issue by happyreacer** [SimpleMobileTools/Simple-Contacts#218]
Smartphoneos: Android 7.1.2
App version 4.1.0
I use additional the App "Telegram". 
synchronisation my contacts with davdroid from a nextcloud server

I have one person in my contacts app with two contacts. One of them ist only with my Telegram contact and the other with oll the other data about fonenumber an adress.

I hope in one of the nex versions you can joining the two contacts from one person.

**Comment by RoughCurve** [comment]
Can confirm this bug on lineageOS 14.1, android 7.1.2. WhatsApp creates duplicate entries.

**Comment by MartinGSch** [comment]
I have the same on a Sony phone... and taken some screenshots with details. 
In case the root cause of the issue is not fully clear to you, drop a "yes, please" here - shall I upload them here?

**Comment by happyreacer** [comment]
I have test it on lineageos 15.1 (Android 8.1) again.
It is the same result with two contacts for one person

**Comment by tibbi** [comment]
try exporting your contacts in a .vcf file please and comparing the contacts there. Just open the .vcf file with any text editor and look for parts with "BEGIN:VCARD" and "END:VCARD". What do they differ by? Or you can also long press the 2 contacts, press Share and send it to yourself via email.

**Comment by happyreacer** [comment]
The one .vcf file with the Telegramaccount  have only:
```
VERSION:3.0
PRODID:ez-vcard 0.10.4
N:Max;Mustermann
```
The other .vcf File have 
```
VERSION:3.0
PRODID:ez-vcard 0.10.4
N:Max;Mustermann
TEL;TYPE=CELL:+123456789
EMAIL;TYPE=HOME:max@mustermann.com
BDAY:1999-12-12
```

**Comment by tibbi** [comment]
well the 2nd contact has by 3 fields more filled in. Im handling only cases when one contact has extra phone numbers, not email and birthday too. I dont really want to filter duplicates if they differ by 3 fields, that would be too agressive.

**Comment by happyreacer** [comment]
can you adapt a option to merge two contacts?

**Comment by tibbi** [comment]
maybe in the future it will be added, we will see

**Comment by happyreacer** [comment]
can you adapt a option to merge two contacts?
