### ISSUE TITLE
no f droid release

### ISSUE THREAD

**Issue by xificurC** [SimpleMobileTools/Simple-Contacts#22]
still working on it? The buttons go to a 404

**Comment by tibbi** [comment]
ye working on it right now

**Comment by xificurC** [comment]
I see, thanks for the heads up. Is the contact app feature complete? The calendar app looks great so far, len tak dalej :)

**Comment by tibbi** [comment]
well it is the initial release with the core functionality done, there's still some things on the roadmap :)

**Comment by IzzySoft** [comment]
@tibbi Have you already created an RFP (Request For Packaging) with F-Droid? Besides, they currently experience problems with their build server again, so all new updates are delayed.

Meanwhile, you can find [SimpleContacts in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.simplemobiletools.contacts), which can also be used with the F-Droid app. Updates will be picked automatically within 24h of your adding a new tag and attaching the `.apk` to it. As soon as your app becomes available in the main repo, feel free to drop me a note if I shall remove it from mine.

PS: Big :+1: for taking privacy seriously and avoiding the `INTERNET` permission! When it comes to personal data such as contacts and calendars, that's what I prefer in an app. Not saying apps with `INTERNET` permission *really do* bad stuff – but if that permission isn't there, one can't even *suspect it might* :wink:

**Comment by tibbi** [comment]
Hey, they already accepted my pull request, so the app should be added the next time some build script runs. Ive seen their issues too, but I can wait :) You can leave the app on your site, I don't mind. Thanks

**Comment by IzzySoft** [comment]
Ah, I should have checked… Did you use a "reproducible build", or does F-Droid sign with their own key? In the latter case that might lead to confusion with updates. Guess I better take it out of my repo as soon as it is available via the main repo then, to avoid that.

**Comment by tibbi** [comment]
they sign it with their own key. I did it with the same way as all previous apps, it seems to be updating properly. With some delay obviously, but it does update.

**Comment by IzzySoft** [comment]
Yes, it sometimes takes up to 2 weeks. "Reproducible builds" have been introduced only recently: with those F-Droid builds their own APK and compares that against the one you provide; it the two match, *yours* will go into the repo. That way cross-updates are possible (i.e. users can update from F-Droid even if they originally installed from Playstore or Github). And in that case, there wouldn't be any "confusion" with the APK from my repo (which is taken from your Github releases, and thus signed with your key) – except that those using it get their updates earlier :wink:

**Comment by tibbi** [comment]
aha ok thanks, I will take a look at it someday. They also added the option to add screenshots lately, but I would have to setup fastlane for that, which I dont feel like doing yet. The problem with f-droid is the lack of analytics, I just have totally no idea how many people are actually using my apps there. Since f-droid isnt on any social network, I have no idea how popular is f-droid itself either. So I have the apps on f-droid, I just dont have any motivation for spending too much time optimizing the apps for it.

**Comment by IzzySoft** [comment]
That's the trouble with us tin-foils: we value our privacy pretty high. But to find a compromise, you could consider an **opt-in** (important!) FOSS (also important!) analytics framework (see [here in the F-Droid FAQ](https://f-droid.org/en/docs/FAQ_-_App_Developers/#can-i-track-users-from-my-app) for details on such library use wich basically says the same: FOSS, opt-in). IIRC, at F-Droid they often name [acra](https://github.com/ACRA/acra) in this context, but that seems to cover crash reports only. Not being an Android dev, I didn't dig into what solutions might exist.

By the way: the F-Droid build server seems to be working again. I just saw the first 2 new apps turning up yesterday. Hopefully it keeps running, so Simple Contacts will turn up soon as well!

**Comment by tibbi** [comment]
ye I know acra, but thats not the kind of analytics I want to add in the apps, as it needs internet permission too. All I'd like to get from f-droid is a number of how many people install my apps daily, nothing else. I dont want to track button clicks or anything like that.

**Comment by tibbi** [comment]
seems like they added it already
