### ISSUE TITLE
Dialer app needed

### ISSUE THREAD

**Issue by jerryn70** [SimpleMobileTools/Simple-Contacts#224]
My phone is moto x play . Stock android 7.1 . My phone uses google contact app and it's dialer.
So if i disable my default contacts app and try to  use yours, then your app will not work, means it will not import contacts/will not show contacts. 

The problem is my default contact app and dailer app are linked . So I need to disable my dailer app also . Then only your app will work in my phone.

If I do that then there is no way to dail a phone call. 

So it will be helpful if you create dailer app for this contact app. A seperate dialer app is perfect.

**Comment by tibbi** [comment]
it will be added as a part of Contacts, Im already getting there step by step

**Comment by Hal47** [comment]
I'm glad to hear. There is no open-source dialer option in the wild yet.

**Comment by ouzowtf** [comment]
@Hal47 there is at least one: https://f-droid.org/app/ru.henridellal.dialer

**Comment by Hal47** [comment]
@ouzowtf Thanks, I had no idea that had released. I'll check it out.

**Comment by BWPanda** [comment]
Would a feature request for notification of missed calls go in the upcoming dialer app, or the general contacts app?

**Comment by BWPanda** [comment]
Hmm, I must have forgotten to set it as default then... I left the stock 'Phone' app installed as I thought I read somewhere that you can't make emergency calls from other apps. Is that the case here, or can I safely uninstall the stock dialer app? It's obviously not good form to make a test call to the emergency number ;-)

**Comment by tibbi** [comment]
Not yet. The Dialer still isnt implemented in the Contacts, that is what this ticket is about.

**Comment by tibbi** [comment]
an initial implementation of the Dialer will be added in 6.1.0 released soon. It will still rely on the preinstalled Phone app though, more will come in the future

**Comment by neolovich** [comment]
That sounds great. Thank you very much :)

**Comment by tibbi** [comment]
sim cards are handled by the system, not me. In my tests dual sim cases worked just fine.

**Comment by neolovich** [comment]
> sim cards are handled by the system, not me. In my tests dual sim cases worked just fine.

Yes, you are right. So i have to clarify what i meaned: I know dialer apps, that offer the possibility to choose for every number which sim card should be used. And they save this choice. My stock dialer only supports to choose the sim card for all calls. But when i want to make all calls to mobile numbers with the one sim card and all calls to fixed-lines (or landline) with the other sim card, i cant choose this. Maybe you can add this helpful option one day.
Its just a detail and so far i tested your dialer with two sim cards it works fine :) Thanks!

**Comment by tibbi** [comment]
Well I can set which sim card should be used with which number in Simple Contacts too one by one. I wasnt implementing that function at all, the system takes care of that.

**Comment by neolovich** [comment]
> Well I can set which sim card should be used with which number in Simple Contacts too, one by one

And how do i do that? Everytime i tap on a number in Simple Contacts the stock dialer asks which sim card should be used. Simple Contacts deosn't seem to save my choice.

**Comment by tibbi** [comment]
Simple Contacts doesnt save it, as it isnt handled by me. Either the stock contact app handles it, or the system, Im not sure. If you cannot change it, just wait for the fully customized dialer I guess.

**Comment by tibbi** [comment]
since Google meanwhile strictened their new security rules, I will be removing the Recents tab from the app. I wont be able to access it as it isnt the main objective of the app. I will have to create a standalone Phone app with a real dialer someday, only that will be able to show Recents. So Ill close this issue as there wont be any more work on it inside the Contacts.
