### ISSUE TITLE
Allow installation on tablets

### ISSUE THREAD

**Issue by joede** [SimpleMobileTools/Simple-Contacts#236]
I would like to use "Simple Contact" as a replacement of Googles "Contacts" on my Samsung Galaxy S2 9.7 tablet. Sadly, the app can't be installed because it isn't "compatible".

Is there a way to change that?

**Comment by tibbi** [comment]
a couple people reported that already, but Im not sure why does it happen. Ill take a look at it.

**Comment by joede** [comment]
May be the reason for that are the PHONE permissions?

**Comment by tibbi** [comment]
that shouldnt be related

**Comment by Dirkster99** [comment]
@joede I got the app to run in a tablet emulation inside the development environment (Android Studio) see screenshot - so technically, it seems to be fine to run but maybe you are facing un unrelated (setup specific) issue - so, whats the exact step/problem you are running into and cannot seem to get past
-> Can you provide a specific error message and step by step procedure to verify your exact prolem?

![tablet](https://user-images.githubusercontent.com/2129700/44994906-0e575500-afa1-11e8-86dd-9262a391699d.png)

**Comment by tibbi** [comment]
he cannot even install it, something on playstore is preventing it. I dont know what.

**Comment by tibbi** [comment]
Ive tried changing something in 4.4.0, please retest whenever it becomes available. It should be within the next few days.

**Comment by joede** [comment]
As soon as it is visible, I'll give it a try. By the way... the Play Store on the tablet doesn't even find the app. :-/

**Comment by joede** [comment]
Sorry for the delay... I was able to install it and this release works as expected. Thanx!
