### ISSUE TITLE
Feature Request : Enable listing contacts by display name

### ISSUE THREAD

**Issue by GLLM** [SimpleMobileTools/Simple-Contacts#237]
Hi !

Thanks for this great lilttle app !
I have a few suggestions in mind, one fof them being the following :

I'd like my contacts list to be able to use the Display Name, rather than a combination of First Name & Surname. If no Display Name exist, use the name/surname instead.
Indeed, my father, named John Doe, as a display name set to Daddy. My wife (named Jane Jungle) has the following display name : Darling. I also have a contact named Barack Obama, his display named is empty :-)

Currently, the contacts lists & favorites list is:
* John Doe
* Jane Jungle
* Barack Obama

I'd love the contact app to be able to show (thanks to a setting ?):
* Daddy
* Darling
* Barack Obama

What do you think ?
Thanks
GLLM

**Comment by tibbi** [comment]
you can already sort contacts by full name, I dont want to use sorting by one value and showing something else
