### ISSUE TITLE
Suggestion: Contact design

### ISSUE THREAD

**Issue by Phoenix1747** [SimpleMobileTools/Simple-Contacts#24]
Hi, I don't know what you plan to do in the future and I know that this app is in a really early stage but hey, I guess feedback is always good.

So, I think what'd make the app much nicer is more space between the contacts (not much only a couple of px more) and maybe a couple of randomly-assigned colorful contact images if no image has been provided by the user.

**Comment by tibbi** [comment]
well I dont really plan changing it as this is the size I use in all apps for consistency and I dont want to make the app look like a rainbow, but I can leave it here ;)

**Comment by Phoenix1747** [comment]
Not like a rainbow, more like slightly colored profiles not this all grey look :P

**Comment by tibbi** [comment]
Ill close it as I dont really plan adding it :) A toggle for hiding thumbnail has already been added.

**Comment by Phoenix1747** [comment]
Ok :/
