### ISSUE TITLE
Disappearing from the app menu

### ISSUE THREAD

**Issue by ReekyMarko** [SimpleMobileTools/Simple-Contacts#243]
I don't know if this is an issue with my specific setup, or a bug in this app, but since the last update from F-Droid 3 days ago (4.3.0). Simple Contacts has disappeared from my application menu. I can get it to show up when I uninstall and reinstall but it disappears shortly after that. I can still access it from recents just fine.

**Comment by ouzowtf** [comment]
I had this problem too a few weeks ago, but a reinstall solved it permanently for me or it was fixed with an update of my launcher (Nova).

**Comment by tibbi** [comment]
It could be related to app icon color customization. Dont you have the Shared Theme enabled with Thank You installed which might change the icon color automatically? If you do, try disabling it.

**Comment by ReekyMarko** [comment]
Yeah I turned off the shared theme and now it works again

**Comment by tibbi** [comment]
ok, it is a more general issue, some launchers dont handle icon customization well. Not sure if theres anything on my side that could be improved, seems like not.

**Comment by ReekyMarko** [comment]
Just to add to this, I'm not having the issue with other simple apps that have the shared theme enabled

**Comment by tibbi** [comment]
hm, that is weird. Can you compare 2 apps, lets say Contacts and Gallery? Find them in your device settings, do a "Clear Data", then reinstall them. Do they still behave differently? Or pick something else instead of the Gallery, if you dont want to reset your settings. All apps have the latest implementation related to icon colors.

**Comment by ReekyMarko** [comment]
I tried to clear data and reinstall both calendar and gallery. No issues on these two using the shared theme. And I even tried to re-enable the shared theme on contacts too,and the icon for it hasn't disappeared yet. This is very weird
