### ISSUE TITLE
Cannot export contacts to .vcf file: IllegalArgumentException [Regression 4.2.2 -> 4.3.0]

### ISSUE THREAD

**Issue by genodeftest** [SimpleMobileTools/Simple-Contacts#244]
Steps to reproduce:
1. Have a few contacts **EDIT:** with no year for birthday. You may want to use the Google contacts app for creating such a contact
2. Open Simple-Contacts app in main view (list view)
3. Click three-dot menu
4. Click "Export contacts to a .vcf file"
5. Select any folder (e.g. "Documents")
6. Keep defaults (exported contact sources: Signal and Phone storage)
7. Confirm (click "Ok")

What happens:
It creates an empty file and does not export any file content. Instead, I'm getting this error:
    An error occured:
    java.lang.IllegalArgumentException:
    [Error 37] Month must be between 1 and 12 […]

What should happen:
Export contact list just fine.

Additional info:
Android 8.1.0, patchlevel 2018-08-01
Nokia 5, Model TA-1053

Opening a file manager on the device shows that the file has been created with a  size of 0. On a computer (Fedora Linux) attached to the device, the file does not show up as if it were never created.

`adb bugreport` does contain a syslog, but that syslog does not contain the exception or stack trace. I've attached some of its contents by section here:
[preamble](https://github.com/SimpleMobileTools/Simple-Contacts/files/2339465/preamble.txt), 
[EVENT LOG](https://github.com/SimpleMobileTools/Simple-Contacts/files/2339466/EVENT.LOG), 
[SYSTEM LOG](https://github.com/SimpleMobileTools/Simple-Contacts/files/2339467/SYSTEM.LOG)

**Comment by genodeftest** [comment]
This issue may be related to #211 and probably is a regression caused by c0720e3e7311b6299f979ae732ecbe7cd43df664. It is present in version 4.3.0 but not in 4.2.2.

**Comment by tibbi** [comment]
ye seems so, thanks

**Comment by genodeftest** [comment]
I *think* that this exception is caused by the fact that I have a few contacts with a birthday without a year. With version 4.2.2, exporting those to a .vcf file gives a line like this:

    BDAY:--01-01

Workaround: Specify a year for each contact and this issue is gone.
