### ISSUE TITLE
Cannot export contact with fax number to vcf file: NullPointerException [Regression 4.2.2 -> 4.3.0]

### ISSUE THREAD

**Issue by genodeftest** [SimpleMobileTools/Simple-Contacts#245]
Steps to reproduce:
1. Have a few contacts
2. Open Simple-Contacts app in main view (list view)
3. Click three-dot menu
4. Click "Export contacts to a .vcf file"
5. Select any folder (e.g. "Documents")
6. Keep defaults (exported contact sources: Signal and Phone storage)
7. Confirm (click "Ok")

What happens:
It creates an empty file and does not export any file content. Instead, I'm getting this error:

    An error occured:
    java.lang.NullPointerException:
    Attempt to invoke virtual method
    'java.lang.String ezvcard.parameter
    .VCardParameter.c() on a null object
    refere[…]

What should happen:
Export contact list just fine.

Additional info:
This is a regression in 4.3.0. Exporting the same contacts worked fine with 4.2.2. This issue may be related to #211 and probably is caused by c0720e3.
Android 8.1.0, patchlevel 2018-08-01
Nokia 5, Model TA-1053

Opening a file manager on the device shows that the file has been created with a  size of 0. On a computer (Fedora Linux) attached to the device, the file does not show up as if it were never created.

**EDIT:**
The issue is caused by a fax number. Workaround: Save fax number as something else.

**Comment by genodeftest** [comment]
Interestingly, even though exporting fails (the resulting file is empty), I get the message "Exporting successfull" drawn as an overlay over the app. This was also true for issue #244.

Also, I cannot get the backtrace on `java.lang.NullPointerException` (same as in #244). It is only being displayed in a short-living overlay over the app. Can you please make the exception+backtrace being logged to syslog too?

**Comment by genodeftest** [comment]
I've bisected my contacts list to two contacts which are affected.

First one (exported from Google Contacts):

	BEGIN:VCARD
	VERSION:2.1
	N:Surename;Forename;;;
	FN:Forename Surename
	TEL;HOME;FAX:+1234567890
	TEL;HOME:+987654321098
	ADR;HOME:;;Street 15;;;;
	END:VCARD

Second one (Shown as two separate contacts due to #174; Exported from Google Contacts):

	BEGIN:VCARD
	VERSION:2.1
	N:Surename;Forename;;;
	FN:Forename Surename
	TEL;HOME;FAX:+1234567890123
	TEL;CELL:+98765432101
	TEL;CELL:+1298765432101
	END:VCARD

Both have the `TEL;HOME;FAX:` field in common. If I change this field to something else, e.g. a pager (`TEL;TYPE=pager:`) or a mobile phone number, exporting works just fine.

**Comment by tibbi** [comment]
should be fixed in 4.4.0
