### ISSUE TITLE
UX: Selecting a date is very hard

### ISSUE THREAD

**Issue by genodeftest** [SimpleMobileTools/Simple-Contacts#246]
Steps to reproduce:
1. open Simple-Contacts
2. edit any contact
3. add a birthday
4. select birthday date

What happens:
If the year is long gone (e.g. 1990), it takes very long to select the correct date. In 2018, selecting a year 1988 takes about 30*12=360 clicks on the "previous month" button.

What should happen:
Have an easier way to select the date. It should be possible to select the year independently from month and day. The default Google contacts app does this quite nicely.

Additional info:
Tested with Simple-Contacts version 4.3.0

**Comment by ouzowtf** [comment]
You can tap on the year and select it separately.

**Comment by tibbi** [comment]
yep, Im using standard android date/time pickers, people are used to them. Just click on the year to select it.

**Comment by genodeftest** [comment]
Thank you very much and sorry for the noise.
