### ISSUE TITLE
Be able to copy phone number

### ISSUE THREAD

**Issue by Lucki** [SimpleMobileTools/Simple-Contacts#250]
I can't find a way to copy the phone number or other fields into the clipboard or share menu.
I was surprised I couldn't find a way to perform this simple task. Often you need to paste your phone number somewhere or want to share only the address of a contact.

**Comment by tibbi** [comment]
you can long press the phone number to select it. That is the native android way of selecting text, I dont want to flood the UI with an extra button.

**Comment by Lucki** [comment]
Long press would be fine, no need for an extra button. But right now this does not copy the number.

**Comment by tibbi** [comment]
I mean long pressing or double tapping at the edit screen, not view. But ye, guess I can add long press to copy on the view screen too.

**Comment by Lucki** [comment]
That'd would be nice. Sorry that I've forgot to mention the view contact screen.
