### ISSUE TITLE
FR: Support selecting source phone number when calling from a phone with dual SIM

### ISSUE THREAD

**Issue by justjulian** [SimpleMobileTools/Simple-Contacts#258]
My phone supports two SIM cards. When I click on a number in Simple Contacts, it opens the dial app and is making a call using the first SIM card.
I would like to be able to select which number I want to use for the call.

**Comment by michaelof** [comment]
@justjulian 

I also have a dual sim phone. Cool thing, funny IMHO that usually only the cheap phones offers this.

Nevertheless, selecting the card for a call is an issue of android / the dial app and IMHO or AFAIK not a job of any other app like Simple Contacts.

My current smartphone with Android 6 is my third with dual sim support, so  I know for sure for 4.2, 4.4 and 6 that Android offers you to 

- set a specific card (1 or 2) as default for calls, or
- set "choose always", in which case you'll get a popup dialogue, asking directly before the call which card should be used for the next call

You can specify this for outgoing calls and for outgoing sms.
In Settings / SIM Management. 
Or in the dialer / sms app, when they are open, in the background some sort of popup is always open, like a notification.

I can confirm that this works perfectly for me with Simple Contacts, when Simple Contacts passes the phone# to the dialer and e.g. "choose always" is currently set, dialer app asks me for the desired sim. 

Remark: Android is doing even even more, as I'm using sip clients for voip, like e.g. linphone, I'm asked at first which app I want to use for the call, and when selecting the gsm dialer, I was asked for the sim.

Remark 2: Out of scope, but maybe a pitfall to be avoided: When using your smartphone via bluetooth in a car, be sure, at least in all cases I know, to set sim card option to card 1. I don't know any car able to handle "choose always" or "card 2", you'll get misleading errors like "line busy" or "no carrier" etc.

![simmgmtgeneraloptions](https://user-images.githubusercontent.com/15951622/45838079-235a1500-bd11-11e8-930a-c062be40bc13.png)
![simmgmtcalloptions](https://user-images.githubusercontent.com/15951622/45838087-294ff600-bd11-11e8-9f28-f81d5ce2043e.png)

**Comment by michaelof** [comment]
@justjulian 

What is your Huawei doing when you choose "Not Set": Nothing, no call?? 
Or maybe the same than my phone does when set to "Choose always"?

Just an idea :-)

**Comment by justjulian** [comment]
@michaelof 
Not set is my current setting and the standard dial app then always asks me which number to use. So yes, not set probably means always ask in this context but Simple Contacts doesn't ask. When I click on a number in Simple Contacts it just forwards it to the default dial app anyways. So I actually would expect the default dial app to ask me which number to use but it's always using the first SIM card.

**Comment by michaelof** [comment]
@justjulian 

I'm a little bit confused, do I understand you correctly:

When sim mgmt option set to "Not set",  you're saying that if you are

- in your stock dialer app and e.g. select a number from the recent call history, your stock dialer asks you to choose a sim, finally dials out using the selected card?
- e.g. in your stock contacts app and clicking on contact's phone#, phone# is passed to your stock dialer, and your stock dialer asks you to choose a sim, finally dials out using the selected card?
- in Simple Contacts and clicking on contact's phone#, phone# is passed to your stock dialer, but the "not set" option is ignored, and the stock dialer dials out using the card 1?

**Comment by justjulian** [comment]
@michaelof 
yes, you summarized it perfectly. one little detail: on the screen where I can select a (recent) number to dial, there are two buttons to trigger a call, each representing a SIM (see photo). Hence, in those screens the button to trigger the call already contains the information which number to use. But when I'm selecting a contact in the stock contact app it behaves as you described: I select a number to call and then it asks me which SIM I want to use.
![2018-09-21 15 45 47](https://user-images.githubusercontent.com/788673/45886090-76d36e00-bdb8-11e8-89aa-aec7e19c1231.png)

**Comment by michaelof** [comment]
@justjulian 

Just my five cents: IMHO you are describing a bug in the non-Android-standard way your Huawei dialer app deals  with initiating a dual sim call. 

No idea if Tibor will find an easy way to workaround  this bug, but IMHO dealing with the desired sim is job of the dialer, once the number is passed from (whatever) contact app. IMHO never an issue of Simple Contacts.

**Comment by tibbi** [comment]
I dont have any experience with dual-sim devices, I will research it whenever I will be working on it. Ill try getting the best and expected user experience, not just some other app. We will see how will it end up :)

**Comment by tibbi** [comment]
Simple Contacts will be able to make calls from version 6.1, but it will still partially make use of the preinstalled Phone app. Anyway, dual sim is handled by that app, not Simple Contacts.
