### ISSUE TITLE
Incomplete birth dates (just day and month)

### ISSUE THREAD

**Issue by Atalanttore** [SimpleMobileTools/Simple-Contacts#264]
Hi

I would like to add and get displayed incomplete birth dates (just day and month) in Simple-Contacts.

It's possible to add incomplete birth dates in other programs, e.g. Thunderbird, and I use that for new contacts which I don't want to ask for the exact year of birth, respectively, the age. The year of birth is also not necessary to be reminded of a birthday.

Regards,
Atalanttore

**Comment by Atalanttore** [comment]
Meanwhile Simple-Contacts shows incomplete birth dates (only day and month), but unfortunately adds the number "3" as year. When saving changes the wrong birth year will also be synchronized to my CardDAV provider.

Regards,
Atalanttore

**Comment by rugk** [comment]
Hmm, it works for me, however it's still not really good: https://github.com/SimpleMobileTools/Simple-Contacts/issues/565

**Comment by Atalanttore** [comment]
This is good news, but how to enter a birth date without a year is not clear to me. I also don't understand why you can enter several birthdays for one contact in Simple-Contacts.

**Comment by tibbi** [comment]
just enable the "Hide year" checkbox. Sadly the UI doesnt allow hiding the year in the date picker, but it will be ignored.
