### ISSUE TITLE
Words in field `displayname` are separated in different lines

### ISSUE THREAD

**Issue by Atalanttore** [SimpleMobileTools/Simple-Contacts#265]
Hi

Several words in the field `displayname` are displayed in different lines in Simple-Contacts.

Steps to reproduce:
1. Create a new contact in another program (e.g. Thunderbird)
2. Add several words in the field `displayname` (e.g. John James Jean Johnson Anderson Richardson)
3. Sync
4. Open Simple-Contacts
5. Search for this new contact
6. Open this contact

Regards,
Atalanttore

**Comment by tibbi** [comment]
ye Im not using DisplayName, it is split into first name etc. Im using https://github.com/mangstadt/ez-vcard for parsing the name, so it is up to them how they split it.

**Comment by Atalanttore** [comment]
Then I would like to disable the parsing of the name, because I would rather do it myself.

**Comment by tibbi** [comment]
well Im not going to disable it, or making it optional. Try filling the name fields separately then, not using the generic `displayname`.

**Comment by Atalanttore** [comment]
What name field is intended for a company name consisting of several words?

**Comment by tibbi** [comment]
Company

**Comment by Atalanttore** [comment]
Unfortunately, I cannot reproduce this behaviour with a newly created contact (😕), but some of the existing contacts with company name only doesn't appear in Simple-Contacts.
