### ISSUE TITLE
Losing my contacts when adding accounts

### ISSUE THREAD

**Issue by marnux** [SimpleMobileTools/Simple-Contacts#267]
I have imported my contacts to the Phone storage (the one visible to applications) when i reinstalled my LineageOS. It seems to be working fine up until the moment that i add an account or accounts. At that point the contacts app becomes empty. If i check the filtering options, i see the account(s) and the private phone storage as options, not the public phone storage. I also tried to disable the suppression of duplicates, as suggested in other issues. Nothing seems to work, only deleting the account(s) restores the contacts in the app.
I did test syncing a contact to my google account and as soon as i do that, it shows up in the contacts app. This is off course not my  desired way of working, as i don't want to sync my contacts to google. They still need to be available though to some other applications. I try to keep my apps as open as possible, so using the provided contact app is not an option.
I have tested this with 4.2.x, 4.3.x and 4.4.0 from fdroid on lineageos 15 and 16

Possibly also related to #257

**Comment by marnux** [comment]
I have some time today, so i'll check some other releases. Yell if you want to have some testing done. Unfortunately i'm not familiar with android development.

**Comment by tibbi** [comment]
well the android contacts storage still contains many unexplainable mysteries to me, so Im not sure what could you test :) I guess trying out a few previous versions might help, if you find out something.

**Comment by marnux** [comment]
Same behaviour on on all 4.+ packages.
With 3.5.3 i can have accounts and still have contacts in the phone storage.
- Install
- Import contacts -> all well
- Add account -> contacts gone
   - Account doesn't show up in filter.
- Import contacts -> all well
- Remove account -> contacts gone
- Import contacts -> all well

Biggest difference between 3.5.3 and 4.x, I see, is that accounts don't show up inside the app in 3.5.3 and that phone storage does not show up in 4.x when there is at least one account.

**Comment by marnux** [comment]
Dove into the developer documentation and searched the net and it may be that this is Android forced behaviour. When there are no accounts, you will add contacts to a local storage in the contacts provider. As soon as you add an account of some sort, those contacts will be associated with the newly created account and synced. At least if you didn't turn off automatic syncing.
There used to be an option to give the contact an extra property to indicate it was local and should not be synced, but i can't find that option anymore.
Seems like the only option now is to create an actual account that does not sync to a server or have an account that you force to sync to a server you control.

**Comment by tibbi** [comment]
recheck with 5.0.1 please, once it becomes available
