### ISSUE TITLE
Inserting new contact, needs both or neither of ACCOUNT_NAME and ACCOUNT_TYPE

### ISSUE THREAD

**Issue by exks** [SimpleMobileTools/Simple-Contacts#270]
Started Simple Contacts and immediately created a new contact entry in an empty address book that had been set up previously, backed by a DAVdroid account. (I have had this work previously.) When I attempted to save it, a toast error popped up stating to the effect that "either both or neither of ACCOUNT_NAME and ACCOUNT_TYPE must be set", (didn't capture it, sorry.) After that the contact could not be saved again; I had to cancel out. The problem was repeatable several times in a row by creating a contact and trying to save it.

The problem went away after I switched the target address book to Phone Storage and inserted a contact there successfully, deleted it, then switched back to the DAVdroid account and inserted successfully there.

Environment:
Android 8.0
Simple Contacts 4.5.0

**Comment by tibbi** [comment]
recheck with 5.0.1 please, once it becomes available, reopen if it still broken
