### ISSUE TITLE
WhatsApp doesn't see the contacts

### ISSUE THREAD

**Issue by 12people** [SimpleMobileTools/Simple-Contacts#273]
When I add a new contact to the app, WhatsApp doesn't see it. It sees it neither in the case that I add it via Simple Contacts, nor when I add it through WhatsApp's "New contact" button.

In order for WhatsApp to see a contact, I need to use Google's Contacts app.

I'm using Android Marshmallow on the Nexus 5 (no ROM, no root).

**Comment by tibbi** [comment]
recheck with 5.0.1 please, once it becomes available

**Comment by anat0lius** [comment]
It's happening to me too. In Android 10.

I see the contacts are stored in "Phone storage (not visible by other apps)". 
They are so hidden that not even the Simple Dialer can access them.

I have Google Contact disabled.

**Comment by tibbi** [comment]
that is an unrelated issue. Adding support for those private contacts is on the roadmap. They should be seen by Simple Dialer and Simple SMS Messenger, no other apps.
