### ISSUE TITLE
Contacts get deleted

### ISSUE THREAD

**Issue by 12people** [SimpleMobileTools/Simple-Contacts#274]
Some of my contacts seem to get deleted after a while. I still haven't figured out how/when/why.
Oddly enough, not all contacts get deleted—I have a stable number of contacts in my contacts list.

May be related to bug #267 .

I'm using version 4.4.0 on Android Marshmallow on the Nexus 5 (no ROM, no root).

**Comment by tibbi** [comment]
arent they stored on a SIM card? People seem to lose those too after phont restart.

**Comment by Katalysator42** [comment]
Same here: contacts get deleted and I don't know how/when/why.
The deleted contacts have in common that they aren't linked to messengers like Signal or Telegram.
Other contacts are stable in my contacts list, like @12people reported.
Contacts are not stored on a SIM Card (I don't see an option to store them on a SIM Card).

I'm using version 4.5 from Google Playstore on Android 8.1 Oreo (no root) on the Nexus 5X.

This wouldn't be as big of a problem if I could import my .vcf backups, but this doesn't work either.
Also, there is a stable group of contacts, that get saved to my Google account after some time, even tough I saved them somewhere else.

**Comment by tibbi** [comment]
retest with version 5.0.0 released soon please

**Comment by Katalysator42** [comment]
Contacts still get deleted.
The contacts that get deleted are the last one I added (and the contacts are the last ones on a list when I export my contacts).
This time six contacts got deleted.

Importing contacts still doesn't work.

Version 5.0.0 from Google Play Store on Android 8.1 Oreo (no root) on the Nexus 5X

**Comment by Katalysator42** [comment]
I just noticed that another eight contacts got deleted. Again these contacts are the last ones I added (they are the last ones on a list when I export my contacts).
Version 5.0.0 from Google Play Store on Android 8.1 Oreo (no root) on the Nexus 5X

**Comment by tibbi** [comment]
recheck with 5.0.1 please, once it becomes available

**Comment by Katalysator42** [comment]
Contacts still get deleted.
I can only add that contacts get deleted without shutting down the phone.

BTW: the vcf.-file I exported via the Simple Contacts App and couldn't import in the Simple Contacts App I could import in the Google Contacts App.

**Comment by gvghia** [comment]
I have the same problem. Contacts that were entered in v4 got deleted in v5.
I wanted my contacts in a local database and not seen by other apps.
But it seems that imports from vcf and manual adds get only in the general contacts database. They can be seen there by the standard contact app, but not anymore by your app. the list is empty.
In Filter you can select the dbf (middle option) but when you retrieve filter settings the checkbox got empty.
I thought the filter option was the way to direct the adding of new items but apparently not?
I would like to see in details the dbf from where the item was retrieved. 
With 5.02 manual entry reappeared, but standard dbf stays unaccessible.
