### ISSUE TITLE
Feature request: Dialer GSM codes

### ISSUE THREAD

**Issue by JonnyTech** [SimpleMobileTools/Simple-Contacts#287]
Is it possible to handle so-called "GSM" or "secret" codes in the dialer? These are numbers such as `*#06#` for IMEI details and `*#*#4636#*#*` for MediaTek testing mode access, to name just two of many. These codes work with stock dialers.

**Comment by tibbi** [comment]
thanks, Ill take a look at it soon

**Comment by tibbi** [comment]
sadly from Android 8 or so these codes work only if the app is set as your default app for handling calls. That isnt possible yet, Ill take a look at it once Dialer is added.

**Comment by JonnyTech** [comment]
Ok, thanks, I was looking to replace my default dialler so shall keep this issue open.

**Comment by tibbi** [comment]
yeah for sure keep it open, Ill get to it after adding the dialer, maybe right together with it

**Comment by tibbi** [comment]
some support has been added for casual codes starting with *#*# and ending with #*#*, we will need it some others are needed too.
