### ISSUE TITLE
Voicemail speeddial

### ISSUE THREAD

**Issue by JonnyTech** [SimpleMobileTools/Simple-Contacts#302]
On most other dialers, including stock Android / AOSP ones, holding down key `1` calls the voicemail number.

See [official documentation](https://support.google.com/phoneapp/answer/2811844?hl=en) section "Call your voicemail"

Can this be implemented please?

**Comment by tibbi** [comment]
Speed Dialing has been added in Simple Dialer, all calling related functions will be moved there soon
