### ISSUE TITLE
Unwanted attribute merging of contacts

### ISSUE THREAD

**Issue by geniusupgrader** [SimpleMobileTools/Simple-Contacts#305]
Versions:
Simple Contacts: v 5.1.0
Nextcloud: 14.0.3
DAVDroid: 2.0.5-ose (248)

I sync my contacts from nextcloud with DAVdroid. When there are two contacts with the same name they get automatically merge in the simple-contacts app in some of their attributes (groups, photos and other things) or rather they seem to get merged, because when synced back to nextcloud everything is fine.
Example:

Contact1:

- Name: Michael
- Photo: photo1
- Groups: group1
- Notes: small

Contact2:

- Name: Michael
- Photo: photo1
- Groups: group2
- Notes: big

These two contacts (synced from nextcloud) appear as follows in simple-contacts:

Contact1:

- Name: Michael
- Photo: photo1
- Groups: **group1, group2**
- Notes: small

Contact2:

- Name: Michael
- Photo: **photo1**
- Groups: **group1, group2**
- Notes: big

**Comment by tibbi** [comment]
shouldnt be happening anymore in the latest pro version

**Comment by geniusupgrader** [comment]
I've tested it with version 6.5.1 Pro.
_Unfortunately the problem is not solved_:

When there are multiple contacts **with the same name** the contacts get „merged“ or rather shown as one contact (although the contacts differ in at least one other property). Is this not possible?

Please open this issue again. If you need any more infos, please tell me.

**Comment by tibbi** [comment]
that is currently the expected behaviour, I might recheck it in the future. It seems to work just fine and people like it.

**Comment by nunesgh** [comment]
I am experiencing the same issue here. Whenever I create a new contact with the same name of an existing contact, they are automatically merged.

This behavior is not expected, e.g. it is not the default for other services such as Google Contacts, and it happens without warning or without giving users a choice. Also, it is not clear how one can undo the merging after it is detected.
