### ISSUE TITLE
Unable to install Simple Contacts Pro

### ISSUE THREAD

**Issue by Booteille** [SimpleMobileTools/Simple-Contacts#307]
I am trying to install Simple Contacts Pro on LeEco LePro 3 AI - Android 6.0 but I cannot.
With Yalp Store I get the "This apk is split, choose root or privileged method".
With manual installation, by just running the apk I can install it but it crashes when I try to start it and the two additional apks (com.simplemobiletools.contacts.pro.36.split.config.fr.apk and com.simplemobiletools.contacts.pro.36.split.config.xxhdpi.apk) can't be installed.

I installed the apk from github as a workaround.

**Comment by tibbi** [comment]
that is a yalp issue, they dont support app bundling. The pro apps will be available on f-droid soon too.

**Comment by Booteille** [comment]
Okay! Thanks! I'll wait for fdroid builds then!
