### ISSUE TITLE
Support Import of VCF 4.0 Contacts (feature request?)

### ISSUE THREAD

**Issue by aGrimRepoMan** [SimpleMobileTools/Simple-Contacts#327]
Really enjoying this app - thanks for your work on it.

I'm using Simple Contacts Pro version v6.1.0.  When I import contacts created by the Thunderbird email client's "CardBook" add-on (https://gitlab.com/CardBook), the images (photos) of my contacts are lost.   After experimenting, I found that this happens if the contact is created according to the VCF version 4.0 specification.  If the contact uses VCF 3.0 specification instead, then the contact's photo is not lost upon import into Simple Contacts Pro.

Examining the difference between a VCF 3.0 and VCF 4.0 format contact file, I see this:
VCF version 3.0, which imports successfully:                            
              PHOTO;ENCODING=B;TYPE=JPEG:
VCF version 4.0, the (jpeg) photo is dropped upon import:      
              PHOTO:DATA:IMAGE/JPEG;BASE64,

Would it be possible for Simple Contacts to support VCF 4.0 formatted contacts in whole or in part?

Thanks for considering this.

**Comment by aGrimRepoMan** [comment]
Hmmm - have been doing further tests.  Now I'm not so sure if the problem with photos getting dropped is restricted to VCF 4.0.  I'm having trouble now where the photo is dropped upon import of a VCF 3.0 format contact too.

**Comment by immerfroehlich** [comment]
If it will stay a feature request, I have some additional requests, that are linked to this request:
1. It would be really nice, on export to decide which Vcard Version to export to. (Not all all applications can read all versions).
2. Vcard version 4.0 (RFC 6350) supports the UID property, which is a globally unique identifier. Which helps to prevent creating multiple contact entries that belong to one person/organisation. It would be really nice if this could be used and saved on the phone. This would really help when managing contacts in other applications.

**Comment by njmdietrich** [comment]
Vcard version 4.0 also supports the ANNIVERSARY property. You can already set this in the app, but upon export it is lost because it exports to Vcard 3.0.

**Comment by tibbi** [comment]
I will take a look at it. The library Im using for parsing is https://github.com/mangstadt/ez-vcard , it seems to support both 3 and 4.

**Comment by laurastephsmith** [comment]
Hi @tibbi have you had a chance to work out if you can implement VCF 4.0? I'm trying to import from ProtonMail (which only supports VCF 4.0). I get java.lang.NullPointerException: it.date must not be null. I assume that's because it's v 4.0?

**Comment by tibbi** [comment]
not yet, I dont really remember anyone else requesting it, so it isnt a high priority for now

**Comment by laurastephsmith** [comment]
No worries. I've since discovered that VCF 4.0 doesn't seem to be all that widely adopted, so I've asked Proton if they're able to support v 3.0. I don't suppose you know of any tool for converting a 4.0 file to a 3.0 file?

**Comment by FranBran** [comment]
So no plans on supporting vcard 4.0? 😢 i would love handling Anniversaries and Date of Death with Simple Contacts (and be able to export those 4.0 vcards)

**Comment by aGrimRepoMan** [comment]
Agree with FranBran.  "Cardbook" on Mozilla Thunderbird email client is popular and supports VCF 4.0.

**Comment by FranBran** [comment]
Without supporting VCF 4.0 it's also not possible to backup anniversaries (stored in simple contact's database), right?

**Comment by tibbi** [comment]
I tried importing a vcard version 4 with the new photo and birthday format, it works just fine. Are you still getting some issues? The app doesnt really care what vcard version does the file contain, it just does its best at parsing some reasonable values.

**Comment by tibbi** [comment]
actually I just upgraded it to version 4, I found nothing that would break. Let me know if there will be some issues starting with version 6.17.0
