### ISSUE TITLE
Exporting to vcf file with version 5.1.1/6.1.0 in Android 6/7 (Fairphone Open) does not work

### ISSUE THREAD

**Issue by immerfroehlich** [SimpleMobileTools/Simple-Contacts#329]
Hello Tibor,

just tried to export my locally stored contacts ("Phone Storage") to a vcf file with the "export contacts to vcf" functionality. It does not work. The applications says: "No entries for exporting have been found".

This behaviour started after I updated from version 4.5.0 to 5.1.1 through the F-Droid app store (I guess). I was using the "Fairphone Open 18.04.1" OS which is based on Android 6.0 but without the "Google Mobile Services". More information can be found here:
https://code.fairphone.com/projects/fairphone-2-official-releases.html

In the meantime I tried to update to the latest versions "Fairphone Open 18.10.0" which is based upon Android 7.1.2 and updated "Simple Contacts" to version 6.1.0 through the F-Droid store. It did not help. It is showing the same behaviour.

Do you have any idea, what this might be?

Kind regards,
Andreas

**Comment by immerfroehlich** [comment]
Arrghh, I just forgot to explain the reproduction steps, sorry:
1. Open the app
2. Click on "..." and select "Export contacts to a .vcf file"
3. Choose a folder like "/internal/backup/"
4.  Use the default settings
5. "Include contact sources" shows: "Phone storage" and "Phone storage (visible by other apps)", Select both then click "OK".
Result: The app show the following error: "No entries for exporting have been found"

**Comment by immerfroehlich** [comment]
Sharing does work with one contact, however I do not know how to select multiple contacts:
1. Click on a contact
2. Click share symbol
3. Choose "Save as..."
4. Choose a folder like "/internal/backup/"
5. Click on the download button (circle with a down arrow)

**Comment by tibbi** [comment]
there are many ways of selecting multiple items. You can just long press an item at the list view, then click additional ones. Or long press and drag. Anyway if you get a list of apps for sharing after pressing Share, it already means that it worked.

**Comment by immerfroehlich** [comment]
I don't  get it. Do you mean "Sharing" and "export contacts to vcf" is the same functionality?
In that case I must say from a usability standpoint, I wish the function would be "export ALL contacts to vcf". Having to select every contact is a time consuming and error prone process.

But maybe there is a problem in the filter:
I,
1. clicked on "..."
2. clicked "Filter"
3. then marked both of the visible entries "Phone storage" and "Phone storage (not visible by other apps) as included.
4 and pressed OK.

And what happened was, that none of the contacts where visible.
Then I deselected both of the filter entries, but it doesn't change anything.
A restart of the app doesn't do anything. Now it is more worse then ever.
I can't see any of my contacts anymore. What is this?

**Comment by tibbi** [comment]
under the hood sharing uses the same functionality as exporting, it creates the .vcf files the same way. Thats what I meant. Just reinstall the app and you will see your contacts again.

**Comment by tibbi** [comment]
if you are willing to help me debug the issue let me know at hello@simplemobiletools.com. I could send you a test version via email with some messages appearing, you would just send me screenshots of them. Im still not sure what is wrong there :/ Thanks

**Comment by immerfroehlich** [comment]
Yes OK. But I don't want to install any apts on my phone. Is it
possible to active a debug switch or something like thatand compile the
test version myself?
Oh and by the way. Happy new year!

**Comment by tibbi** [comment]
not really, you would have to reinstall it. Happy new year too.

**Comment by tibbi** [comment]
does it still happen at 6.3.1?

**Comment by tibbi** [comment]
should be fixed in 6.3.2
