### ISSUE TITLE
when add contact bug

### ISSUE THREAD

**Issue by unknowtech** [SimpleMobileTools/Simple-Contacts#333]
[![Screenshot-20181221-124454.jpg](https://i.postimg.cc/c4Gm8yzS/Screenshot-20181221-124454.jpg)](https://postimg.cc/Dm5stDFj)

**Comment by tibbi** [comment]
what app version and Android OS version do you have? Is your device rooted, or do you have any extra security related apps, settings etc?

**Comment by tibbi** [comment]
if you make the last field "Contact source" visible at the app settings -> Manage shown contact fields, what value is written there?

**Comment by tibbi** [comment]
if you go on the main screen and select Menu -> Filter, what sources do you have listed there?

**Comment by unknowtech** [comment]
![screenshot_20190105-164304_1](https://user-images.githubusercontent.com/41585567/50726135-13701080-1109-11e9-9ff8-eaaed02b08a8.jpg)

**Comment by tibbi** [comment]
Is that first item empty, or you censored it out? Do other Contacts apps work fine?

**Comment by unknowtech** [comment]
Sorry, the problem was my fault.

After looking, I had done a cleaning via adb and uninstall the necessary applications, I reset my phone, 
 
Everything is back to normal, even the recent calls have come back.

**Comment by tibbi** [comment]
so adding contacts works fine now?

**Comment by tibbi** [comment]
retry with 6.2.0 if it is still broken
