### ISSUE TITLE
Filter "phone contacts" not working / phone contacts won't show up

### ISSUE THREAD

**Issue by r0oN** [SimpleMobileTools/Simple-Contacts#344]
Since the pro version release:
when ticking only the box for filtering 'phone contacts' no contacts will appear ("no contacts found").
when checking filters again afterwards: box 'phone contacts' is not shown as ticked anymore.

strangely enough when clicking on a particular contact in my dialer app it opens all contact information in simple contacts app.
other messenger contacts do show up when filtering box is ticked.

- running android 8.0.0 and app version 6.1.2 (rolling back to earlier versions - even before pro version recreates the error)
- filtering phone contacts worked fine until pro version
- all app permissions are granted

**Comment by r0oN** [comment]
Cleared data and emptied cash.
When reopening the app for the first time afterwards (+granting permissions again) all filter boxes are ticked except for "phone contacts". Then I tick the box again -> no contacts found -> check filters again: it's unticked

**Comment by tibbi** [comment]
If you send me a mail at hello@simplemobiletools.com I can send you a test version of the app which will show a message. If you then send me a screenshot of it that might help solving it.

**Comment by foNYWZc** [comment]
Same issue happens for me.

**Comment by tibbi** [comment]
so send an email too, the more people work on it, the better :) Thanks

**Comment by tibbi** [comment]
nevermind, seems to work fine already. Reopen if it still wont work properly in version 6.2.0 released soon.

**Comment by spicfrankly** [comment]
Hi same problem here with v6.3.0 running on fresh AOSP 9 Pie, without any account added.
How to reproduce:
1. Cleared contacts storage
2. Imported from .vcf file containing multiple entries (Google account export result VCF 3.0)
3. Pressed "OK" on the dialog (title: "Import contacts", text: "Target contact source")
  note: the dialog keeps poping up and seems to repeatedly import the same file multiple time if "OK" is pressed again, unless cancelled (seems like another bug)
4. Toast "Importing..."
5. Wait a bit...
6. Toast "Import successful" (or "Import some entries failed", maybe another bug)
7. Nothing appears in the contacts list: "No contacts found"
8. Hit "Change filter", "Phone storage [...]" is ticked
9. Untick, then Press "OK": nothing appears
10. Hit "Change filter", tick "Phone storage [...]", then "OK": nothing appears
11. Go to Settings and enable "Show a dialpad button on the main screen" and "Show letters on the dialpad", then back to the main screen
12. Hit the dialpad button (centered-bottom circle button)
13. Hit the dialpad number to look for a name from the imported vcf: names show up!

Expected:
@7. Imported contacts show up in the contacts list
@9. No contact shows up from the imported contacts list
@10. same as @7

12.

**Comment by spicfrankly** [comment]
Forgot to add that the app has permissions on Contacts, Phone and Storage
