### ISSUE TITLE
no "phone" contacts anymore

### ISSUE THREAD

**Issue by michaelof** [SimpleMobileTools/Simple-Contacts#351]
Maybe related to #344

On the way to 6.2.0 the filter option for the normal "phone" contacts have been lost. Have been there before, at least before Pro apps.

Not an issue for me, personally, as I use only cardDAV/Nextcloud contacts plus a few Sim-only, but just recognized.

SimpleContacts special "phone/hidden" addressbook is shown correctly.

**Comment by tibbi** [comment]
so if you filter out every item at the Menu -> Filter, you still see some contacts? If you open them, what contact source is written at the bottom of the contact?

**Comment by michaelof** [comment]
@mp-smith:
"ensure that my contacts are available to the phone only and not other apps" is maybe NOT related to my bug here, the hidden / SimpleContacts-only option is working fine for me. This bug is about the "phone" (local) contacts which ARE visible to other apps.

@tibbi:
Your last question gave me an idea to try: As said: I've opened this issue as SimpleContacts does not offer to filter for "phone" contacts, and does not offer to create new "phone" contacts. Anymore, worked in earlier versions.

For testing I've created NOW a "phone" contact in stock contacts app. First "phone" on my device, as said Nextcloud only, usually.

And, magic:

1. New contact is visible in SimpleContacts
2. This new contact "enables" "phone" as filter option 
3. Plus, this contact enables the availability of "phone" as an option to create other new "phone" contacts, inside SimpleContacts

BUT: "enables" means only as long at least one "phone" contact exists: Deleting this contact immediately "disables" / hides the "phone" option, both for filter an new creation. 
Additionally, the magic "temporary" option is called "phone" even in my German SimpleContacts, so just the untranslated string is found and used, somehow. 
But "phone" for sure has already been translated many versions before.

**Comment by tibbi** [comment]
ye Ive changed something related to that. There was a hack which displayed "Phone" source in some scenarios, but saving there still wasnt working as it was giving some errors. I will try somehow reproducing the issue and fixing it reliably, I dont want to add the hack back. Not sure when will I be able to do that. Thanks

**Comment by mp-smith** [comment]
My goal is to keep my contacts out of all clouds and I import my master .vcf file in to Simple-Contacts periodically to stay current. 

My devices are an android tablet and phone. Both are coupled into mygmail account for calendar and tasks. The default contacts apps are coupled with the gmail acct too but sync is turned off. There are approx 5 contacts in mygmail acct. I switched to the Pro version of Simple-Contacts several months ago.

To be clear, the 3 filter choices/options I had in v5.1.2 are:
   Phone
   Phone storage
   myacct.gmail.com

The Phone option (used on phone device) lets only my phone app see the contacts. Phone storage (used on tablet device) can not be seen by the phone app. I never use the option myacct.gmail.com acct.

On v6.2.0 the Phone filter choice never appears; not for my initial .vcf import, not for adding a new contact, not when editing a contact, not when viewing contacts. The other two choices are visible and filter as expected.

@tibbi:
If I filter out all items (2), no contacts are displayed. Filtering out none or either of the two displayed works as expected.

@michaelof:
I'm not sure what the "hidden / SimpleContacts-only option" actually is. Could you please clarify it in terms of the three options mentioned above. Perhaps my assumption about the "Phone" option not being visible to other apps is mistaken? I've never seen any clarification of the distinction between "Phone" and "Phone storage". I just observed that "Phone" (when it's visible/working) is seen by the phone app.

Here's the interesting/good news. Using the stock phone app, I added a new contact and selected its "Phone" option. Magic - a new option appeared in my Simple-Contacts as a new choice - everywhere - including the phone app. The choice was listed as "vnd.sec.contact.phone". I then deleted all SC contacts (except the one added via the stock app) and imported my master .vcf specifying the "vnd.sec.contact.phone" choice. I'm back in business. Simple-Contacts is supplying the contact list for the phone app. :-)

Thanks for taking the time to explain your "magic" technique. I would not have tried that on my own. I hope my experience helps sort out why "Phone" has turned into "vnd.sec.contact.phone" for me. My new phone is an unlocked Samsung Galaxy S7 (G930U) with Android 8.0.0 (Oreo).

Thanks to everyone contributing to Simple-Contacts and Simple Mobile Tools - it's really appreciated.

**Comment by tibbi** [comment]
recheck with the latest version 6.3.0 released soon please, I managed figuring out the proper solution

**Comment by michaelof** [comment]
@tibbi:

Checked with 6.3.0. 

"Phone" as an filter etc. is back again, cool.

But, maybe a side effect, also USIMs not in use are shown since your change. As far as I understood Android iterates all SIMcards USIM[1-n]. Stock contacts app and older SimpleContacts versions offers only the (maximum 2) current SIMcard(s).
With your change, all SIMcards which ever  have been used are now shown. 

In general: Unfortunately the USIM# names are used. Would be more easy, if user-defined name from SIM settings would be used.

**Comment by tibbi** [comment]
I will take a look at it someday. It is still better to see more contacts than less :)

**Comment by michaelof** [comment]
Sure :)

But, seriously, you don't see more contacts: No way to show contacts from not available SIMcards. Only the SIMcard as an filter option is shown.

Plus, just recognized when testing for issue #330, all previously available SIMcards are offered as an option to STORE new or updated contacts, although there's also no way to store on a non available SIM.

Other side effect is, for dual sim phones like mine, that's really hard to know which of the USIM[1-n] offered ARE available, an in which slot

**Comment by tibbi** [comment]
yeah I dont have experience with dual-sim devices so I wasnt really modifying anything related to that explicitly, will take a look at it later

**Comment by tibbi** [comment]
create a new issue about it with some details please, just so I wont forget about it.
