### ISSUE TITLE
Feature Request: Standard Phone App

### ISSUE THREAD

**Issue by Phoenix1747** [SimpleMobileTools/Simple-Contacts#36]
It would be nice if one could set this app as standard "phone" app in the android settings. I don't know how hard or easy it is or if it's worth the effort but this would make it much nicer to switch like fully to this app instead of a pre-installed one.

**Comment by tibbi** [comment]
you mean call through it? This app is just for working with contacts, a standalond Phone calling app and SMS messenger will come in the future.

**Comment by Phoenix1747** [comment]
Nevermind, it's not worth explaining now and it's really not important lol, I'll just sit here and wait for the calling app (☞ﾟヮﾟ)☞

**Comment by tibbi** [comment]
I was thinking about it, but I decided I will split Contacts/Phone/SMS into standalone apps. They will come someday, not sure when ;)
