### ISSUE TITLE
Feature request: scheduled export

### ISSUE THREAD

**Issue by ajvsol** [SimpleMobileTools/Simple-Contacts#361]
I'd like to create an automated export schedule - ideally being able to set it to occur every N days at X time.

**Comment by mgohin** [comment]
Hi,

I'd like that kind of feature too, but I think it could be even better : export every time a change is made to the contact list (if this event can be catched by the app).

I'd like to sync it to my Dropbox.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Might this feature be better performed by a file-manager or recoverer/backup-manager?

**Comment by mooreye** [comment]
I'd like this feature too it would make Syncthing take care of contacts without having to remember to export a `.vcf` file or setup CardDAV.

**Comment by Fehertukor** [comment]
Hi @tibbi !

I would love this feature too with the automatic backup on changes.
Please if you have time implement it.

Thanks!

**Comment by bingoxo** [comment]
https://github.com/tmo1/sms-ie does exactly what you want , hopefully simple contacts can implement it as well with encryption and option to backup to the cloud ...

**Comment by Fehertukor** [comment]
> @bingoxo 

I checked it out and looks really good.
I think this could work and hope that @tibbi potentially can implement it.

**Comment by HarriBuh** [comment]
Any news on this feature? More and more apps of the same kind are supporting automated backups by now and this app still doesn't.

**Comment by tibbi** [comment]
it is being worked on already

**Comment by jeremiah-miller** [comment]
How do you select a different folder besides Internal/Android? I'm trying to automatically back up to my syncthing folder but it won't let me use that
