### ISSUE TITLE
Feature Request: Scrollbar displays letters not names

### ISSUE THREAD

**Issue by hockeymikey** [SimpleMobileTools/Simple-Contacts#371]
When using the scrollbar it displays names but it should display the letter of the section I'm in. This would be much quicker for people to sort through, is the default behavior in other contact apps. We can already see the list of contacts in the list, we don't need the scrollbar tooltip to remind us where we are. Could make it an option in settings too to allow people to switch between the two since maybe some like the default behavior that currently exists.

**Comment by tibbi** [comment]
it will be rewritten in the new version 6.7.0 released soon in a way that is used by many other Contacts apps. You will see letters at the scrollbar.
