### ISSUE TITLE
Not all contacts are visible 

### ISSUE THREAD

**Issue by coldsmile** [SimpleMobileTools/Simple-Contacts#376]
* **Simple Contacts:** 6.3.0 (F-Droid)
* **Android Version:** 8.1.0

If contacts, created in stock app, have only phone numbers (no name, no surname),
they are not visible in Simple Contacts.

#179

**Comment by tibbi** [comment]
arent they somewhere at the bottom? Try enabling the "Show phone numbers on the main screen" option in the app settings.

**Comment by coldsmile** [comment]
...completely absent.

Show thumbs = On
Show phone numbers = On
Try filtering out dupe = Off

**Comment by coldsmile** [comment]
...completely absent.

Show thumbs = On
Show phone numbers = On
Try filtering out dupe = Off

**Comment by tibbi** [comment]
is the contact Organization field filled?

**Comment by coldsmile** [comment]
doesn't matter

**Comment by coldsmile** [comment]
rephrase: when i clear name and surname fields from Google Contacts,
the contact disappears from Simple Contacts (even a blank line is not visible).

**Comment by tibbi** [comment]
should be fixed in 6.4.3
