### ISSUE TITLE
Groups of contacts

### ISSUE THREAD

**Issue by morfikov** [SimpleMobileTools/Simple-Contacts#38]
The default contacts app in my phone has the ability for grouping contacts. This is especially useful when you have many contacts, and you just want to make the list a little bit more clear (by selecting the appropriate group). It looks like there's no groups in Simple-Contacts (except the favorite/stared ones). Are you planning to implement this feature?

**Comment by tibbi** [comment]
ye my default Contacts app has a Groups tab too, but I dont plan adding it anytime soon, maybe in the future.

**Comment by just-Nob** [comment]
Yeah, that's something I'd like to use as well! :)

**Comment by Solarunit** [comment]
Hi! Just wanted to to propose the same feature request. B&W  theme looks very good.
I am currently using ExDialer (Dialer & Contacts). Waiting for the Simple Dialer =)

**Comment by tibbi** [comment]
Ill get there soon, I see that more people use it than I expected.

**Comment by tibbi** [comment]
will be added in 3.4.0 released soon

**Comment by marc-straube** [comment]
I can't find this feature in version 6.4.4. Has it been removed?
