### ISSUE TITLE
Custom contact names are renamed to "x-name" when vcf card is imported

### ISSUE THREAD

**Issue by joeyLaus** [SimpleMobileTools/Simple-Contacts#382]
When i imported a list of contacts via one vcf card, the custom names of the numbers are renamed to x-customname.  This is an issue because i cannot go renaming everything back to what it was now.

**Comment by tibbi** [comment]
Hey, if you open the .vcf file with a text editor, dont you see the "x-name" value there somewhere? Maybe the structure of the file is weird and Im not handling it properly.

**Comment by joeyLaus** [comment]
Hi @tibbi 
The structure is as follows:
N:;Name;;;
FN:Name
TEL;WORK:0123456789
TEL;X-Jacky:0123456789
ADR;HOME:;;123 Address Road;;;;

For some reason after importing it into simple-contacts, and after uninstalling the app, i now have some duplicate contacts.

Anyway, i hope this can help you fix the issue.

**Comment by tibbi** [comment]
well the file says "X-Jacky", so obviously it is used. Which app has created the .vcf file?

**Comment by joeyLaus** [comment]
Yes it might be used, but the "X-Jacky" is not actually displayed as "X-Jacky" in the display of the App as opposed to Simple Contacts.

Im using the Contacts App build version: 1.7.31 from LineageOS.

**Comment by tibbi** [comment]
that is the phone number type, like "Home", "Work" or so

**Comment by joeyLaus** [comment]
yes so in the display of the normal Contacts App, it is displayed as "Jacky", not "X-Jacky". But in Simple Contacts its displayed as "X-Jacky", any idea why its not handling the import correctly from the exported .vcf file?

**Comment by tibbi** [comment]
I dont see why would be the issue on my side. The .vcf file clearly says "X-Jacky" at the given field. I will try reproducing that behaviour with some other Contacts apps, to see if they remove the "X-". I dont see a reason why would they.

**Comment by joeyLaus** [comment]
@tibbi Im not sure you understand what the issue is..

yes the .vcf file obviously says `X-Jacky` however im talking about the **_DISPLAY_** of the contact inside your app, please see screenshot below.
![2019-04-10](https://user-images.githubusercontent.com/45409007/55872494-77352a00-5b8d-11e9-8c6c-ec6658dfc02c.png)

Im trying to say that the **_display_** of the contact shouldn't say `X-ContactName`, only the vcf file has this inside.
Even with your app when creating a new contact, the **_display_** of the contact is shown as `Contact` NOT `X-ContactName`
Therefore only when importing the vcf file from the normal ContactsApp to your SimpleContactsApp displays the contact as `X-ContactName` when selecting the contact.  Which means i have to go to every single contact and rename x-contact to contact since the "x-" is annoying.

**Comment by ouzowtf** [comment]
Maybe you should export the .vcf file from an other app if your current one saves the contacts with a wrong name.
How could any other app know if something is wrong with the names in the source file, know what is wrong and automagically fixes them?

**Comment by joeyLaus** [comment]
Turns out something had "corrupted" my .vcf file, but its fine now after re-editing the entries.
