### ISSUE TITLE
features request to add the feature " save the numbe throght Qr code 

### ISSUE THREAD

**Issue by nasirshah1813** [SimpleMobileTools/Simple-Contacts#387]
according to my know this is very usefull appllication for contact but I want to add some  in this application the features is save the number through QR code with this help we can save any number with all  details from anothder phone with help of QR code scanning if you like my ideas I will explain properply though image .
 how can I save number through QR code ?

**Comment by tibbi** [comment]
You cannot add it yet, but I will consider it in the future. Thanks

**Comment by nasirshah1813** [comment]
# Repository
https://github.com/SimpleMobileTools/Simple-Contacts
 
# Introduction

according to my knowledge, this is a very useful application for all types of contact with the help of this application you can synchronize via Google or other accounts. there are many features in this application like managing your email contact number save the number with picture details business or other information.

# Components

The components (Features) I want to suggest is

This feature must be in this application and This feature will increase the utility of application.

1-   Save Number through QR Code
2- Save all number Through QR code

# Proposal Description

according to my knowledge, this is a very useful application for contact but I want to add some feature in this application the features is:

##  save the number through QR code.

according to my information, you can also know about the  QR code .  this is the fastest way to transfer information there are many developers who use this feature. The Quick Response system became popular outside the automotive industry due to its fast readability


this feature very helps fully for this application the user can save any number with the help of this application.  when the user clicks on the QR code icon after open this option when users scan the QR code of any number and all the information and number will be saved automatically in the phone within a second.

# Save all number Through QR code 

Sometimes users change their mobile phones. there are many number save in  phone memory  and he wants to save all the number into the new mobile  phone   But it does not have time to copy the number and with the help of this feature he can save all the number Through QR code  scan option 




# Mockups / Examples


![1.png](https://ipfs.busy.org/ipfs/QmZCt47iazgvF2wDcn6mBb1wHop2jzTTxQdH57txbUHPE4)
![2.png](https://ipfs.busy.org/ipfs/QmWxwDx6whrBiv92oH7wS5UxSkHUFaJMAw3Ztz1KSmFqWE)

![3.png](https://ipfs.busy.org/ipfs/QmdbpiKzr7dP6qEKXQZ9YXaDkfbPyEAmrg2mn9uXhq41CL)

# Benefits
this is the fastest way to save the 1 number or all the contact numbers. the maximum time will be saved with the help of this application.  User will get amazing feature the application user can reduce their mistake to save the Password 

# GitHub Account
https://github.com/nasirshah1813
