### ISSUE TITLE
How it refresh the contact when a new contact is added or existing updated or deleted in native app? 

### ISSUE THREAD

**Issue by alphaguy4** [SimpleMobileTools/Simple-Contacts#396]
I looks like when i open the app it refresh the whole contact list. When it is in background and i add a contact in the native app, this app detect it when it comes foreground i can see the new contact in the list. I think the whole contact is not refreshed into that case.

Do you refresh the whole contact or do you just get the diff for new/update/delete

**Comment by tibbi** [comment]
Im reading all info directly from the phones internal contact storage, I dont copy it in any own database. It might be added later to improve the performance, we will see.

**Comment by alphaguy4** [comment]
So every time app comes to foreground it re queries the contact storage ? Don't you think this will have performance issue when contacts are more 1000 in the native contact

**Comment by tibbi** [comment]
ye, thats how it works currently. It works just fine in 99% of cases, most people have max a couple hundread contacts. In some extreme cases it can be slow, Ill see how could it be improved in the future.
