### ISSUE TITLE
Import/Export contacts

### ISSUE THREAD

**Issue by buckelieg** [SimpleMobileTools/Simple-Contacts#4]
Import/export functionality like a standard app (in Android 7.x)

**Comment by Phoenix1747** [comment]
Definitely needed! 👍

**Comment by TeeTeeHaa** [comment]
I recently found Simple Contacts and am really excited about it because it exactly is what I was looking for: Simple, open source, and (most importantly) not trying to send my data somewhere. So first of all: thank you for creating it!

The only feature I am currently missing is an import/export to/from a .vcf file, preferably in a format understood by Mozilla Thunderbird. Would be awesome if such a feature would be implemented.

**Comment by tibbi** [comment]
it will be added, Im just postponing it because Im afraid that it will end up like the calendar ICS files, when there are some rough standards, but every app/web does it a bit differently and it is a mess...

**Comment by tibbi** [comment]
oh yeah, just as I thought. Exporting through the Google Contacts android app and the Google contacts web produces different vcf files \o/

**Comment by tibbi** [comment]
will be added in 3.1.0 released now

**Comment by TeeTeeHaa** [comment]
:astonished: Whoa, that was fast, thank you, I really appreciate your efforts.

I made some quick tests with Mozilla Thunderbird 52.5.2 (32-bit) on Windows 7 (64-bit) US:

Export from Simple-Contacts and import to Thunderbird worked, at least for first name, surname and mobile phone number, but the photo did not appear in Thunderbird.

Export from Thunderbird and import to Simple-Contacts did not work. The following file causes a failure during import:

    begin:vcard
    n:Firstname;Surname
    tel;cell:+49 123 4567890
    version:2.1
    end:vcard

There are two things it does not like: Lowercase key words and missing trailing semicolons in the name line. The following, manually modified can be imported in Simple-Contacts:

    BEGIN:VCARD
    N:Firstname;Surname;;;
    TEL;CELL:+49 123 4567890
    VERSION:2.1
    END:VCARD

It is your decision whether Mozilla Thunderbird is a supported "target" for the import/export of Simple-Contacts.

**Comment by tibbi** [comment]
yeah, thats exactly what I meant :/ There are some standard which nobody cares about at https://en.wikipedia.org/wiki/VCard#Properties . Ill fix it, doing incasesensitive checks is easy to add.

**Comment by TeeTeeHaa** [comment]
Using version 3.1.2 from Google Play Store importing the two files mentioned above does seem to work. The first two imports said "successful", but the new contacts did not show up afterwards. They did show up in the stock Android messages app. I then stopped and restarted Simple Contacts which made the contacts show up there, too. After deleting them and importing the first file again, the contact showed up immediately afterwards.

Nevertheless thanks for fixing this so fast.

**Comment by tibbi** [comment]
Ok not sure what caused the delay, but whatever :) Enjoy
