### ISSUE TITLE
Wrong Translation [German]

### ISSUE THREAD

**Issue by moritz31** [SimpleMobileTools/Simple-Contacts#40]
In the App under settings their is a toggle which says in german "Namen mit Vornamen beginnen", but when i enable this, the names start with the "Nachname" default is that it starts with "Vorname".

**Comment by tibbi** [comment]
cc @Phoenix1747

**Comment by Phoenix1747** [comment]
Oops, I confused surname with `Vorname`. Fixed in PR #41!

**Comment by tibbi** [comment]
alright, thanks
