### ISSUE TITLE
[Bug] Filter is ignored by Starred Contacts & Groups Tabs

### ISSUE THREAD

**Issue by Zorks** [SimpleMobileTools/Simple-Contacts#404]
All starred contacts show up in Favorites tab, regardless of filter status. Same with groups (assuming group only contains filtered contacts), though that may be unavoidable if groups can be cross-list.

This feels like a bug, but theoretically I could see this as intended behavior (ie: wanting starred contacts of hidden lists to still show). If the latter, maybe make a toggle for favorites/groups to follow the filter list?

**Comment by tibbi** [comment]
ye it is the intended behaviour, Ill see if it gets changed in any way in the future

**Comment by Zorks** [comment]
Makes sense in hindsight but I was definitely befuddled at first as to why those tabs were showing duped entries. Appreciate the app and the quick response!
