### ISSUE TITLE
Take back the Recents tab in f-droid and github builds , please!

### ISSUE THREAD

**Issue by DI555** [SimpleMobileTools/Simple-Contacts#408]
Please take back the Recents tab with all history in f-droid and github builds!
Let only GP builds be without that future.

**Comment by tibbi** [comment]
I dont want to build any custom app versions

**Comment by DI555** [comment]
So, you let bigG rules you ;( ???
It's a pity(. Better would be to delete the app from gp, and keep f-droid and github one.

**Comment by DI555** [comment]
But it's a good practice to have poor one version in gp store, but feature rich one in own repo.

**Comment by DI555** [comment]
Without new features and good stuff the app is useless(((.

**Comment by DI555** [comment]
Why not just to rename 'Recents' to 'History' ???

**Comment by tibbi** [comment]
it doesnt matter how it's called.. The issue is that I dont have access to the call logs.

**Comment by DI555** [comment]
It's sad(. And if with asking access permition?
But anyway if just build gp's one with cut off code of 'Recents'? So let be 'Recents' code as module, and build google one without it?

**Comment by tibbi** [comment]
I dont want to go around the Google rules, that could get me banned.

**Comment by DI555** [comment]
No reason to ban, I saw many apps that provide more reach version on github and/or f-droid repo ...
But as I remember,  could it be possible to ask a permition to access call log...?

**Comment by tibbi** [comment]
I asked for it, it was declined. Anyway, im done with this thread, just use a different app if you want.

**Comment by DI555** [comment]
But, why not to drop the app in gp and update it only sometime and without 'recents'(just to be live in gp),
but support the feature rich app in other stores...?
Imo will not be any ban in gp...
 I wrote it because I like the app and want to see it's progress!

**Comment by DI555** [comment]
@tibbi , please, you planned to ask another try for use recents/history! i hope it must be success!

**Comment by tibbi** [comment]
ye I just added a dialer in the latest version so once it works well I will request the permission again
