### ISSUE TITLE
SimpleContacts as ContactsProvider replacement

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-Contacts#411]
Hi guys, i want to delete my Contacts and ContactsProvider from my Spreadtrum phone, and still able to read my contacts inside my Dialer and other apps, but in this Spreadtrum phone the ContactsProvider force close if delete Contacts, i see how SimpleContacts sync with other trusted services without Google malware jaja, but i really want to go totally offline with my stuff so, thanks a lot for your time

**Comment by tibbi** [comment]
this isnt planned
