### ISSUE TITLE
Contacts synchronization, 'other methods'?

### ISSUE THREAD

**Issue by tomjennings** [SimpleMobileTools/Simple-Contacts#412]
first, thanks 1E6 for the great code. 

i'm using Simple Contacts to keep contact info out of Google Contacts (phone-local storage). of course this introduces at minimum a backup requirement. my questions are about non-google backup, and secondarily, non-google synchronization.

the contacts data/database seems to be at com.simplemobiletools.contacts. 

the app description for Simple Contacts states in the 2nd sentence: "The contacts can be stored on your device only, but also synchronized via Google, or other accounts." what does 'other accounts' refer to here?

what methods might there be to minimally save, backup, transport, synchronize this database, other than manual copy to USB storage, etc?

**Comment by tibbi** [comment]
'other accounts' means assigning the contacts to your email address, which is basically the default way all contacts apps work. That way google will upload your contacts to the cloud and you can see the same contacts on every device and https://contacts.google.com/

**Comment by tomjennings** [comment]
> 'other accounts' means assigning the contacts to your email address, which is basically the default way all contacts apps work. That way google will upload your contacts to the cloud and you can see the same contacts on every device and https://contacts.google.com/ <https://contacts.google.com/>
Ahh, thank you. What I’m trying to do is probably not reasonable, which is to restrict Google et al to the minimum data necessary to use the phone (phone number, physical address), and not have email/username/etc or any other personal “contact” data in the Contacts database.

It’s generally unquestioned that physical/electronic data would be stored together — a closer look at usage found that the set of people I email only slightly overlaps the set of people I call or see physically, at very little increased effort on my part.  That coupled data makes personal security much poorer for me and everyone in Contacts. A small step in slowing the pernicious cross-referencing of our collective Contact data.

I appreciate you answering my post so quickly. The Simple apps are great, well done, consistent, and clean. Thank you!

**Comment by tibbi** [comment]
well ye, saving contacts to "Phone storage (not visible by other apps)" stores them in a whole separate database, so there is just no way any app can access them. It might be good for your privacy, but it definitely has drawbacks. One of them is not seeing the callers name, if he is stored in that area. Or you might also lose all your contacts if you uninstall the app, or clear its data. Sometimes data is cleared also at big system updates.
