### ISSUE TITLE
Import Contacts fails when Android Permission: Contacts denied

### ISSUE THREAD

**Issue by tomjennings** [SimpleMobileTools/Simple-Contacts#413]

**Comment by tomjennings** [comment]
i want to use Simple Contacts with local storage only (see other issue re: sync, backup) and deny system access to contact data. i manually create a test entry OK, but import fails. 

with system contact permission denied, import fails. i expected import to populate the local storage.

import seems to work only on the system contacts data. is this correct?

if i allow contact permission, i see the logical "OR" of my manual test data, and the contents of android contacts.

**Comment by tibbi** [comment]
what app version do you have?

**Comment by tomjennings** [comment]
v6.3.2

**Comment by tibbi** [comment]
recheck with 6.3.5 if it is still broken
