### ISSUE TITLE
cannot add contacts with out account on device

### ISSUE THREAD

**Issue by nutpantz** [SimpleMobileTools/Simple-Contacts#42]
Without a account on the device I can not create contacts with simple contacts
There seems to be no option for device only contacts.
Simple contacts would not pass email address to k9 mail from contacts stored in essential pim pro served account.

**Comment by tibbi** [comment]
what items do you see after pressing Filter? Most devices have some local storage too, me included. What Contacts app are you using now? Do you see some storage like "Phone storage" or so there?

**Comment by nutpantz** [comment]
Vnd.sec.contract.phone.

I can see contacts created in the oem contacts app . See all the info and use simple contacts to phone or start a email.
But I can't create a new contact or get  a email address from within k9mail choosing simple contacts as the app to get the email address from.

**Comment by nutpantz** [comment]
When trying to create a new contact
Some java error flashes as a toast(that I can't read fast enough) then there is a unknown error toast

**Comment by nutpantz** [comment]
Got a screen shot of the error

**Comment by nutpantz** [comment]
an error occurred:
java.lang.illegalargumentexception:must specify both or neither of account_name and account_type uri:content://com.android.contacts/raw_contacts ,calling user: com.simplemobiletools.contacts, calling pahage.com.simplemobiletools.contacts


Had to type it out, seems I can't attach pictures

**Comment by tibbi** [comment]
So you see the already created contacts in Simple Contacts? If you open one to edit it, what is written at the bottom, where some account name should be?

**Comment by nutpantz** [comment]
Vnd.sec.contract.phone.
If I create a contact with the oem contacts app
Or 
Essentialpim
(essential pim pro is a app that encrypts it's own contacts database and uses an account to exchange the information to the rest of the system,(until someone creates a open source app that does the same thing)) I would prefer to use essential pim pro to host the contacts and simple contacts to pick people

**Comment by nutpantz** [comment]
I had disabled essential pim to see if the error was because of it but I get the error with essential pim disabled.

**Comment by tibbi** [comment]
Can you try this version? Just download the file on your device, remove the ".zip" extension so the filename is "contacts-release.apk", allow installing apps from unknown sources in the security settings of your device and run the file, it should update properly. Is the error still there? Thanks
[contacts-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Contacts/files/1674643/contacts-release.apk.zip)

**Comment by tibbi** [comment]
okay Ive published 3.1.3 to playstore, get it from there or from f-droid whenever it gets available. Let me know if you find more issues. Thanks
