### ISSUE TITLE
Importing/exporting contacts does not work

### ISSUE THREAD

**Issue by Reue** [SimpleMobileTools/Simple-Contacts#420]
Android: V. 9.0
Contacts: V. 6.3.3

On all recent "Simple Contacts" versions the "export/import contacts" function does not work.

You have a smarphone with all contacts saved as "vnd.sec.contact.phone". This is important for various reasons, one of them is being able to see the contacts name when you receive a phone call. In fact, when you save a contact as "Phone storage (not visible by other apps)" then when you receive a call from that contact you will only see the phone number, and not any information (like person's name) associated to that contact. On the other hand, in case you later decide to use another contacts application, and want to transfer the contacts to the new application, it is preferable to use "vnd.sec.contact.phone" from the beginning to avoid even more problems than "Simple Contacts" is already having.
Currently "vnd.sec.contact.phone" is the default value for most Android phones, and corresponds to the following file: /data/data/com.android.providers.contacts/databases/contacts2.db

Well, then you export the contacts do a "vcf" file (either via "Export contacts to a .vcf file" or via selecting all contacts -> share -> Save as).
You transfer the ".vcf" file to another smarphone. There you open "Simple Contacts", select "Import contacts from a .vcf file", select the file (at this moment the option "vnd.sec.contacts.phone" appears by default but you can't select it), press "OK", and no contacts are imported (and you receive a message saying that "an error has occurred"). If, instead, you do this: Open "Simple Contacts", select "Import contacts from a .vcf file", select the file, then press "vnd.sec.contact.phone", then select "Phone storage (not visible by other apps)", then press "OK", - then all the contacts are imported but they all appear under the value "Phone storage (not visible by other apps)", wich means you will have the problems mentioned above and the contacts will be saved not in "/data/data/com.android.providers.contacts/databases/contacts2.db" but in "/data/data/com.simplemobiletools.contacts.pro/databases/local_contacts.db" ! Even worse than this: after that, "Simple Contacts" does not allow you to change, on any contact you have, the "Phone storage (not visible by other apps)" value to "vnd.sec.contact.phone" value (or any other value). As a matter of fact, if you are using Android 9.0 and any recent "Simple Contacts" version, and you simple want to create new contacts (without importing anything), you will only have the option to create contacts under the "Phone storage (not visible by other apps)" value! So the contacts will allways be saved (only) in the folder "data/com.simplemobiletools.contacts.pro/databases/", with all the problems and restrictions mentioned above.

Well, you would think you could solve these problems by simply making a backup, as follows:
- You root the smartphone where you have all your contacts saved in "/data/data/com.android.providers.contacts/databases/contacts2.db"
- Then, using "adb", you copy that file to a PC.
- You root the "destiny smartphone".
- You copy "contacts2.db" from PC to the smartphone folder "/data/com.android.providers.contacts/databases/".
- You install latest "Simple Contacts" version and open it.
Them you will see all the contacts, with all the fiels perfectly filled! And all the contacts will be shown as "vnd.sec.contacts.phone"! Perfect! Problem solved, right?

Wrong... Why? Because next time you reboot your smarphone "Simple Contacts" will simply delete the file "/data/data/com.android.providers.contacts/databases/contacts2.db" !!! And so, when you open again the "Simple Contacts" app the contacts are all gone, forever... You would need to copy "contacts2.db" from computer to smartphone (via adb) whenever you reboot your phone!

This is a weird and illegitimate behavior... These are very strange bugs that need to be fixed quickly.

**Comment by MisterMoeller** [comment]
Has there been any progress on this or did someone find a workaround? I am having the same issue and it's really annoying to not see who is calling me. Is there gonna be a fix anytime soon?

**Comment by tibbi** [comment]
No workaround for this. If you save a contact under the "Phone storage (not visible by other apps)", you obviously cannot see who is calling you... The dialer app has no access to those contacts, it should be quite obvious.

**Comment by QaldeK** [comment]
This bug is a big one, the application has much less interest... Any project to solve this ?

**Comment by tibbi** [comment]
should be solved already. If not, make a shorter report please to the point
