### ISSUE TITLE
existing data in TITLE: and ORG: are not shown

### ISSUE THREAD

**Issue by Buntbart** [SimpleMobileTools/Simple-Contacts#422]
Thank you for SMT!

I'm using v.6.3.3 from F-Droid on a Samsung Galaxy S5 running LineageOS 16 (Android 9). Also I'm using Nextcloud DAVx5 for synchronization.

The data behind TITLE: and ORG: are in the *.vcf-file and they will even be exported from Simple Contacts but they are not shown and can't be edited in Simple Contacts.

Example:

BEGIN:VCARD
VERSION:2.1
N:Doe;John;;Prof. Dr.;
FN:Prof. Dr. John Doe
TEL;WORK:+491234567890
EMAIL;WORK:j.doe@example.com
ORG:Example Company
TITLE:CEO
URL:http://www.example.com
END:VCARD

Please find a way to show these data when a contact is opened and make them editable.

Besides, I also can't edit academic titles like in the "Prof. Dr." example.

Thank You!

**Comment by tibbi** [comment]
some fields are hidden by default, try just enabling it in the app settings.

**Comment by Buntbart** [comment]
How blind can one be...
Sorry!
