### ISSUE TITLE
Integrate phone/call replacement feature to replace default Android phone app

### ISSUE THREAD

**Issue by antomate** [SimpleMobileTools/Simple-Contacts#436]
Currently the Simple Contacts app can replace the Contact and Dialer functionalities, but it would be awsome to integrate basic phone functionalities (call, receive call, display call log...) because currently we still need to use the default Google Phone app, even when using the dialer of Simple Contacts and for privacy aware people, that is not very good.

I found some basic Phone app on GitHub and it seems not too much code for basic functionalities.
https://github.com/mbarrben/android_dialer_replacement
https://medium.com/@mbarrben

(By the way, big fan of your apps in general, I'm using 4 of them in PRO versions)

**Comment by tibbi** [comment]
call log used to be there, but it had to be removed due to Googles latest permissions policy. Ill have to create some dialer in the further future, so Im closing this one. No sense adding a dialer in the app if I cannot show a call log.

**Comment by antomate** [comment]
I understand for the call log, but when you say "I'll have to create some dialer in the future", so you will at some point add this right ?

**Comment by tibbi** [comment]
well it is on the roadmap for quite some time now, we will see. I definitely cannot promise any date.
