### ISSUE TITLE
Contact with no name filled in not shown

### ISSUE THREAD

**Issue by JohnVeness** [SimpleMobileTools/Simple-Contacts#444]
If I create a contact in a different contacts app with just Organisation and a phone number filled in (no first name/surname), the contact won't show up in Simple Contacts.

V 6.3.5 from F-Droid

**Comment by tibbi** [comment]
retry with 6.4.1, once it becomes available

**Comment by JohnVeness** [comment]
Thanks. Same issue in 6.4.1 I'm afraid

**Comment by JohnVeness** [comment]
Sorry, this is a dupe of #376

**Comment by tibbi** [comment]
should be fixed in 6.4.3
