### ISSUE TITLE
Option to Open in Favourites Tab

### ISSUE THREAD

**Issue by Russe** [SimpleMobileTools/Simple-Contacts#450]
Great App, thanks for your work.
Is there any way to add an option for displaying a standard tab when opening the app?
I would like to open the app with favourites tab.

**Comment by tibbi** [comment]
the tab which is open at closing the app is open by default on the next run, I dont really want to add a setting for that

**Comment by Russe** [comment]
This does not work for me, Simple Contacts opens always with the first tab (Contacts) and not with Favourites tab.
I'm using the current F-Droid version on LineageOS.

**Comment by tibbi** [comment]
make sure you exit the app with the back button, Home just pauses it
