### ISSUE TITLE
Contact group "disappear"

### ISSUE THREAD

**Issue by michaelof** [SimpleMobileTools/Simple-Contacts#456]
6.4.2 / F-Droid

Steps to reproduce:
- start app, all fine
- tap on groups
- tap on any ex. group
- all contacts for group are shown
- tap go back
- all contacts groups are "gone"

Restarting app "brings back" all groups :)

**Comment by tibbi** [comment]
it has already been fixed in 6.4.4, I guess it will arrive on f-droid soon
