### ISSUE TITLE
Show letters on the Dialpad should be the default

### ISSUE THREAD

**Issue by uncertainquark** [SimpleMobileTools/Simple-Contacts#458]
Showing the letters on the Dialpad doesn't clutter the UI at all. Plus, it allows people to use T9 search when dialing a number, which the app has! The setting availability that turns it on is unnecessary and therefore should be removed, and the letter just shown by default.

![photo_2019-11-08_16-53-04](https://user-images.githubusercontent.com/22585732/68473173-3f3bb580-0248-11ea-97e8-8d54011050a8.jpg)

**Comment by tibbi** [comment]
it will be the default one starting 6.5.0
