### ISSUE TITLE
IllegalStateException: accountName must not be null

### ISSUE THREAD

**Issue by k3b** [SimpleMobileTools/Simple-Contacts#46]
On my android-7.1 phone the app does not show any contact data except the error message

* IllegalStateException: accountName must not be null

I am using v 3.1.1 downloaded from izzy-soft fdroid repository

**Comment by tibbi** [comment]
You see this right after launching? If you reinstall the app you see it right after first launch? Im going to release 3.1.2 right now, I will allow empty account name. It might misbehave at editing/adding new contacts, let me know how will it work or what contact sources do you see. If you dont have any google email or so, you should still see "Phone Storage" or some equivalent of it. Thanks

**Comment by k3b** [comment]
yes it is show at start up and i currently have no mail on the phone. I will let you know what happens in 3.1.2 once it is available in fdroid or izzysoft repository

**Comment by k3b** [comment]
i have now installed 3.1.2 the error message is gone and the app shows that there is no data although there are more than 50 contacts on the phone

**Comment by umbibonci** [comment]
Yes, I am getting the same error message. It says: An error occurred: java.lang.IllegalStateException: accountName must not be null. I am on 7.1.1 .

**Comment by tibbi** [comment]
Can any of you try this version? Just download the file on your device, remove the ".zip" extension so the filename is "contacts-release.apk", allow installing apps from unknown sources in the security settings of your device and run the file, it should update properly. Is the error still there? Thanks
[contacts-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Contacts/files/1674641/contacts-release.apk.zip)

**Comment by k3b** [comment]
this pre-release works on my android-7.1 :-)

**Comment by tibbi** [comment]
can you also insert/edit contacts properly? Any issues anywhere?

**Comment by umbibonci** [comment]
Tibbi, I did not mention I still have version 3.1.1; does this change anything?

**Comment by tibbi** [comment]
ye i changed some things lately so 3.1.2 might have some improvements related to it. The version which I just attached is 3.1.3, that will hopefully work fine.

**Comment by umbibonci** [comment]
OK, thank you. I downloaded it from F-Droid and I wanted to stick to it. On F-Droid it's still 3.1.1. You think I should update it to 3.1.3 anyway?

**Comment by tibbi** [comment]
Well you would have to reinstall the app after testing. That would just reset the settings, you wouldnt lose anything else. Im going to publish 3.1.3 now so it might get available on f-droid within a couple days, you can wait for it if you want.

**Comment by umbibonci** [comment]
Thank you. You know I already have Galley, File Manager, Contacts, Camera and Calendar. I am looking forward to install a Dialer from you…

**Comment by umbibonci** [comment]
Your work is great.

**Comment by k3b** [comment]
* delete works.
* edit/insert-new gives error "bitte wählen sie einen account aus, zu dem der kontakt gehört" (please select account where the contact belongs to)

**Comment by k3b** [comment]
Edit and add photo works; in edit you can add to favorites so it is visible in the favorites list

**Comment by tibbi** [comment]
okay Ive published 3.1.3 to playstore, get it from there or from f-droid whenever it gets available. Let me know if you find more issues. Thanks
