### ISSUE TITLE
Cannot add new contact from K9

### ISSUE THREAD

**Issue by trev-dev** [SimpleMobileTools/Simple-Contacts#464]
In K-9 Mail you can add a contact that's not already in your address book by touching the contact's name/image placeholder. However when using Simple Contacts, this process fails and you get a popup that states "No suitable application for this action found"

It's weird because K-9 is able to pull information from _existing_ contacts, it's just the ones that don't exist that fail to start the process of adding a new one with Simple Contacts.

I raised this issue with them first here: https://github.com/k9mail/k-9/issues/4244 - we seem to feel like there actually may be a problem with Simple Contacts as opposed to K-9.

If there's anything more I can do to help, let me know.
Software being used:
Android 8.1.0
Simple Contacts 6.4.4 Pro
K-9 Mail 5.600

**Comment by tibbi** [comment]
what Simple Contacts app version are you using?

**Comment by trev-dev** [comment]
@tibbi 6.4.4 Pro
