### ISSUE TITLE
Feature Request: Contact activity

### ISSUE THREAD

**Issue by igoro00pl** [SimpleMobileTools/Simple-Contacts#47]
When you click on the contact, app will open activity to edit. I think, activity with non-editable contact data, and button to edit will be better.

**Comment by tibbi** [comment]
ye I was thinking about it too, will be added

**Comment by igoro00pl** [comment]
Thanks.

BTW: I made Polish translation, but I'm new on Github, and I don't how to upload it to you. Can you help me?

**Comment by trubitsyn** [comment]
@igoro00pl please read https://github.com/SimpleMobileTools/General-Discussion/blob/master/README.md#how-can-i-suggest-an-edit-to-a-file

**Comment by tibbi** [comment]
an option to select what action should happen on contact click will be added in 3.2.0. You can either call the contact, view it or edit it.
