### ISSUE TITLE
Phone numbers not displayed

### ISSUE THREAD

**Issue by mafanie** [SimpleMobileTools/Simple-Contacts#471]
Having an valid vCard v3 vcf file with several phone number some of them are not displayed. Please see the vcard file above habing defined three phone numbers and the screenshot of the app showing that only one phone number is displayed.

Example file:
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Thunderbird.net/NONSGML Thunderbird CardBook V43.0//EN-US
UID:a952fb64-ce41-45c0-bea7-a17848eecb32
FN:Mustermann Max (Test)
N:Max;Mustermann
ORG:Test
EMAIL;TYPE=WORK:a@test.de
EMAIL;TYPE=WORK:b@test.de
EMAIL;TYPE=HOME:c@test.de
EMAIL;TYPE=PREF,HOME:d@test.de
TEL;TYPE=PREF,CELL:+49 172 12345678
TEL;TYPE=CELL:+49 171 12345678
TEL;TYPE=MAIN:+49 170 12345678
REV:2019-11-27T03:22:13Z
END:VCARD`
```

Screenshot:
![Screenshot_20191127-034541](https://user-images.githubusercontent.com/19827673/69689067-39f3bd00-10c8-11ea-817b-a37cd38c6f61.jpg)

**Comment by mafanie** [comment]
Is there already some idea about a resolution of this issue? Missing some telephone number or not being sure if all telephone numbers are showns makes using the app a little inconvenient.

**Comment by tibbi** [comment]
I use a system function which compares the phone numbers, it checks only the last 7 digits. Changing it will need more work, not sure when will I get there. Casual phone numbers are checked properly, this is an extra edge case.

**Comment by mafanie** [comment]
That the telephone numbers are nearly identical was only because I didn't want to use some real data for this bug report. In fact I had some problem with the display of telephone numbers with real data, but I was not able to reproduce the problem now. Maybe it is meanwhile solved by another change. Otherwise I will reopen this bug as soon as I encounter the problem again.
Thanks for your efforts.
