### ISSUE TITLE
Q: grant access to contact on device storage 

### ISSUE THREAD

**Issue by stefanschauer** [SimpleMobileTools/Simple-Contacts#472]
Apps on my phone have problems accessing contacts that are stored on the device. How can I grant those app access to the contacts? 
e.g. signal can not resolve the names of the contact via the phone numbers. All the tricks mentioned on the signal forum did not work and I granted signal access via android settings. Is there something that I missed?

**Comment by tibbi** [comment]
what contact source are the contacts stored on (I mean the last field at creating a new contact). Are you maybe using "Phone storage (not visible by other apps)"?

**Comment by stefanschauer** [comment]
yes that's what I use - is there a way to create an extra storage that can be accessed by other apps?

**Comment by tibbi** [comment]
well, its goal is having contacts be invisible to other apps. You can just use any other contact source to make them public. You cannot cherry-pick which app sees which contacts.
