### ISSUE TITLE
Allow export of contacts using Share intent

### ISSUE THREAD

**Issue by Friptick** [SimpleMobileTools/Simple-Contacts#474]
Feature request. Make it possible to export contacts via the Share API.

This would be really useful for exporting backups to cloud storage. At present it is necessary to export the .vcf file to local storage, then upload or share it from there.

Thanks for your consideration, and for your work.

**Comment by tibbi** [comment]
if you select multiple contacts and use Share, it already shares them bundled in a .vcf file

**Comment by Friptick** [comment]
Great. Thanks for the tip.
