### ISSUE TITLE
contact photos don't display

### ISSUE THREAD

**Issue by pdgilbert** [SimpleMobileTools/Simple-Contacts#475]
(v 6.4.4 Pro ) I can edit a contact and select a photo, and it displays in the edit contact screen, but it disappears when I return to the details screen and the contacts screen. Also, photos imported in a .vcf file do not display. I've tried this on a Google Pixel 2 and a Huawei P Smart.

**Comment by tibbi** [comment]
are you storing the contacts under "Phone storage (not visible by other apps)", or some other source? I mean the last field at creating a new contact

**Comment by pdgilbert** [comment]
Yes, I'm storing under "Phone storage (not visible by other apps)"

**Comment by pdgilbert** [comment]
(clicked the wrong button, didn't intend to close.)

**Comment by tibbi** [comment]
should be solved already
