### ISSUE TITLE
Improve birthday input of a contact

### ISSUE THREAD

**Issue by FestplattenSchnitzel** [SimpleMobileTools/Simple-Contacts#479]
Improve adding a birthday to a contact at "Edit Contact". At the moment it is hard to add a 19xx-birthday, because you have to click on the "go back in time"-button very often (and only one month is skipped by one click).

**Comment by tibbi** [comment]
Im using the system date picker, you usually just have to click on the year to be able to select it easier.

**Comment by duesseldorferjung** [comment]
I was just about to open a request as well.
