### ISSUE TITLE
Pressing Back after viewing contact details from a search should return to the search results

### ISSUE THREAD

**Issue by JohnVeness** [SimpleMobileTools/Simple-Contacts#483]
At the moment, if I do a search, click on one of the results, realise it's the wrong contact and click back, I am returned to the full list of contacts and have to do the search again. This is annoying, especially as there is no search history.

Would it be possible to change it to return to the search results in this situation?

**Comment by contrapunctus-1** [comment]
A related request - when searching -> selecting contact(s) from search results -> pressing Back, exit search without losing the selection.

**Comment by contrapunctus-1** [comment]
Thank you very much, @tibbi 😀
