### ISSUE TITLE
Bug with opening phone number from OsmAnd

### ISSUE THREAD

**Issue by contrapunctus-1** [SimpleMobileTools/Simple-Contacts#488]
1. From a POI in OsmAnd (v3.5.5), tap the phone number
2. Open it with Simple Dialer (v6.5.1)

With the Google Phone app, this opens the dialer with the selected phone number filled in.

With Simple Dialer, the phone number field is empty.

**Comment by tibbi** [comment]
Simple Contacts has no dialer anymore, report it at Simple Dialer if still valid

**Comment by contrapunctus-1** [comment]
Seems to be fixed. Thanks!
