### ISSUE TITLE
Cannot add new contacts on factory reset phone without first adding one contact with Google Contacts

### ISSUE THREAD

**Issue by alcoolfire** [SimpleMobileTools/Simple-Contacts#491]
I bought a new Android 10 phone and disabled Google Contacts app without ever using it even once. I installed Simple Contacts from F-Droid and tried to manually add my first contact. I was provided no option at the bottom of the contact edit screen to associate the contact with either my Google account or phone storage, yet I was permitted to save the contact. However, the newly added contact was not shown anywhere. Only later did I discover that the new contact was saved in phone storage.

Similarly, I was not provided an option to associate an imported VCF file with my Google account either. There seemed to be no way to get Simple Contacts to initialize the contacts database associated with my Google account.

The workaround was to re-enable the Google Contacts app, use it to manually add a temporary contact, launch Simple Contacts so that it would actually see the new contact, and only then could I disable the Google Contacts app again (and delete the temporary contact).

Obviously Simple Contacts should not require Google Contacts as a dependency, even if only temporarily.

Simple Contacts v6.5.1
Google Pixel 3a
Android 10

**Comment by Niklas81** [comment]
Similar thing on a brand new Android 9 phone, Android One model. In my case, contacts are saved so that they can be accessed through the main contacts app (when saving in Simple Contacts), they cannot be seen in Simple Contacts; however uninstalling Simple Contacts, adding a contact in the main app and then re-installing Simple Contacts has no effect for me.

**Comment by boner-cmd** [comment]
Android 9, brand new Moto g7 Power. Could not see contacts through app when starting with zero Google contacts. Contacts I added through the app weirdly could be seen through Google contacts, but not the app. Uninstalling the app, adding a contact to my empty Google contacts, then reinstalling the app worked for me.

**Comment by ZarVladimirII** [comment]
Hello, I registered to tell this is an **essential** problem.
On my Android 10 phone (One Hyper) it is the same. The intention is to start using it with nearly no Google-Apps.
Thanks to you guys it starts to be possible. But with this bug it is not recommendable to anyone. You can´t say this is better but prior to be able to use it you have to do this and that. To solve this is more important than any GUI-improvement or feature.

Good thing for all with this. The bug can be outlined without coming back to Google-Contacts and/or re-install anything:

1. Create an dummy entry and just use the export function.
2. Re-import this entry (you may also play around with the created vcf-file)
  Import of any vcf may fix it too.

Still in v6.7.0

**Comment by eklausme** [comment]
I observed the following: I did not want to let SimpleContacts to touch my Google contacts, so I denied access to contacts. This is asked whenever you start SimpleContacts (and can then be saved).

In this case, no (Google) contacts access: I wanted to import a VCF which failed. I had to enter a contact manually. After this manual entry I could import the same VCF without problems.

**Comment by tibbi** [comment]
should be fixed in 6.9.0, let me know if not. I still havent figured out how to initialize the SIM contact source, only the local Phone one will work.

**Comment by ZarVladimirII** [comment]
When saving the first contact no storage is pre select (Wether internal nor gmail).
Thus lead to be able to create a contact/contacts that are not visible by SimpleContacts but Phone-App and other (QKSMS...)

After selecting a place they show up accordingly after creation, also when editing out from Phone-App and select at least gmail.

-> Please pre select phone storage or ask the user at first, a change to somewhere else is still possible afterwards but difficult with a contact not showing up.

**Comment by tibbi** [comment]
ye that should be fixed in 6.10.0 released soon
