### ISSUE TITLE
Feature Request: Add dialer shortcut

### ISSUE THREAD

**Issue by Matombo** [SimpleMobileTools/Simple-Contacts#503]
Add an option to enable a seperate shortcut/appicon that directly opens the dialer.

**Comment by mistanoize** [comment]
Seconded.

**Comment by tibbi** [comment]
It is already there, you can see the Dialpad shortcut after long pressing the app icon on Android 8+

**Comment by Matombo** [comment]
Thanks! I would have never found that xD.

I guess this is part of android, but: the dialer shortcut has a small icon of the contacts app on top, can i somehow hide that? so that it's just the dialer icon

**Comment by tibbi** [comment]
not really, shortcuts work like that
