### ISSUE TITLE
Question: Last number called in menu? 

### ISSUE THREAD

**Issue by TobiasDev** [SimpleMobileTools/Simple-Contacts#507]
Hello, 
I'm using a OnePlus 3 with Lineage OS, and I can't seem to see the last person I called or that called me inside of the app. However, a friend that has an Samsung devices can see this in the app. Is there something I need to add / change to get this option? 

At the top with the star and such she has 4 instead of 3 options. One of them being last called.

**Comment by tibbi** [comment]
Stars are favorite contects, not last called. Call log used to be there, but it had to be removed due to Googles latest permissions policy. Not sure when will I be able to add it back, hopefully soon.

**Comment by TobiasDev** [comment]
> Stars are favorite contacts, not last called. Call log used to be there, but it had to be removed due to Googles latest permissions policy. Not sure when will I be able to add it back, hopefully soon.

Ah. Makes sense. My friends phone is no longer updated, so thats why she still has them. :) Thanks for the answer
