### ISSUE TITLE
Accessing wrong internal contact database on Android Pie (LOS16)

### ISSUE THREAD

**Issue by just-Nob** [SimpleMobileTools/Simple-Contacts#518]
## Environment:
**Simple Contacts:** v. 6.7.0 Pro, taken from F-Droid
**Android Version:** 9.0 / Pie
**ROM Version:** LineageOS 16.0
**Root:** yes, using Magisk 20.3
**Device:** BQ Aquaris X Pro

### Initial Situation:
A few days ago, I updated my device from Android 8.1 _BQ stock ROM_ to _LinageOS (LOS) 16.0_.
As I did for years, I used _MyPhoneExplorer (MPE)_ to transfer all personal data (contacts, calendars, SMS...) to the new installation, because on the one hand, I don't like to sync that data to Google servers, on the other hand _MPE_ is a really great and comfortable tool for synchronising this kind of data with a local PC.
Having a look into _LOS' default contact/dialing app_ (I think it's Google's AOSP one) is showing me that the contacts were transferred correctly into the device's storage; additionally, editing any of these contacts in LOS' standard contacts app shows "save in ['device']".
Other tools are able to access the contacts' data as well, e.g. _Birthday Adapter_ (hosted on F-Droid as well) for extracting birthdays, annuals etc..

### Issue(s) concerning _Simple Contacts_:
When I now launch _Simple Contacts_, not all of my contacts are shown, but only my _WhatsApp_ contacts; and if I'm going to open any of them (i.e. showing their content) in _Simple Contacts_, only a few data fields of the full contact's data set are displayed:
* contact's picture/photo,
* name (first name & family name),
* mobile phone number (without any formatting like spacings, brackets etc.!),
* contact's groups to which the contact is assigned to,
* place/database where the contact is stored at (it shows always ['WhatsApp']).

From syncing back my contacts to the PC by using _MPE_, I know that _WhatsApp_ creates its own set of contact data, so I guess that _Simple Contacts_ accesses / uses the wrong data set / array pointer.

Furthermore, when I'm going to edit one of those contacts, the only choices offered for storing the contact are:
* [my Google account],
* ["Phone storage (not visible by other apps)"].

There's neither a third choice named "device" or something like that (in German, I guess it was formerly named "Gerät"), nor a choice named "WhatsApp" - even so this is the initial content of the "storage" data field!

But there's still a way to access the correct (full) contacts (i.e. the correct data base) in _Simple Contact's_ contact viewer/editor for any single (internally stored) contact:
If a contact is opened in _Simple Contact's_ contact viewer/editor via another app (e.g. _Emerald Dialer_ - also hosted on F-Droid -, or _LOS' standard dialer/contacts app_... - presumable some more apps, I haven't checked out others), the full contact's dataset is visible (like it used to be in _Simple Contact's_ when running in older/other OS versions of Android):
* Full set of phone numbers (including all formatting characters inserted by me, like brackets, blanks, minus...),
* calendar dates,
* addresses
* etc.!

Anyway, using this workaround lacks the possibility of writing back the edited contact into the correct contact database, because - as mentioned above (when editing a "WhatsApp" contact) - the only choices for storing the contact still are only those two:
* [my Google account],
* ["Phone storage (not visible by other apps)"].

Due to the fact that even _Emerald Dialer_ (an independent open source tool) is able to access the correct data array of contacts (otherwise they weren't correctly displayed in _Simple Contacts_ when being passed by _Emerald Dialer_), I guess that's indeed a bug of _Simple Contacts_, not of Android / _LOS_.

**Comment by just-Nob** [comment]
With version v. 6.8.0, the behaviour changed, but isn't as expected at all.
I'm going to describe the current, new behaviour asap.

**Comment by tibbi** [comment]
If I send you a test version with some messages appearing, can you try it out? If you can, let me know at hello@simplemobiletools, it is easier to send files there.

**Comment by tibbi** [comment]
actually recheck it with 6.9.0, there will be some related change

**Comment by andreabenetton** [comment]
I think I have the same issue. When I try to import a vcf file, I have only one destination available, Phone Storage (not visible by other apps). I have used successfully the app one year ago (with lineageos 16 and a previous version) to do exactly the same thing. 

Simple Contacts: v. 6.8.0 Pro, taken from F-Droid
Android Version: 10.0 
ROM Version: LineageOS 17.1
Root: no
Device: Google Pixel XL (marlin)

**Comment by tibbi** [comment]
well you apparently dont have 6.9.0 yet though. It has been released quite a few days ago, not sure why hasnt it been updated on f-droid yet.

**Comment by just-Nob** [comment]
Hi tibbi,
I sent you a PM via email. Sorry for the delay (see PM for reasons) Just mail me your latest version (no matter if standard or debug version) and I will test it.

**Comment by just-Nob** [comment]
After doing a few tests (using Simple Contacts v., 6.9.0 from github) I came to some confusing results.  So it seems that the problem described by me is more with MPE, at least partly. Due to this I will get in contact with MPE's author as well.

One question to @andreabenetton : Is your problem gone with v. 6.9.0?

The following behaviour was observed by me:

1. While contacts written to the contact memory via MPE are not visible for Simple Contacts, new contacts created in the phone (via LineageOS' standard contact tool as well as via Simple Contacts) are also displayed in Simple Contacts.

2. LineageOS' standard contact tool is able to see both 'kind' of contacts: Those created by MPE as well as those newly created. The same with Emerald Dialer and Birthday Adapter - all contacts sends to be visible to them.

3. The new contacts created in the phone cannot be synchronized with MPE, i.e. they do not appear to be visible to MPE.

**Comment by andreabenetton** [comment]
I will as soon as 6.9 is available on f-droid.
Aurora Store also has the same update problem, it is 2 version in delay with their GitLab version, the old version seem don't connect anymore to google, so I have to wait. I let you know as soon as I have updated.

**Comment by andreabenetton** [comment]
> One question to @andreabenetton : Is your problem gone with v. 6.9.0?

No, the problem is still here.

> new contacts created in the phone (via LineageOS' standard contact tool as well as via Simple Contacts) are also displayed in Simple Contacts.

The same. I can add that the contact I have added from the standard contact app can be deleted from Simple Contact.

I noticed also that the importing works (with the problem described in this issue) only if I start from the file manager app long-touch the vcf file. If I use the importing menu of the simple contact app, the vcf appears grey, and I cannot proceed. Can it be a problem for the app to access storage (rights)?

**Comment by just-Nob** [comment]
Hi @tibbi ,

sorry for my late reply. I ran a little out of time the last few weeks.
Yesterday, I found out the following:

The problem leading to this issue seems to be caused by the way LOS implements its "DEVICE" account. By the first view, "DEVICE" looks like an usual account for contacts; for example, it's listed under "Accounts" in LOS' build-in contact app. _Simple Contacts_ detects it as an account as well. That's why I assumed that _MPE_ should be also able to find it - or rather why I guessed _Simple Contacts_ made some mistake when accessing the "DEVICE" account.

Having said this, _MPE_ isn't able to access it, not even to find it!
When I recognised that, I thought about a bad/faulty behaviour of _MPE_. But one have to look out: Unfortunately, "DEVICE" isn't a full-featured at all! You have to take a look at LOS' settings under "Accounts": There's no account called "DEVICE"! This is the reason why _MPE_ writes all contacts' content somewhere where LOS itself is able to see it, but _Simple Contacts_ isn't.

In the end, I installed _MyLocalAccount_ (provided by the author of _MPE_), activated the account in LOS' account settings, and everything works fine now!

I'm sorry for all the trouble caused by this issue.
From my point of view, it's gonna be closed. But because of @andreabenetton's problem (which still seems to be existent), I won't close it this time.

**Comment by tibbi** [comment]
this is one of those issues that will probably be open forever :) Contact handling is a huge mess and it really needs to be remade from scratch by Google, some fixes wont help. Just check the official Google Contacts app how bad ratings it has aswell https://play.google.com/store/apps/details?id=com.google.android.contacts&showAllReviews=true . Sometimes people have issues related to this one, sometimes it is something different that works well in Simple Contacts.

**Comment by just-Nob** [comment]
Yes, Google succeeded in confusing me for certain weeks with their obscure and inconsistent "concept" of contact accounts! ;-)

Anyway, once again:
For me, this issue could be closed. My problem is now known, it's no problem of _Simple Contacts_, and a workaround/solution is available.

Maybe it's smarter if @andreabenetton opens a new issue for his problem(because I don't think anymore that his problem is really related to mine) and I'm going to close this one.

@andreabenetton , what do you think about my suggestion?

**Comment by andreabenetton** [comment]
> @andreabenetton , what do you think about my suggestion?

Fine for me to open a new issue.
