### ISSUE TITLE
vCard implementation fragmentary

### ISSUE THREAD

**Issue by ZarVladimirII** [SimpleMobileTools/Simple-Contacts#519]
My observation is that several aspects of vCard are infringed.
There are already some specific issues opened:
#327 vCard4 import photo
	#349 Export photo
	#501 Phone type usage
	#364 Adress

I know about ez-vcard
https://github.com/mangstadt/ez-vcard
https://github.com/mangstadt/ez-vcard/wiki/Supported-Specifications
So before anything else, either ez-vcard (Android project) is not supporting the specifications correct or the implementation into SimpleContacts is buggy.

A point that is missing is the _full name_ descriptor **FN**. -> Import in other software might be faulty.
Worse in second example over bluetooth. Exported contact name doesn´t match name in VCF. Might have occured because of #491. I have also two dummy contacts three times in one full export file. They show up only once in every program.

One dummy exported to Storage
`BEGIN:VCARD`
`VERSION:3.0`
`PRODID:ez-vcard 0.10.5`
`N:Speicher;Test`
`TEL;TYPE=CELL:555485`
`EMAIL;TYPE=HOME:dr@da.com`
`END:VCARD`

One dummy exported through Bluetooth to PC. Contact Name **Emerald test**
`BEGIN:VCARD`
`VERSION:3.0`
`PRODID:ez-vcard 0.10.5`
`N:Zimmermann;Hannah`
`END:VCARD`

_For the Bluetooth export. Every contact is exported in a single *.VCF file. That´s kind of stone age._
But repeated now, it happened (again) that some VCFs are just empty. Not with the same contacts after some changes in the saved contacts list.
I also used the _file-app_ and shared the contact.vcf to PC with the same result.

Importing a real contact, created with CardBook in Thunderbird resulted in:
	

-  import VCF saved in Unicode or UTF-8 fails
-  ä, ö, ü wrong imported when saved in ANSI
-  ZIP Code and City get lost  connects with #364

		RFC6350(vcard4.0) 6.3.1 specifies order to use
-  e-mail saved as URL (accidently as URL) got lost

`BEGIN:VCARD`
`VERSION:3.0`
`UID:somethingxxxxxxxxxxx`
`ADR;TYPE=HOME:;;Griesxxx 30 \nKüxxxxxx ;Bad Xxxxxxried ;;88XXX;`
`ADR;TYPE=WORK:;;Rol.... 9 ;City ;;88XXX;`
`FN:XXXwäb.Museumsdorf City `
`N:XXXwäb.Museumsdorf City ;;;;`
`NOTE: correct imported`
`REV:20170417T134014Z`
`TEL;TYPE=WORK:XXXXXX42050  Kasse`
`TEL;TYPE=FAX:XXXXXX420516`
`TITLE:XXX ür...`
`URL;TYPE=WORK:name@city.de`
`URL;TYPE=HOME:name2@city.de`
`X-THUNDERBIRD-ETAG:0`
`END:VCARD`

For the next:
	- examples **FN** and **N** are important. Both different, FN gets dropped. connected to #215
	- _EMAIL;TYPE=PREF;TYPE=HOME:_ gets _pref_ but it is 'preferred Privat' address  (missing feature, but a standard in _vCard Format_, if something is dropped than it should be _PREF_). 
	- address same

`BEGIN:VCARD`
`VERSION:3.0`
`UID:number something`
`ADR;TYPE=WORK:;;Lise-Meitner-Str. 14;Ulm;;89081;Deutschland`
`EMAIL;TYPE=PREF;TYPE=HOME:name@inmach.de`
`EMAIL;TYPE=HOME:otherguy@inmach.de`
`FN:InMach Intelligente Masch.GmbH`
`N:InMach GmbH;;;;`
`NOTE: correct imported`
`REV:20170417T134014Z`
`TEL;TYPE=WORK:+49 XXXXXXXX6672`
`X-THUNDERBIRD-ETAG:0`
`END:VCARD`

Entered in SimpleContacts and exported onto storage with file-manager.
`BEGIN:VCARD`
`VERSION:3.0`
`PRODID:ez-vcard 0.10.5`
`N:Dummy;Address`
`NICKNAME:Test 8`
`TEL;TYPE=CELL:8888888888`
`EMAIL;TYPE=HOME:vorthat@shit.org`
`BDAY:1998-03-16`
`ADR;TYPE=HOME:;;Grabenweg 12\n55555 Bled`
`ADR;TYPE=HOME:;;Gießweg 77\n77777 Geiš`
`IMPP:icq:2374727499`
`END:VCARD`

For **ADR** _address_, good both HOME are handeled. Compared with above the remaining `;` are missing. Looking into the Specification sheets this is a violation.

At this stage SimpleContacts is incompatible with Nextcloud, cardDAV, DavX5(DAVDroid) and cardBook. _Use together on your own risk, or only import._
As I see implement full vCard4 import and export correct (On vCard3 level) will solve a lot of open bug and feature issues at once.

My work around suggestion to reduce import/export frauds is using _MyPhoneExplorer_ (but it´s also not perfect).

Specification notes:
RFC 6350 10.3.1. Properties Registry* lists all the possible entrys for vCard4 (a lot)
FC 2426 4. Formal Grammar* for vCard3, but more difficult to read. But already 1998, as I figured out now. (A bit outdated.)
www.acatysmoof.com/posting/openwebmail-patches/041025/vCard-2.1/vcard-21.rtf who wants to read vcard2.1 (1996)

**Comment by tibbi** [comment]
vcard has just been upgraded to version 4, starting in app 6.17.0. If you still have some issues please report them one by one.
