### ISSUE TITLE
Website not shown

### ISSUE THREAD

**Issue by rugk** [SimpleMobileTools/Simple-Contacts#521]
## STR

1. Import this (in your Nextcloud): https://gist.github.com/rugk/817048d3a43be5711647ce611993bbe3
2. Sync it with DAVx⁵.

What happens: No website shown e.g. in the listing for "Telefonseelsorge".

What should happen: Show me the website.

The .vcf file has been exported from Nextcloud before.

---

Nextcloud 12
Android 9
DAVx⁵ 2.6.5-ose (334)

**Comment by tibbi** [comment]
it shows up just fine to me

**Comment by rugk** [comment]
Did you really import that? Maybe there is some other error, because I've imported it in Nextcloud and synced with DavX5, which should not make a difference though.

It still does not show up for me:
![nowebsite](https://user-images.githubusercontent.com/11966684/86904144-9021e780-c110-11ea-814a-43954114ffd2.png)

**Comment by tibbi** [comment]
make sure you have "Website" enabled at the app settings -> manage visible contact fields

**Comment by rugk** [comment]
Whuuut, there are setings… Oh please.

Then please enable thjis by default, a website is an essential thing.
