### ISSUE TITLE
Does not render company/organisation ("ORG:") field

### ISSUE THREAD

**Issue by rugk** [SimpleMobileTools/Simple-Contacts#523]
The company ("Firma") field is not rendered locally.

You can edit/add that directly below the contact name in the Nextcloud Contacts app.

The resulting vcf field is "ORG:".
Example here: https://gist.github.com/rugk/817048d3a43be5711647ce611993bbe3/02c6183e380542f5c20342fea922e06f8ccd019c#file-notrufnummern-vcf-L69

**Comment by tibbi** [comment]
it seems to work fine to me, the select contacts organization is Nummer gegen Kummer

**Comment by rugk** [comment]
Yet gain, no it its not shown for me.

**That said** searching for "kummer" e.g. works. The official name "Kinder-, Jugend- und Elterntelefon" still appears though.

![noorg](https://user-images.githubusercontent.com/11966684/86904388-f0188e00-c110-11ea-899d-e1e90c186601.png)

Please reopen this.

**Comment by rugk** [comment]
Also, even if it would show up, one should also be able to **edit** it.

**Comment by tibbi** [comment]
make sure you have "Organization" enabled at the app settings -> manage visible contact fields

**Comment by rugk** [comment]
Ah, yet again, I don't see why this is disabled by default.

Having that hidden in the settings is not a good UX IMHO. Maybe when you see/edit an entry just show all entries the entry has + if yiou edit it maybe have a "show more fields" button that shows all of these other entries.

**Comment by tibbi** [comment]
the vast majority of people dont need such fields to be visible, it is described in the FAQ too. It might change in the future, we will see.

**Comment by rugk** [comment]
Well… at least, IMHO, you should *show* all fields when displaying an entry. There is nothing wrong with that, I usually have plenty of whitespace below the last line, and hiding things may not always be the best.
