### ISSUE TITLE
Wrongly imports the phone number type as "voice"

### ISSUE THREAD

**Issue by rugk** [SimpleMobileTools/Simple-Contacts#526]
When you import my sample file with this app, it imports the phone number type as "voice", see nextcloud/contacts#1521

file: https://gist.github.com/rugk/817048d3a43be5711647ce611993bbe3/02c6183e380542f5c20342fea922e06f8ccd019c

Should be: "miscellaneous" as when you import it via Nextcloud

Split from https://github.com/SimpleMobileTools/Simple-Contacts/issues/524

**Comment by tibbi** [comment]
which number you mean? There are many contact files, most of them indeed have TEL;TYPE=VOICE

**Comment by rugk** [comment]
Have a look at https://github.com/nextcloud/contacts/issues/1521

If you import my file **locally** AFAIK / IIRC there is a difference in  behaviour:
* Nextcloud renders `TEL;TYPE=VOICE:116 116` as a "call" number, which is the correct term
* This app shows it as "miscellaneous"

IIRC this was the problem. (note this issue is really old and I'm not sure whether I recall it correctly.)

**Comment by tibbi** [comment]
should be solved already
