### ISSUE TITLE
Add Call log to the app

### ISSUE THREAD

**Issue by contactwajeeh** [SimpleMobileTools/Simple-Contacts#538]
Can you please add call log to the app, after that it can be used as an all in one replacer for contacts & dialer.

**Comment by tibbi** [comment]
Call log used to be there, but it had to be removed due to Googles latest permissions policy. Not sure when will I be able to add it back, hopefully soon.

**Comment by contactwajeeh** [comment]
Which version had it?

**Comment by tibbi** [comment]
6.1.2

**Comment by contactwajeeh** [comment]
I see the adding of recents is an issue on google play, can you make one different branch for F-Droid or Github where you are restricted to provide that.

**Comment by tibbi** [comment]
I dont want to maintain multiple app versions. Im already working towards adding a proper dialer in the app, then I might get the permission already. It is just really difficult to implement.

**Comment by contactwajeeh** [comment]
Understood, fair enough. Look forward to it. Appreciate your time.
