### ISSUE TITLE
Groups are created as smt_private when importing a .vcf file

### ISSUE THREAD

**Issue by QuickJack** [SimpleMobileTools/Simple-Contacts#539]
Thanks for this nice app. It seems the only solution on Android which can handle groups (or labels) correctly when importing/exporting contacts.

When creating a new group, the destination account must be selected. The app lists the Google accounts or smt_private (there is no description for the user what smt_private actually means). However, the destination account cannot be selected when importing a .vcf file. Furthermore, a group's account location cannot be edited.

Groups created as smt_private (and the contacts within this group) are not visible by other apps.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by QuickJack** [comment]
I've tested it today using 6.9.0

**Comment by QuickJack** [comment]
I found a similar problem. When trying to create a new group, the app suggests a list of contact sources as a target. On my phone it lists the Google accounts and smt_private. It does not list WhatsApp and "Local Contacts". But the latter two are listed when trying to create a new contact.

By the way, I am using the app MyLocalAccount which provides "Local Contacts" because my phone does not support a local contact source.
