### ISSUE TITLE
"App Not Installed" error with 6.10.2 on Android 9

### ISSUE THREAD

**Issue by QuickJack** [SimpleMobileTools/Simple-Contacts#544]
I am using MIUI 11.0.8.0 (Android 9). The App cannot be installed from the downloaded APK. I have already uninstalled any old versions.

**Comment by tibbi** [comment]
where did you get the .apk? I dont see why would that be an apps issue

**Comment by QuickJack** [comment]
I've downloaded it from the Releases area of this project.

**Comment by tibbi** [comment]
make sure it is fully uninstalled before you try installing it, you shouldnt even see it in the device settings. If you have installed the app just cannot run it, have you maybe changed the icon color? Some launchers do not handle that properly and just make the icon disappear. You should either change your launcher app, or just stick to the default orange icon.

**Comment by QuickJack** [comment]
There was an old installation in the second profile. It is working now. Thanks.
