### ISSUE TITLE
Feature Request: Per-Contact Notification Tones for Message and Call

### ISSUE THREAD

**Issue by Saijin-Naib** [SimpleMobileTools/Simple-Contacts#552]
I'd love to see the ability to set custom Notification Tones per contact for Text/Call events to help differentiate each contact from one another.

**Comment by tibbi** [comment]
the Dialer part of the app has been moved into Simple Dialer at https://play.google.com/store/apps/details?id=com.simplemobiletools.dialer , so it will be removed from Simple Contacts soon. Report such issues at Simple Dialer and Simple SMS Messenger.

**Comment by Saijin-Naib** [comment]
Thank you! I was unsure if this was best filed here or in the Dialer.

**Comment by aGrimRepoMan** [comment]
Would it be possible to distribut this app (Simple Dialer) via F-Droid too?
Thanks for considering this.

**Comment by tibbi** [comment]
ye it has been accepted on f-droid yesterday, so it should be available within a couple days
