### ISSUE TITLE
Feature Request: Pin Contact Card to Home Screen

### ISSUE THREAD

**Issue by Saijin-Naib** [SimpleMobileTools/Simple-Contacts#553]
I'd love a means to pin contacts to the home screen/launcher using their contact photo or the generated contact icon/bubble.

Quick actions on tap/hold for the contact would also be amazing (Issue #554 ).

**Comment by Aga-C** [comment]
Isn't it already implemented as creating shortcut?

**Comment by tibbi** [comment]
it is
