### ISSUE TITLE
Feature Request: Quick Action for Pinned Contacts

### ISSUE THREAD

**Issue by Saijin-Naib** [SimpleMobileTools/Simple-Contacts#554]
I would love, if we get pinnable contacts as per Issue #553, that there be quick actions for the contact such as Call, Text, Email, etc.

**Comment by priyank-py** [comment]
Is it ok if we create a widget with list of favorite contacts on homepage?

**Comment by Saijin-Naib** [comment]
That is okay, I guess, but likely will end up very large and bulky compared to a single contact widget.

**Comment by priyank-py** [comment]
Bulky depends on how big it the favorite list and how often we are updating the widget.

**Comment by Saijin-Naib** [comment]
Not my preference, but I can certainly see how many people would like and use that style of widget. In fact, some other messaging apps and launchers include such a style widget.

Any which way you decide to go, thanks for adding functionality.

**Comment by tibbi** [comment]
ye, should be good enough
