### ISSUE TITLE
Feature Request: Contact "Timeline"/History Panel

### ISSUE THREAD

**Issue by Saijin-Naib** [SimpleMobileTools/Simple-Contacts#556]
Following along with Issue #555 , I would love for there to be a Timeline/History panel in the Contacts list per Contact, that would show you the list of recent calls, texts, calendar events, etc. shared between you and that contact.

I grew quite accustomed to this on W10M/W10 Desktop, and really value the UX of being able to easily jump back to a prior conversation as a point of reference.

Attached is an example image:
![image](https://user-images.githubusercontent.com/19295950/81996364-ccf2c600-961a-11ea-9565-de09a3269d7d.png)

**Comment by tibbi** [comment]
the app has no access to Call Logs and SMS, thats why Simple SMS Messenger and Dialer had to be published

**Comment by Saijin-Naib** [comment]
Is that something that Google does not allow, or just not a direction you'd like to go? I think it'd be incredibly handy, honestly.

**Comment by tibbi** [comment]
it is something Google doesnt allow. Thats why I had to create those separate apps, they strictened some permission granting.
