### ISSUE TITLE
Inconvenient birthday input for year

### ISSUE THREAD

**Issue by rugk** [SimpleMobileTools/Simple-Contacts#565]
Problem: You use the default(?, or at least a bad) date picker for the birthday in Android.

However, when I input a birthday that is likely a few years ago.
The default picker does not allow me to input the year manually, so I would have to swipe 12*30 (for a 30 y/o person) times to the left, because well… you can only cycle in years.

Solution:
* let me enter the year manually (and also omit it, if I don't know it)
* still let me use some kind of picker for day+month

**Comment by tibbi** [comment]
the app uses the system date picker, it isnt made by us. Usually you can click on the Year too and select it quickly.

**Comment by rugk** [comment]
Uuuugh, yes you can! :tada: 

Anyway, still inconvenient.

Also, you don't allow saving the birthday without a year (when one does not know it, e.g.). Maybe we should change this issue to track this? (Technically it may be the same, you'd need to somehow have to decouple the year from the date.)

**Comment by tibbi** [comment]
it is already reported elsewhere

**Comment by rugk** [comment]
Ah yeah, even cross-linked it already. Sry. It's https://github.com/SimpleMobileTools/Simple-Contacts/issues/264
