### ISSUE TITLE
Remove or disable by default the dialer from the app

### ISSUE THREAD

**Issue by smilearric** [SimpleMobileTools/Simple-Contacts#569]
Hello,

Latest versions of the simple contact app which I like very much bundle the dialer which take over my phone's default.

Since you developed the dialer as a separated app, maybe you could just remove it from this one or at least add a setting which by default has it disabled.

The problem is the bundled dialer is a basic/lightened implementation:

- it doesn't allow me to use the "loud"/hands free speaker of my phone which is blocking my usage
- a minor issue is the display of long name which should be centered like the other items of this view instead of stuck to the left

I cannot downgrade so please consider this, other users may be affected.

Many thanks for your nice suite!
I use this one and the gallery. Have the Camera installed too.

Regards

**Comment by tibbi** [comment]
All calling related functions will be moved into Simple Dialer soon, that is indeed the plan. Simple Dialer has just been released, I want to fix a fe wmore things. The loud speaker already works there.

**Comment by tibbi** [comment]
will be removed in 6.11.0
