### ISSUE TITLE
`Use English language` setting not working on Android 7.0

### ISSUE THREAD

**Issue by Jonas1312** [SimpleMobileTools/Simple-Contacts#574]
I already had the same issue with another opensource app before https://github.com/beemdevelopment/Aegis/issues/287

<details>
<summary>Screenshot</summary>

![Screenshot_20200604-105721](https://user-images.githubusercontent.com/15847892/83736941-a096fc00-a652-11ea-832b-2f4ad0c68926.png)

</details>

    Version: 6.11.3
    Source: Fdroid
    Device: honor 5C
    Android version and ROM: 7.0

Thanks

**Comment by tibbi** [comment]
it could be a more generic system glitch unrelated to the language changer. Does changing the text size work?

**Comment by Jonas1312** [comment]
> 
> 
> it could be a more generic system glitch unrelated to the language changer. Does changing the text size work?

nope, doesn't work. restarting my phone didn't help

**Comment by tibbi** [comment]
retry with 6.13.0
