### ISSUE TITLE
Not all contacts visible

### ISSUE THREAD

**Issue by Machion** [SimpleMobileTools/Simple-Contacts#575]
A long time ago I wrote that with my motox4/android9 I can only see signal contacts. 
This bug still persists with version 6.12.0 

But it's interesting, that your new dialer app (great app btw, there are too less good (free) dailer apps out there) shows all my contacts as it should be. Maybe this hint helps you.

**Comment by tibbi** [comment]
well the way contacts are handled by those 2 apps differ, Ill take a look at it
