### ISSUE TITLE
Cannot remove empty groups

### ISSUE THREAD

**Issue by sciurius** [SimpleMobileTools/Simple-Contacts#578]
I have several empty groups: Coworkers, Family, Friends, ICE and Unfiled. 
How to get rid of these groups?

Note that some of them have alternatives in my local language, e.g. Familie and Vrienden.

Version v 6,4,1 on Samsung Galaxy A3 (2017) with Android 8.0.0.

**Comment by tibbi** [comment]
if you select them by long pressing, then press Delete at the top menu, doesnt it work?

**Comment by sciurius** [comment]
Stupid me... Tried everything except this.  
They're gone now, hope they stay away.  
Thanks.
