### ISSUE TITLE
Simple Contacts is not accessing contacts stored on device.

### ISSUE THREAD

**Issue by techware01** [SimpleMobileTools/Simple-Contacts#579]
Hello I'm fasing the issue that it's not possible to store new contacts to the device so that all other apps (like the aosp contact app or signal) can show / import them. The only option to choose where to save the contacts are "OpenKeyChain and Phone stoarage (not visible by other apps)". Also contacts that I created with the default app are not displayed in simple-contacts. It looks like the app  is not accessing the contacts storage. I gave it all needed permissions and set the filter correctly. All my Signal contacts though are listet in simple contacts.

App: 6.12.0 (F-Droid)
OS: GrapheneOS (Android 10)

**Comment by tibbi** [comment]
if you try disabling Signal app, do the other contacts show up well? There seems to be a weird Signal related glitch that I dont understand yet.

**Comment by techware01** [comment]
How is it possible to disable app that are not pre installed in Android?
So I complety uninstalled signal and restarted the phone to test this, but afterwards simply no contacts were displayed. After installing Signal again everything is like it was.

**Comment by tibbi** [comment]
hm okay, weird.. Ill do some tests myself. Thanks

**Comment by MagicMuscleMan** [comment]
I can confirm the bug on Android 9 with the f-droid version. I think it worked for nearly half a year until it probably stopped few weeks ago.

I have no Signal installed on that system. However, Silence, which shares common roots with Signal, is installed.

Would it make sense to test some downgrades to see if older versions work again and possibly which version change broke it? Where can I get old f-droid versions from or where can I get the build instructions?

If that does not work, would it make sense to use a debugger? Which function in which file would be interesting for debugging this problem?

**Comment by tibbi** [comment]
You can find all older versions on Github, they are at https://github.com/SimpleMobileTools/Simple-Contacts/releases . Just try some very old version first, to see if it ever worked at all, as I cannot reproduce it on any of my devices. I dont think any debugger would help. Thanks

**Comment by zayuim** [comment]
Hi all, just tried this app recently and have had the same problems. I have a Moto G7 Power running stock Android 10. I am using the F-Droid version. I have enabled all permissions in the Android app settings before reporting.

- Version 6.1.2 was the last version that would show my contacts from the device. Previous versions would work also, but required me to go open the settings and back to the main page to trigger the sync.
- Version 6.2.0 does not show the system contacts. I can create a contact with Simple Contacts and it will show in Google Contacts, but the contact created won't show in Simple Contacts.
- Version 6.12.7 is completely isolated from the contact storage. Contacts created will show, but only in Simple Contacts.

@tibbi I would be pretty interested in a debug feature that will try and force a sync with the contact storage.

**Comment by xbjfk** [comment]
I think that 4dcb46 broke it on 6.2.0 and 8e91a0b must have broke 6.12.7, because all other changes in 6.12.7 are language-based.

**Comment by xbjfk** [comment]
I can also confirm the behaviour stated, using 6.13.1 from F-Droid, the only option for contacts is phone storage (not visible by other apps)

**Comment by hype11** [comment]
I can confirm this for Android 10 and 9 with version 6.13.1 from F-Droid

**Comment by trevorthalacker** [comment]
My guess: Signal is probably storing contacts using Google Play Services, which I assume the F-Droid version isn't using as much. The play store version works just fine,  yet any downloaded APKs and the F-Droid version do not work at all with Signal.

**Comment by stubb** [comment]
Can confirm the problem with Android 11 and version 6.14.2 from F-Droid. The version 6.1.2 recommended by @zayuim seems to not compatible with Android 11 and crashes on startup.
