### ISSUE TITLE
feature request:  Allow contacts to be saved outside of a google account only locally on the device

### ISSUE THREAD

**Issue by mdkuser** [SimpleMobileTools/Simple-Contacts#58]
Can you please add an option to save contacts only localy on the device without linking it to a google account? Same as local calendar in your simple calendar app.
So the contacts are never synced to the cloud!

**Comment by tibbi** [comment]
it should already be possible. If you press the New Contact button and click on the bottom field with a user icon, do some options show up? One of them should be some equivalent of "Phone Contacts", that shouldnt be synced to the cloud by default.

**Comment by mdkuser** [comment]
Hi, I alresdy tried this, but the only options I can choose are:

1) my google account (user@gmail.com)
2) ooen keychain account

No local contact

I'd like to store contacts on the device only and deactivate googles contact app and substitute it with simple contacts. 

Btw: At the moment simple contacts are not supporting all fields from android contacts app (e.g. pager or instant messenger information are not displayed, can't be edited in simple contacts)

**Comment by mdkuser** [comment]
Hi, I alresdy tried this, but the only options I can choose are:

1) my google account (user@gmail.com)
2) ooen keychain account

No local contact

I'd like to store contacts on the device only and deactivate googles contact app and substitute it with simple contacts. 

Btw: At the moment simple contacts are not supporting all fields from android contacts app (e.g. pager or instant messenger information are not displayed, can't be edited in simple contacts)

**Comment by tibbi** [comment]
will be added in 3.2.0 which Im just releasing

**Comment by mdkuser** [comment]
Hi, thank you for implementing the local storage for contacts.
However, this feature is quite useless if the main telephone app can't access the local contacts.
I wonder how to make the cobtacts localy available to installed apps, but exclude it from syncing at all with google.
Would this possible?

**Comment by tibbi** [comment]
You can uncheck Google syncing contacts in Settings -> Accounts -> Google and pick an email. For that you dont need this new hidden contact group.

**Comment by mdkuser** [comment]
Ok, but if accidentily the snyc gets enabled, it will upload all contacts to the cloud without notify the user.
The contact app should if possible store contacts so that it can't be seen by google sync but entries are visible to apps on the device only. Similar as storing contacts to simcard. Would that be possible, or is it a limitation from

**Comment by tibbi** [comment]
You cant just selectively set who you share the contacts with. Maybe on a rooted device with some extra security apps, but that is not my job already.
