### ISSUE TITLE
No contact name when multiple numbers available

### ISSUE THREAD

**Issue by SMTSCI1** [SimpleMobileTools/Simple-Contacts#583]
When I recieve a call or a message (or start a call/send a message) via the simple mobile tools apps, I only see the contacts name for one number of this contact. 
If there are multiple numbers saved, I don't see the name for the second or third added number when calling or writing.

**Comment by tibbi** [comment]
calls are not handled by Simple Contacts Pro anymore, please use Simple Dialer at https://github.com/SimpleMobileTools/Simple-Dialer for it
