### ISSUE TITLE
Isn't this app supposed to be reused?

### ISSUE THREAD

**Issue by ron5673** [SimpleMobileTools/Simple-Contacts#586]
It's easy to fund a developer, but it doesn't make sense if you can't adapt to the project you're working on (ie you can't do a full version).
Are there any projects that pay for  file is unlock read-only?
(It doesn't matter if the functions are somewhat limited. We can't provide the app with the dark theme.)

**Comment by tibbi** [comment]
no, it is not supposed to be reused
