### ISSUE TITLE
Sharing a contact to WhatsApp results in faulty contact name

### ISSUE THREAD

**Issue by just-Nob** [SimpleMobileTools/Simple-Contacts#587]
## Description:
I've shared one of my contacts to WhatsApp. Usually, there's the contacts name displayed. In that case, the contact's _company_ was displayed instead of the contact's _name_.
Astonishingly, the shared contact's _**WhatsApp** profile picture_ (**not** the contact's picture on my phone!) was shown correctly.

When trying to save that shared contact as a new contract on my phone, the contact's name was totally dissipated.

## Environment:
- **_Simple Contract_'s version:** 6.12.6 Pro
- **OS:** LineageOS 17.1 (Android 10)
- **Device:** BQ Aquaris X Pro

**Comment by tibbi** [comment]
what do you mean by sharing contact to WhatsApp? Please give some steps for reproduction.

**Comment by just-Nob** [comment]
Just do the following:

1. In _Simple Contacts_, select a contact that you like to send to someone else via WhatsApp by doing a long tap on it (i.e. you like to _share_ it with someone else by sending it via WhatsApp).

2. Tap on the three dots in the upper right corner to open the menu.

3. Select "Share".

4. A list of apps opens. Select _WhatsApp_ as the target for the _share_ action (i.e. as the app via you like to send/share the contact).

5. In WhatsApp, select one or more _target contact(s)_ as receiver for the data of the contact that you selected in _Simple Contacts_ for being shared.

6. WhatsApp will ask you if you are sure that you like to share the contact with the selected person(s).

7. After confirming the safety request, the contact is being send via WhatsApp to your target contact/person(s).

**Comment by tibbi** [comment]
ok cool, thanks

**Comment by just-Nob** [comment]
You're welcome! :-)

**Comment by tibbi** [comment]
what contact name fields do you have filled in that case where you can reproduce the issue? I mean first name, last name etc?
