### ISSUE TITLE
Search by number only searches the primary numbers

### ISSUE THREAD

**Issue by wombatch** [SimpleMobileTools/Simple-Contacts#588]
Doing a search by telephone number only searches the first number recorded for a contact with multiple numbers, if you search for the second number, there is no result.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by wombatch** [comment]
Currently (the version I see  the issue with) 6.12.6 Pro

**Comment by tibbi** [comment]
it works fine to me. Make sure you really try it with the latest app version.

**Comment by wombatch** [comment]
Sorry, you are right, this was a case of there being duplicate entries in the contacts list, one entry with one number and the other entry with the other number, both under the grouping "Phone". 
Sorry to have bothered you.
