### ISSUE TITLE
F-Droid build - offer to install Dialer

### ISSUE THREAD

**Issue by licaon-kter** [SimpleMobileTools/Simple-Contacts#592]
...from F-Droid instead?

Is this ok @tibbi ? It will be an F-Droid metadata `sed` for this https://github.com/SimpleMobileTools/Simple-Contacts/blob/master/app/src/main/res/values/strings.xml#L20 no changes here needed.

Or, are those `market://` links still working?

**Comment by tibbi** [comment]
that dialog probably isnt even shown to anyone anymore, it was added 3 months ago to existing users at https://github.com/SimpleMobileTools/Simple-Contacts/blame/master/app/src/main/kotlin/com/simplemobiletools/contacts/pro/activities/MainActivity.kt#L614 . I will remove it soon together with the string.

**Comment by licaon-kter** [comment]
Ref: https://forum.f-droid.org/t/simple-mobile-tools-contacts-tries-to-download-a-dialer-app-not-from-f-droid/10710/
