### ISSUE TITLE
Import contacts from a .vcf file

### ISSUE THREAD

**Issue by ZarVladimirII** [SimpleMobileTools/Simple-Contacts#596]
I wanted to import an vcf-file.
Possible relations #420 

1. Problem
Possible storages would be:
- "Phone storage (not visible by other apps)"
- "google account" (gmail-address)

But there was shown only the one where it will be imported, no option to choose. And of course, at first was the wrong database 'active'. Creating an dummy entry to the other storage switched the shown target.

2. Problem #519 
 Simple Contacts is able to show Address-Information consisting of several lines (corresponding Postal descriptors), also to fill them in.
Also synching with MyPhoneExplorer, Nextcloud, DAVx5 etc. showed to work correct.
But when using the internal "Import contacts from a .vcf file" option it fails.
But this internal way most users will be using.
I think I repeat myself, correct transition of contact information is crucial. 'Mainstream' users don´t care if it is an external engine (ez-vcard) fault, the implementation of it or the apps/your fault.

As long as there is no full certain support it should be marked as: "Experimental, use for reliability free external software".
An idear to tell the user. A switch in the settings to activate import/export. When activating a message box appears.

**Comment by ZarVladimirII** [comment]
But thats the point. This is unwanted, unintended. And an option to select prior to this screenshot does not exist right now. I´m not asked where I want it to be imported. Furthermore an normal contact-database with address information birthdays and so on and people not using this messenger has nothing to do with the Telegram/messenger-Account database. Also messenger-Accounts/databases have no phonenumber themselfs saved in the through contact-apps accessible database, as I understand.

To view on messengers only is half the story.
If not only one googe-account is available. Lets say another google-account or a DAVx5 adressbook, this way it´s not intuitive to see/know how to switch to which target source the vcf will be importet.

- "Phone storage (not visible by other apps)"
- "google account" (gmail-address)
- "other google account"
- "other created contacts database that is seperate from the others"

If you don´t think it´s a bug as I do, than it´s a feature request.

Instead of just name the actual selected database, let it be as in the view-selector(which contacts database is visible), let one or even more be selected and with "OK" it´s imported there. I don´t care if then a messenger still appears in this box.

And thanks to your software suite, it´s much needed for the really free world.

**Comment by tibbi** [comment]
I want to keep the current behaviour, I dont like too many questions asked. The vast majority of users use only their google account with an email.
