### ISSUE TITLE
Link to messengers, directly open corresponding chats

### ISSUE THREAD

**Issue by ZarVladimirII** [SimpleMobileTools/Simple-Contacts#597]
In google´s 'Contacts-App', if a contact is using phone-number linked messengers the chat, messenger-call and video-call function can directly be accessed.

Currently out of Simple-Contacts only the messenger-apps contact description can be changed but not the app opened nor even the specific function accessed directly.

This is very inconvenient especially compared to the google-app we like to replace.

![messenger link (Handy)](https://user-images.githubusercontent.com/61712819/90954580-b1972280-e475-11ea-94e9-91360a900272.png)

This is an addition to #428

**Comment by ZarVladimirII** [comment]
😃😃 Looks good in version 6.13.1, works so far.


A note to something related I see. I have one contact, renamed different in Telegram weeks ago. Since both show up divided. I assume different sources are merged through their name. Any chance to get it work with different namings?

**Comment by ZarVladimirII** [comment]
The feature itself is added a while now, and works for Telegram and Signal. I´m surprised it is still marked as open.

With 6.15.1 on Android 11 now, I realised it is gone, and again tipping on the messenger name opens only the entry editor. There is also no App-logo beneath the app-names. Before there was.

**Comment by tibbi** [comment]
it has been broken by Android 11, the icons there are invisible as it is no longer possible to scan device for available apps. Just upgrade to 6.16.1, it has been fixed there already.
