### ISSUE TITLE
Address field

### ISSUE THREAD

**Issue by piu130** [SimpleMobileTools/Simple-Contacts#60]
Would be nice to have an address field with Street, City, County, Postalcode and Country.

**Comment by tibbi** [comment]
Address will be added in 3.3.0. But only the structured address in one field, it wont be split to all those smaller fields. I dont want to complicate the app with that.

**Comment by maggu2810** [comment]
Hi @tibbi,
thank you for your app.

Would it be possible to add support for separate fields for the separated address fields (street, postal code, city, ...). I understand that you don't want to complicate the app, but perhaps it would be possible to use one field default and add a setting to enable the separate fields.

The missing separated fields are the most annoying thing of all contact editors I know.
I only know about two apps that allows edit of the separate fields but both are not such nice as yours.

Can you please think about it again?

**Comment by tibbi** [comment]
I was thinking about it already, but I dont want to add it for now. I really see it as an unnecessary complication, even if optional only.

**Comment by maggu2810** [comment]
Perhaps I am doing something wrong.

I add a new contact ("Max Mustermann) and add an address "Musterstraße 17, 12345 Musterstadt".

After that I open the web page "https://www.google.com/contacts/" and open the address field in the web UI. All the information is shown into the street field ("Musterstadt" should be the city and "12345" the postal code).

If I export all the contacts to a CSV file I see the address is placed into the fields:
* Address 1 - Formatted
* Address 1 - Street

But the street itself is only "Musterstraße" and its street number 17.

Perhaps you can tell me the format I have to use to insert the address correctly so "Address 1 - Street", "Address 1 - City" and "Address 1 - Postal Code" are identified correctly.

**Comment by tibbi** [comment]
not much you can do differently in Simple Contacts. Some apps handle whole addresses in 1 field, some have them separated. You just cannot make it work properly across multiple apps and services.
