### ISSUE TITLE
Installing the app enables back Animations

### ISSUE THREAD

**Issue by L-P** [SimpleMobileTools/Simple-Contacts#609]
Hi, when installing Simple Contacts (upgrade or downgrade through F-Droid) the accessibility flag `Remove animations` is disabled.  

Installing the app must not change system settings.

## Repro
1. Disable animations by setting `Remove animations` in the phone accessibility settings.
2. Install the app update through F-Droid (ie. touch the Install button in the Updates section, or downgrade from the app page).

**Comment by tibbi** [comment]
Sorry, but I dont really see how would that be possible. The app has no permission to do anything like that, or it is automatically done by all apps.
