### ISSUE TITLE
Birthday not compatible with Outlook/Google contacts

### ISSUE THREAD

**Issue by piu130** [SimpleMobileTools/Simple-Contacts#61]
When I ave a contact with a birthday, the birthday does not appear in other apps like Outlook or Google Contacts.

**Comment by michaelof** [comment]
works FINE for me with 

Simple-Contacts 3.5.1 from F-Droid
Android 6.0
Contacts from Nextcloud 13.0.1, synced via DavDroid (1.10.1.1-ose, F-Droid)

--> Birthday is synced from Simple-Contacts to Nextcloud correctly, and synced back to Android's contacts, visible as correct "birthday" in Stock/AOSP contact's app.

**Comment by tibbi** [comment]
works fine to me too, maybe there was a glitch previously. Reopen if it is still broken.
