### ISSUE TITLE
All Contacts Disappeared After Calendar Sync

### ISSUE THREAD

**Issue by bigboipete** [SimpleMobileTools/Simple-Contacts#611]
I'm running the latest F-Droid version of Simple Calendar Pro (6.10.3) and Simple Contacts Pro (6.13.0) and just recently set up calendar sync restricted to my local WLAN via Davx5 (3.3.2-ose).
Today I noticed all my local contacts on my phone are gone (or at least not displayed anymore). As there wasn't any notice, that the calendar sync would affect contacts I didn't bother setting it up. I see four options:

1. I misunderstood the syncing mechanism and it's expected behavior, that my setting wants to sync (remotely non-existing) contacts and thus nothing is shown in Simple Contacts Pro anymore.
2. I have not yet found the right switch in the involved Apps Simple Contacts Pro and Davx5 to not sync contacts/only use local contacts on the phone.
3. This is a bug in Simple Contacts Pro (or maybe Davx5), that deletion of contacts occurs by accident.
4. This behaviour is related to issue #579 and has nothing to do with syncing and Davx5.

Maybe someone could support me to sort this out.

I'm running a [Shiftphone 5me](https://shop.shiftphones.com/shift5me.html#product_tabs_description) with Shift OS (AOSP 8.0)

**Comment by tibbi** [comment]
It doesnt really sound like an issue in our app, you must have set up something wrong. Havent you just filtered the contacts out at the top Menu -> Filter?

**Comment by bigboipete** [comment]
No, changing the filter (here: phone and/or device storage) doesn't change anything. Tried it both directions - checked and unchecked.

Btw. it is not obvious in the current UI, if it should be checked or not to see e.g. phone contacts. Does setting the checkmark "filter away" the Phone contacts themselves or filter (aka does not display) everything else? Maybe you could clarify this in the UI.  

Is there actually a technical reason, why the settings of the app doesn't provide a sync toggle, like Simple Calender Pro does? This would be very helpful, because syncing does also affect contacts (as far as I currently understand it...).

**Comment by tibbi** [comment]
contacts work in a different way than the calendar. There is no need for any toggle, Simple Contacts just displays all contacts that can be found on the device. The app doesnt care where do they come from. Everything in the Filter should be checked.

**Comment by bigboipete** [comment]
Wow, that doesn't sound promising: If it's not Simple Contacts related, I guess DAVx5 "un-synced" all my contacts away. At least that's how it looks like to me right now. I'll ask there for clarification, too.
