### ISSUE TITLE
Contact page redesign

### ISSUE THREAD

**Issue by YerinAlexey** [SimpleMobileTools/Simple-Contacts#614]
As per `v6.13.0`, the contact details UI looks a bit smashed. Other problem is sometimes buttons are hard to hit.

I think it should be transformed into something like this:
![mockup](https://user-images.githubusercontent.com/51704055/96350441-866c3080-10be-11eb-9983-c2b49e28bb55.png)

This UI looks a lot cleaner and shows the information in more familiar way.

**Comment by tibbi** [comment]
it will be remade in the future, but Im not yet sure how will it look like. Anyway, I dont want to keep such issues open. Thanks
