### ISSUE TITLE
Inability to remove middle name of contact

### ISSUE THREAD

**Issue by jcstaudt** [SimpleMobileTools/Simple-Contacts#617]
The motivation for this issue is that I had the wrong name for one of my contacts which has a first/middle/last name, and I would like to remove the name entirely such that the phone number appears in my call log rather than an erroneous name. I feel this should work without requiring the user to delete/create the contact, and that this issue is within scope of Simple-Contacts.

* Using Nextcloud, I created a contact with first/middle/last name
* Using DAVx5, I synced the contacts with Simple-Contacts
* Using Simple-Contacts, I removed the first/last name (no middle name option is available)

The name of the contact is replaced with the middle name, without the obvious ability to remove the middle name in the contact edit mode.

**Comment by tibbi** [comment]
you can customize visible contact fields in the app settings -> manage visible contact fields.
