### ISSUE TITLE
Prevent automatical addition of newly added accounts to filter

### ISSUE THREAD

**Issue by alecpetrosky** [SimpleMobileTools/Simple-Contacts#619]
Currently, newly added accounts are automatically added to the filter as included. It would be better to follow this current behaviour only if there's no unselected items (i.e. all address books are included). If there's at least one address book unselected, it means the user wants manual more gradient approach and automatic filter expansion should be avoided. Another option is adding corresponding option into the settings. But in my opinion, the former variant is more intuitive, easier to implement and KISS.

**Comment by tibbi** [comment]
I dont like the idea of hiding contacts by default, I want to keep like like it is now. Thanks
