### ISSUE TITLE
Merging Contacts

### ISSUE THREAD

**Issue by bigboipete** [SimpleMobileTools/Simple-Contacts#620]
Referring to the situation reported in #611, I came across an interesting point. Looking at the AOSP 8.0 built-in contacts app, I found out that there are two entries available for some of the contacts (actually the ones I manually added after the described deletion). In Simple Contacts I only see contact information that was provided by the re-import of an older version of my address book.

Citing from #611:
> Simple Contacts just displays all contacts that can be found on the device.

Now I wonder is this a shortcoming of Simple Contacts to still not see _all_ contacts yet? Or did I just not find the right way to get them displayed in Simple Contacts? And - if it's possible to see two "overlapping" contacts - it would be great to have an option to merge them. Is that possible or could it be implemented?

Thanks in advance for clarifying the situation. I'd really like to have my contacts straightened.

Let me know if you consider the different contact appearance between built-in app and Simple Contacts a bug. I can easily file it seperately.

**Comment by tibbi** [comment]
just open a contact and if it is stored multiple times, you should see multiple contact sources at the bottom of the View Details screen (not the edit one). Maybe your email is listed there multiple times, or some other field?

**Comment by bigboipete** [comment]
@tibbi thanks for the quick reply. But unfortunately there is nothing I could identify as "contact sources". What am I supposed to see, something like a path or kind of a user/account name as source?

In Simple Contacts I only see the contact details like phone number, email, address as usual and the rest is just plain background color to the bottom of the screen without any possibility to scroll somewhere below.

But I guess I also wasn't precise describing the current situation. The set of contact information in both contact apps are equal. But the built-in contacts app asks me which source to edit (without telling which is which), if I select editing. That makes me wonder, where these two sources come from. Simple Contacts just puts it all together and leaves no evidence, that it uses two sources. Or I couldn't find it at least...

Either way so far I'm unable to identify where which piece of information is coming from and how to merge this to have only one contact (source) for each listed person. I would highly appreciate, if you might have some more hints for me.

**Comment by tibbi** [comment]
do you have "Contact source" enabled at the app settings -> manage visible contact fields? In the View Details screen the icon looks like a persons reverse silhouette

**Comment by bigboipete** [comment]
Hi @tibbi sorry, for the delay. I found the icon you are referring to. Attached you'll find a screenshot from one of the contacts with two sources. I wonder if it is expected, that there is one source entry without icon? I still would be interested on how to merge these two contact sources to one?

![SimpleContacts_SourceWithoutIcon](https://user-images.githubusercontent.com/38537584/99117406-ef7b9100-25f5-11eb-9849-8486fece4590.png)

**Comment by tibbi** [comment]
ye, that icon is not related to the contact source, it is just a generic one showing that thats where the list of contact sources starts. You can click on those bottom "Phone"s to open individual contacts and maybe delete one. Be careful not the delete the one with the phone number though. Contact merging isnt currently possible, some way might be added in the future.

**Comment by bigboipete** [comment]
I see. Thanks for summing this up. Then I will do the "merges" manually...
