### ISSUE TITLE
Question: Which VCARD version does Simple-Contacts support?

### ISSUE THREAD

**Issue by michaelof** [SimpleMobileTools/Simple-Contacts#621]
Hi Tibor,

does Simple-Contacts already support V4.0, as specified in RFC 6350 (https://tools.ietf.org/html/rfc6350), for importing?

When exporting from Simple-Contacts, vcards have the
`VERSION:3.0`
property set, no option to select, currently.

Michael

**Comment by tibbi** [comment]
it supports version 3 right now
