### ISSUE TITLE
Feature Request: Protected fields (checkbox)

### ISSUE THREAD

**Issue by Vintic** [SimpleMobileTools/Simple-Contacts#627]
For example I would like to hide, second phone number or email, or note from other apps, but first number to be shown.
And instead of creating same contact but in a private storage, would be perfect to have protected checkbox, like in KeePass.

When it is checked, field will be stored in phone storage.
When it is unchecked, field will be stored in private storage.

**Comment by Vintic** [comment]
For this to be realized, I think, all contacts should be stored both in private and phone storage. 
And on checkbox change, to replace contact from phone storage.

**Comment by tibbi** [comment]
that is way too advanced, dont really expect having such options at contacts. Just create separate private contacts I guess.

**Comment by Vintic** [comment]
> 
> 
> that is way too advanced, dont really expect having such options at contacts. Just create separate private contacts I guess.

So, if any one else will develop this feature, would it be accepted?
Why not just to add label, like "backlog", "hard to implement" .... instead of closing it?

In my optinion all fields should be private, instead of maybe phone numbers, which are used by messengers to interconnect peoples.

**Comment by tibbi** [comment]
I closed it because I dont like having such tasks open, I just dont plan adding it. It is a way too geeky request, but the target audience is the 95% of casual people, not extreme edge cases.
