### ISSUE TITLE
MyContactsContentProvider exported

### ISSUE THREAD

**Issue by kanytu** [SimpleMobileTools/Simple-Contacts#628]
Why is this provider exported, exposing contact information to other applications without contacts permissions? Isn't that a security issue for you? Are users aware of this behaviour?

**Comment by tibbi** [comment]
it is used at sharing the privately stored contacts within our apps suite, if it is enabled in the app settings. Other apps cannot access it.

**Comment by kanytu** [comment]
"Other apps cannot access it."

How come? What checks are in place for that? There is no permission check or signature. If the user enables the setting, all apps will be able to query that content provider.

**Comment by tibbi** [comment]
it just returns no results for other apps

**Comment by kanytu** [comment]
Care to explain where or how are you checking if the app is yours or not? I can't seem to find it.

**Comment by tibbi** [comment]
it is in Simple Commons
