### ISSUE TITLE
Starting voice call to whatsapp contact crashes Contacts

### ISSUE THREAD

**Issue by leaumar** [SimpleMobileTools/Simple-Contacts#630]
Title explains all, really. I'm about to send the crash log through the play store with the link to this issue in the description. I'm assuming that reaches the devs.

Thanks

**Comment by tibbi** [comment]
what app version are you using?

**Comment by leaumar** [comment]
6.13.1 pro

**Comment by tibbi** [comment]
So it always happens, or only at specific contacts?

**Comment by leaumar** [comment]
So far it seems to be on any whatsapp contact

**Comment by tibbi** [comment]
I do get some limited crashlogs, but the error message itself is missing. Anyway, do you have Android 8.1 and Motorola Moto device? That is the only device where it is happening. Dont you have a rooted device, or some hardened privacy features?

**Comment by leaumar** [comment]
Correct on the device. Not rooted, stock rom, no privacy extras. I'll see about getting the exception message myself later.

**Comment by leaumar** [comment]
Sorry it took a while. I read the stacktrace and found that Contacts was missing the phonecall permission. Not sure how that happened, I've had the app for a long time. Granting it solved the problem.

I'd suggest that permissions should be checked/exceptions caught since the app can just request them when needed instead of crashing, but it's probably not something that occurs a lot so maybe not worth the effort.

Anyway, problem solved, thanks for the app :)

**Comment by tibbi** [comment]
so just to be sure, it crashed at clicking on the WhatsApp icon and initiating a call from there?

**Comment by leaumar** [comment]
Yes, when clicking "voice call <number>"

**Comment by tibbi** [comment]
alright, Ill fix it anyway. Thanks
