### ISSUE TITLE
Replace Contrast Icon

### ISSUE THREAD

**Issue by Github-com-foss** [SimpleMobileTools/Simple-Contacts#637]
Pls replace icon,(now) its look like old (gingerbread,ics) change colorful contrast color, dual tone shade or gradient colors. implement in simple (Message,dialer and contacts )

![images](https://user-images.githubusercontent.com/75672019/102580288-5542c780-4124-11eb-97fa-f8f86548eefa.jpeg)
![Screenshot](https://user-images.githubusercontent.com/75672019/102580294-57a52180-4124-11eb-8ecb-add169704579.jpg)

**Comment by tibbi** [comment]
I dont really plan changing it, I like them :) They are all material colors.
