### ISSUE TITLE
Manage Compagny / Job Title / Departement fields when editing a contact 

### ISSUE THREAD

**Issue by alexandrenavarro** [SimpleMobileTools/Simple-Contacts#649]
Manage Compagny / Job Title / Departement fields when editing a contact.

Thank you for the amazing work you made, I just discovered because they are available in f-droid  and I want to have open source apps for some critical apps and you made a fantastic job (I bought all).

**Comment by tibbi** [comment]
you can enable the organization field in the app settings -> manage visible contact fields

**Comment by alexandrenavarro** [comment]
Thanks. Sorry for making this issue.
