### ISSUE TITLE
[FR] Identicons as alternative to letters

### ISSUE THREAD

**Issue by limbusdev** [SimpleMobileTools/Simple-Contacts#650]
Hi. It would be great if we could choose to display identicons instead of the first letter as contact image.

Cheers,
Keep up the great work : )

**Comment by tibbi** [comment]
what is an identicon?

**Comment by limbusdev** [comment]
Its a pretty pixel-art icon generated from the hash of a e.g. contact name. FairEmail uses very nice identicons. Since it's open source too, you could have a look how it's done there. I'll send a screenshot later.

**Comment by limbusdev** [comment]
![signal-2021-01-23-131247](https://user-images.githubusercontent.com/6540152/105577940-ff91b880-5d7c-11eb-8000-1b3d3b7d77c5.jpeg)

**Comment by tibbi** [comment]
ah that looks weird and doesnt fit th eapp style at all, dont really expect having it. Thanks though

**Comment by limbusdev** [comment]
Alright : )
