### ISSUE TITLE
Ignore accents on search

### ISSUE THREAD

**Issue by jEsuSdA** [SimpleMobileTools/Simple-Contacts#653]
I'm a spanish user and, as you can imagine, I have a lot of contacts with names which contains accents, like "Ángel", "Julián", "Papá", etc.

It will be very useful to make accent-non-sensitive the search bar at top, so, when I type "angel" the contact list reflects "Ángel" as available contact.

The same improvement will be fine to simple-dialer.

Thanks!

P.D.: I just make a donation! Thanks a lot for your efforts and for bringing us this amazing apps. ;)

**Comment by tibbi** [comment]
which app version are you using?

**Comment by jEsuSdA** [comment]
Hi @tibbi 

I'm using Verisón 6.13.1 Pro from F-Droid repo.
