### ISSUE TITLE
Search on other than names and numbers

### ISSUE THREAD

**Issue by esprit-libre** [SimpleMobileTools/Simple-Contacts#657]
I used a lot search by company name, but it does not work with Simple Mobile Apps. This would be great if search could include also other fields like company, postal address, etc.

Many thanks for your apps!!

**Comment by tibbi** [comment]
it should already search there, what app version are you using? Do you have company displaying enabled in the app settings?

**Comment by esprit-libre** [comment]
You're right, I just tested with in Simple Contacts (6.14.0) and it works. My problem is the search function in Simple Dialer (5.6.1).
I was thinking that both use the same engine, but visibly not. I transfer my request to Simple Dialer repository.
Thanks
