### ISSUE TITLE
Android 10 on device/sim cant be read

### ISSUE THREAD

**Issue by doobydooby72** [SimpleMobileTools/Simple-Contacts#663]
Hi used your apps for ages now and love them. Just upgraded phone its an oppo with android 10. Prior i was using a phone with android 7.1. On my old phone sim cards would pop up under USIM, now with android 10 only non shared storage and app contacts (eg fb messenger) are available. I personally prefer to use QKSMS in combination with simple dialer and simple contacts which is impossible at the moment. If i have my contact stored in a shared space imported through google contacts simple dialer reads them fine but simple contacts doesnt. If i then import into simple contacts i get duplicated for the shared space as well as private space for simple dialer. If i only import into private space that your apps can access without duplicating in a shared space QKSMS cant read them. This is rather annoying since i love all these and they all worked fine in conjunction prior to this upgrade. Thanks for your efforts, hope this is written appropriately as ive just joined github to find or help in a resolution and is my 1st comment.

**Comment by tibbi** [comment]
Hey, not sure what is your issue now. 
1. If you try creaitng a contact with Simple Contacts, what contact sources do you see? Only Phone storage and the private one? 2. Do you have any contacts stored on your SIM already?
3. What app version are you using at all?

**Comment by doobydooby72** [comment]
I have about 6 or so contacts om the sim card which google contacts can see.
The app versions have been the most recent ones. Always updated via fdroid automatically.
View image for available storage options.
![Screenshot_2021-02-23-17-29-02-45_ed5b588ea0ef6c9a299100fc3989c22d](https://user-images.githubusercontent.com/79504735/108824855-24668f00-75ba-11eb-9c2a-c512cfc0c2bb.jpg)

**Comment by tibbi** [comment]
how about some other Contacts apps, do they see people stored on your SIM card? What Simple Contacts Pro version are you using at all?

**Comment by doobydooby72** [comment]
The app version is 6.14.0
I just tried simpler caller id off the google play store and interestingly it doesnt display the contacts imported by google contacts by default. However when i change a setting under display contacts from the default "all contacts" to "custom" it then displays all imported contacts.

**Comment by doobydooby72** [comment]
Another app off google play called Phone + Contacts and calls doesnt appear to read the imported contacts either. Though in the call log it displays contacts names over each instance.

**Comment by tibbi** [comment]
well it seems to be some device specific issue, hard to say what though. Contact handling under the hood is a mess and there can be many things done differently per device.

**Comment by doobydooby72** [comment]
Would it be possible to add 2 switches under the simple dialer settings to ignore device contacts and or contacts within your own apps privately imported into simple contacts. Could be an alternative solution. Thank you

**Comment by tibbi** [comment]
you can already disable private contact sharing in Simple Contacts Pros app settings. More advanced filter for Simple Dialer is on the roadmap.

**Comment by doobydooby72** [comment]
Look forward to the filter in simple dialer, would be a solution. Thank you

**Comment by tibbi** [comment]
adding filtering in Simple Dialer is a on the roadmap, but this issue got messy and in the end it is related to the dialer
