### ISSUE TITLE
FR: Show calculated current age next to birthday

### ISSUE THREAD

**Issue by JohnVeness** [SimpleMobileTools/Simple-Contacts#667]
It would be useful if the app could calculate someone's current age in years and display it next to the birthday date, when the birth year is known, to save the user having to do mental arithmetic! E.g.:

- 17 Sep 1963 (57 years old)

**Comment by JohnVeness** [comment]
Hi, many thanks for implementing this. Unfortunately it doesn't seem to take notice of the current date when showing the age. I would expect to see an age of 4 when looking at someone born 1 July 2016 at this time of year. Only later in this year would I expect to see age 5.

**Comment by tibbi** [comment]
thats how it works to me, I see 4. Can you send a screenshot?

**Comment by JohnVeness** [comment]
Ah, whoops, sorry, please disregard this! I have completely miscalculated! (There goes my credibility!)
