### ISSUE TITLE
Phone contacts are missing.

### ISSUE THREAD

**Issue by cryptono** [SimpleMobileTools/Simple-Contacts#673]
Using the current version of Simple Contacts, many contacts are not shown for me (using a synced account).
Out of 649 contacts, only 632 are shown (based on the information of the counter).
For your other app "Dialer", it only shows 474.
I don't have any idea what the reason for that could be.

**Comment by tibbi** [comment]
What app version are you using? Dont you have some contact source filtered out at the top Menu -> FIlter?

**Comment by cryptono** [comment]
@tibbi All filters are activated, doesn't change the number of contacts and still not the number that it's supposed to have.. v 6.14.2 Pro.
Dialer: v5.6.2.

**Comment by tibbi** [comment]
where did you get the number 649 from? Dont you have some duplicates there?

**Comment by cryptono** [comment]
@tibbi 
a) contacts that have the same name, but different content (or real duplicates that have the same content) are not being shown. 
b) (probably) contacts who don't have any name but a number are not shown.
Now it's displaying the same amount of contacts. Yet I really think it should show all contacts, otherwise how would you remove duplicates? And what about people who have the first name in your contact list? 

For dialer, it's not showing the contacts without a phone number which totally makes sense. 

Thanks for the help.
