### ISSUE TITLE
How to Locally test translation before submitting

### ISSUE THREAD

**Issue by MosheSidis** [SimpleMobileTools/Simple-Contacts#674]
I started Translating the Simple-Contacts app to Hebrew.
I used the file:
Simple-Contacts/app/src/main/res/values-hi-rIN/strings.xml

How can I check it **locally on my device** before submitting the changes/translation ?

**Comment by tibbi** [comment]
are you a developer, or not? You cannot really do it without using Android Studio

**Comment by MosheSidis** [comment]
No.
I simply wanted to help translating it to Heb

**Comment by tibbi** [comment]
there is no way of testing it, just submit your texts and you will see the result in the app. Or I can send you a test version with your updates if you want
