### ISSUE TITLE
Cannot create/import Contacts to Default or SIM Storage

### ISSUE THREAD

**Issue by fossfann** [SimpleMobileTools/Simple-Contacts#675]
Hi,

I cannot import/create the contacts to SIM or default storage anymore. There was any reason in older versions. I don't remember which was that but i am pretty sure i could create/import contacts from .vcf file to SIM card. When i tried to create/import contacts i can only see phone storage in the source field.

App version: 6.14.3
Phone: MIUI 12 Xiaomi Not rooted

Thanks in advance.

**Comment by tibbi** [comment]
if you try creating a new contact manually, do you see SIM or default storage as an option? Do you have any contacts store at those places at all?

**Comment by fossfann** [comment]
When i try to create new contact i just see phone storage (not visibly by other apps) option. Also when i try to import contacts from .vcf file again i just see only phone storage. I have contacts on the vcf file.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tibbi** [comment]
Try creating a contact into your default phone storage or SIM card with some other app, then it should show up here too

**Comment by fossfann** [comment]
I am sure there was any problem with older versions. I could create a new contact to SIM storage with Simple Contacts. Do i have to use another contacts app for this issue?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tibbi** [comment]
just to test if creating a new contact into those sources will unstuck it.

**Comment by fossfann** [comment]
when tried to create a new contact there is no default or SIM option to choose in Simple Contacts

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tibbi** [comment]
I mean creating the first contact in some other app, not Simple Contacts

**Comment by fossfann** [comment]
If we need to create contacts with other apps then no need simple contacts. thanks. you can close the ticket

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
