### ISSUE TITLE
Cannot make a call from Contacts in 6.14.3

### ISSUE THREAD

**Issue by fossfann** [SimpleMobileTools/Simple-Contacts#676]
Hi,

When i tried to make a call from contacts the calling screen is working on the background. I must tap the call from the notification shade to see calling screen.

Android 11 MIUI 12

Thanks

**Comment by tibbi** [comment]
what app is handling the call itself? Is it Simple Dialer, or some other one?

**Comment by fossfann** [comment]
Simple Dialer

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tibbi** [comment]
so what exactly happens at clicking the Call button? Only a notification appears, or you see some screen blinking and disappearing? Do you maybe have multiple SIM cards, or anything special?

**Comment by fossfann** [comment]
when i clicked call button call screen is disappearing completely and it is calling the person on background. i can hear the voices but no app is visible

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tibbi** [comment]
Simple Contacts isnt handling calls, it is an issue of Simple Dialer
