### ISSUE TITLE
SIM card contacts are not automatically loaded and disappear after restarting phone

### ISSUE THREAD

**Issue by Dani3I** [SimpleMobileTools/Simple-Contacts#677]
After starting the application, contacts from SIM are not displayed. Only after launching the contacts application, which is installed on the device by the manufacturer, a message appears (which looks similar to the one when "we want to become a developer") that "loading contacts from the SIM card". And only after this message, SIM contacts appear in "Simple Contacts", as well as the option of adding and filtering contacts from SIM.
For some reason, you will need to do this again after a system restart.

Before starting the manufacturer's "contacts" application:
![before](https://user-images.githubusercontent.com/34142462/115138806-a4472d80-a02e-11eb-8cf8-8ee6af943794.png)

After starting the manufacturer's "contacts" application:
![after](https://user-images.githubusercontent.com/34142462/115138816-bc1eb180-a02e-11eb-80aa-4f3304d926ea.png)

**Comment by tibbi** [comment]
what app version are you using?

**Comment by Dani3I** [comment]
6.14.3 Pro
from F-Droid

**Comment by tibbi** [comment]
does it work well in other Contacts app? I mean some downloaded one, not the preinstalled.
