### ISSUE TITLE
"shown contact fields" only in "edit mode" visible

### ISSUE THREAD

**Issue by hugofant** [SimpleMobileTools/Simple-Contacts#679]
Hi,
when activating for example the field "nickname" (in settings/manage shown contact fields) it's shown in "edit mode" correctly, but not, when contact is only viewed...and search mode is also ignoring it. 

i'm actually using version 6.14.3 Pro

**Comment by tibbi** [comment]
Well if the field is not filled out, it isn't shown at View.

**Comment by hugofant** [comment]
of course it was filled.....closing without asking/verifying - really great reaction.....will have a look for another dialer

**Comment by mibe** [comment]
I also encountered both issues (nickname not shown and not found) yesterday. I made screenshots from the issue in ViewActivity and EditActivity.
What do you think @tibbi, should I open new issue(s) or should we revive this issue by posting the screenshots here?

**Comment by tibbi** [comment]
ye, open a new issue

**Comment by mibe** [comment]
Done with #763 & #764.
