### ISSUE TITLE
Can't Import contacts using a vcf file

### ISSUE THREAD

**Issue by ze0ss** [SimpleMobileTools/Simple-Contacts#682]
Please help urgently.
I've been using this app for almost a year now, I had no issues whatsoever until a week ago, 
I cannot import contacts from the vcf file of my account from contacts.google.com.
The app gives an error:
"`android.content.OperationApplicationException`: App op not allowed"

Device: RMX2061 (Realme 6 pro)
Android 11, Rui 2.0
Simple Contacts: 6.14.3 from F-Droid

I tried everything I could and I am exhausted, so no more trying from me, my only hope is you, beloved dev.
Please reply asap.
Thanks

Screenshot:

![20210514_212425.jpg](https://user-images.githubusercontent.com/56572179/118296584-c5e6e800-b4fa-11eb-98dd-4c6dd4f297d1.jpg)

**Comment by tibbi** [comment]
Where are you trying to import the contacts? Does the target contact source at importing say your email, Phone, SIM or something else?

**Comment by ze0ss** [comment]
Phone
And it can't detect the Gmail account for some reason.
No contact apps are detecting the account.
Is this a known issue.in Android 11?
I installed an older version of this app and I can import the vcf, but it's phone storage only, so apps like whatsapp can't see the contacts, please help.

**Comment by tibbi** [comment]
such issues are usually device specific, there are many things that can be done differently by devices. Can you import the file well in other apps? Seems like it isnt an issue on our side.

**Comment by ze0ss** [comment]
Nope I can't import it in any other apps, and it's android 11 issue maybe?
What do you suggest I do?
Google account issue, how to make apps read the account.
The account exists on the device, but no contact app reads the account.
It's not a device issue, app issue.

**Comment by tibbi** [comment]
Im not sure, these issues are device specific, we cannot really help with it.

**Comment by ze0ss** [comment]
don't close I'm in serious trouble 😭

**Comment by tibbi** [comment]
try googling around with specifying your device, it apparently isnt an issue on our side
