### ISSUE TITLE
Order of characters in quick scroller different than Android

### ISSUE THREAD

**Issue by Gitoffthelawn** [SimpleMobileTools/Simple-Contacts#683]
The order of characters in the quick scroller is different in Simple Contacts as compared to Android and all the other dialers I've tried.

In Simple Contacts, special characters are all listed at the bottom of the scroller, instead of the top, like Android.  For example, the plus sign and double-chevrons.

I'm hoping this is an easy fix.

**Comment by tibbi** [comment]
it is not an issue of the scroller, but the sorting of specific contacts.

**Comment by Gitoffthelawn** [comment]
Okay, do you want to fix the sorting of specific contacts?

**Comment by tibbi** [comment]
you should create a separate issue for that, ideally with some sample names too for easy reproducing
