### ISSUE TITLE
Bug(?): Silent ringtone makes a chime sound instead; Can't set ringtone to "None"

### ISSUE THREAD

**Issue by e-t-l** [SimpleMobileTools/Simple-Contacts#684]
I want just one contact in my phone to ring silently (i.e. only vibrate), but when I try to set the ringtone for the contact to "none" in Simple Contacts, it keeps reverting to my default ringtone.

So I downloaded an mp3 of pure silence ([Github source](https://github.com/anars/blank-audio/blob/master/10-seconds-of-silence.mp3)), played it in an audio player to confirm it worked, then set that as the contact's ringtone. 

Oddly, when I get a call from that contact, instead of silence, it players a chime sound approximately once every 3 seconds (the silent mp3 I used is 10 seconds long, so it appears it's being ignored entirely). I don't think this is the phone's doing, because: a) I used to be able to set the ringtone to none when using the default Google contacts app, before I switched to Simple Contacts, and b) I looked through all the default sounds in the phone's Sounds app and none of them match the chime I'm hearing.

Is this behavior due to something in Simple Contacts, and can it be changed?

### Steps to replicate
1. Install Simple contacts
2. Download 10-seconds-of-silence or a similar audio file containing no sound.
3. Set that file as a contact's ringtone in Simple Contacts.
4. Receive a phone call from that contact. 

Note: I'm running Android 11 on a Pixel 3, and while I use Simple Contacts instead of Google Contacts, I still use the default Google/Android phone dialer. I do not know if any of these factors are required to replicate my experience.

**Comment by e-t-l** [comment]
The main issue here, imo, is that in Simple Contacts, you cannot set a ringtone to "None." If you go to the ringtone field, select "My Sounds," and then select "None," then save it, the contact will continue to be set to the Default Ringtone. 

I don't know why a silent mp3 would result in a chime being played, but the simplest solution would be to allow users to set the sound "None" as a contact ringtone.

(If anyone has the same use case as I, the workaround is to go into the default _Android_ Contacts app and set the contact's ringtone to None.

**Comment by tibbi** [comment]
ringtone customization is handled by redirecting to the system on Android 8+, doesnt the redirection happen as you click on ringtone for customization?

**Comment by e-t-l** [comment]
> doesnt the redirection happen as you click on ringtone for customization?
It does, however if you select "My Sounds" and then "None," this selection does not seem to be passed back to Simple Contacts.

**Comment by tibbi** [comment]
will be fixed in 6.16.3
