### ISSUE TITLE
Contacts not appearing on Signal

### ISSUE THREAD

**Issue by marcopavanello** [SimpleMobileTools/Simple-Contacts#685]
I'm encountering an issue on GrapheneOS where the contacts aren't actually visible to the Signal app, but they are in the Simple SMS Messenger app.
Basically I had it working before, when I first added the contacts and then installed the Signal app, but now I decided to remove all my contacts and import them from a VCF file, and now it seems like Signal doesn't recognize all the contacts anymore.

**Comment by tibbi** [comment]
What contact source are you saving the contact to? I mean the last field at the contact details screen. Does it say your email, Phone, SIM or something like that?

**Comment by marcopavanello** [comment]
It is "Phone storage (not visible by other apps)" and it appears to be the only available option...

**Comment by tibbi** [comment]
Well that is quite self-explanatory. I don't know how to make other contact sources appear, GrapheneOS has many things limited.

**Comment by marcopavanello** [comment]
Ok so it's a GrapheneOS issue, it's strange that your Simple SMS app accesses the contacts though..
Thank you.

**Comment by tibbi** [comment]
because it is within our suite. Simple Contacts has a setting for "Show private contacts to Simple Dialer, Messenger and Calendar", so it can be disabled too
