### ISSUE TITLE
Make default storage for new contacts configurable

### ISSUE THREAD

**Issue by wolfisberg** [SimpleMobileTools/Simple-Contacts#688]
It would be awesome if the default storage provider/address book for creating new contacts could be configurable. I feel like a lot of people use this app to avoid google and at least for me, the default address book for new contacts is set to the google account.

**Comment by tibbi** [comment]
The default is always the last used one. So just store one contact somewhere else and it will be set as the default at the next one.

**Comment by wolfisberg** [comment]
Awesome, that works for me. Thank you.
