### ISSUE TITLE
It can't export images (6.15.0)

### ISSUE THREAD

**Issue by Pranab009** [SimpleMobileTools/Simple-Contacts#692]
It can't export images in backups.
Another thing, if you backup through Google contact (with images)  and when you open or import through Simple contact app it can't recognize contact images.

**Comment by tibbi** [comment]
Where are the contacts stored/imported to? Are you using the "Phone storage (not visible by other apps)" contact source?

**Comment by Pranab009** [comment]
I try it both from internal and external storage it backup contact without images.(Google contact backup)

**Comment by tibbi** [comment]
should be working already
