### ISSUE TITLE
Feature: Restrict to entries from a single source

### ISSUE THREAD

**Issue by sciurius** [SimpleMobileTools/Simple-Contacts#695]
By default Contacts shows entries from several sources: the phone list, external phone book (CardDAV), WhatsApp, Telegram, and so on. Often I feel the need to restrict the app to a single source only.

Rationale: When I have Ludwig (firstname) van Beethoven (surname) in my contact list, and he joins WhatsApp, I get another, incompatible entry Ludwig (first) van (middle) Beethoven (surname). I would like to ignore all these by sticking to a single source (CardDAV) only/

**Comment by tibbi** [comment]
just use the top Menu -> Filter for that
