### ISSUE TITLE
[Bug] New contacts now showing up right away

### ISSUE THREAD

**Issue by TehPsychedelic** [SimpleMobileTools/Simple-Contacts#698]
This is a bit of a weird bug, but it goes like this:

1. Press the "search" button top-right as if you were doing a search
2. Create a new contact via the plus (+) button bottom-right, and save.

As you can see, the new contact doesn't show up at all (Step 1 is crucial).
You need to close and re-open the app to see it was created.

It may seem as if in "search mode" adding a contact doesn't trigger the "refresh event".

The annoying thing overall about this bug is that since you don't get any visual clue of what happened you may continue to create duplicate contacts over and over since they never show up.

**Comment by tibbi** [comment]
should be fixed in 6.15.1
