### ISSUE TITLE
Android 11 : can't see regular contact lists

### ISSUE THREAD

**Issue by moonshaadow** [SimpleMobileTools/Simple-Contacts#700]
Hi there .

Simple-Contacts can't see regular contact lists as "SIM" or "Phone". It displays only "Phone storage (not visible by other apps)".
Permissions are correctly set.
I can get "Signal" list (from Signal app).
I can import a .vcf  only in "Phone storage (not visible by other apps)" list.

I have not this issue with Simple-Dialer, which displays phone list by default and "Phone storage..." list. 

Version : 6.15.0 Pro (from F-Droid)
I didnt' have this issue with another (old)  version of android.
I can correctly see phone list with another non-stock app.

**Comment by tibbi** [comment]
if you disable Signal, does it work?

**Comment by moonshaadow** [comment]
No, unfortunately.

**Comment by moonshaadow** [comment]
Issue seems to be similar to #675 , #685 ...

**Comment by moonshaadow** [comment]
Hi there.
Some news about this issue :

- Simple-Contacts is not the only app that cannot see SIM contacts, but with others apps I can at least import from SIM. The issue is not on another phone, so the issue might be related with my device (motorola G30) or Android 11.

- I can finally see Phone contact list in Simple-Contacts, but only after installing another contact app (Contacts from LineageOS). This list is named "DEVICE" instead of "PHONE" in Simple-Contacts. It seems that S-C cannot access to Phone list before another app had accessed it or if the list is empty. I encounter this issue only with my motorola G30 - Android 11 device.

Expected behaviour : Like with others devices, S-C should be able to access and manage PHONE list and SIM list.

**Comment by moonshaadow** [comment]
Hi there!
No news about this?
