### ISSUE TITLE
Wrong contact search

### ISSUE THREAD

**Issue by tikitaka007** [SimpleMobileTools/Simple-Contacts#711]
Hello,

The Contacts App shows contacts that have nothing to do with the searched contact name.

Example:

Action: search contact text "ing".
Result: shows contacts that contain the searched text and others THAT DO NOT CONTAIN IT.

Try adding a new contact with the following data:

Contact name: Test
Phone number: 464

Search contact: ing or i

Did you find the contact Test?

I have the impression that it has to do with the phone number containing 64.

Everything comes that when I receive sms it shows an incorrect contact.

I have cleared cache, uninstalled and reinstalled... and it doesn't matter where I save the contacts.

App Contacts: 6.15.1
App SMS Messaging: 5.10.0
App Dialer: 5.8.0

Android 10 Xiaomi Redmi.

Best regards.

**Comment by tibbi** [comment]
Search searches within all fields, not just the name. And ye, it also converts letters to numbers. Will see if it needs change in the future, for now it is the expected behaviour.

**Comment by tikitaka007** [comment]
Hi tibbi, I already knew that the search is done in all fields, what I didn't know was that when searching it also converts letters into numbers, what happens is that this behavior makes me receive SMS from my bank "Ing" and shows a different contact that has nothing to do. That's why when I search in contacts "ing" it shows me contacts without the content "ing", none of those contacts contains "ing" in any of its fields.

Thanks for developing free software, your programs are very useful.

Best regards.
