### ISSUE TITLE
Save birthdays to all linked contacts

### ISSUE THREAD

**Issue by benwaffle** [SimpleMobileTools/Simple-Contacts#713]
I've been adding birthdays to all of my contacts, but I just realized that it was getting saved sometimes to the Signal contact, or the WhatsApp contact, instead of the Nextcloud address book. I'm not sure what the best solution is, but I want all birthdays to go to Nextcloud.

**Comment by tibbi** [comment]
you have to edit the proper contact instance, you can see at the bottom field of the Edit screen which one are you modifying.

**Comment by benwaffle** [comment]
I think it should be more intuitive, because this is an easy mistake to make. Some options:

- Edit the Nextcloud / cloud contact by default. Not sure how the default is picked right now, but it doesn't seem to pick a good one for me
- Make the default a setting.
- Apply edits to all instances
- Make the currently edited contact instance clearer. It just looks like another field at the bottom of the page right now, so it's easy to miss.

**Comment by tibbi** [comment]
well, contact handling on Android under the hood is a ridiculous mess, I want to keep it as it is now

**Comment by tibbi** [comment]
it is most likely the first contact with the given name, the lowest id
