### ISSUE TITLE
No dialer seen in the app whereas F-Droid page lists "directly call phone numbers" permission

### ISSUE THREAD

**Issue by alex-ie** [SimpleMobileTools/Simple-Contacts#715]
There was an issue with dialing (closed):
 Dialer is without any effect #386 

Now I do not see a dialer in the app. F-droid page https://f-droid.org/en/packages/com.simplemobiletools.contacts.pro/ says:
"directly call phone numbers" Allows the app to call phone numbers without your intervention. , however,  from comparing manifests of this app with Simple Dialer (I wrote small apps some years ago myself, but things might have changed, I spend today only couple of minutes reading https://developer.android.com/guide/topics/connectivity/telecom/selfManaged) I guess you dropped that feature from Contacts and expect it to use Dialer, right? If so, please make sure F-Droid page get fixed. I don't know how they populate info about permissions of the build, seems incorrect that time.

**Comment by tibbi** [comment]
that permission is needed for initialting outgoing calls, even if Simple Contacts itself doesnt handle the call. If you dont grant that permission, some Dialer/Phone app will only dial the number and you have to press the Call button yourself

**Comment by alex-ie** [comment]
Not sure if closed issues get attention, still I'll try before creating another one (and for other app). Simple Dialer has "MANAGE_OWN_CALLS" in manifest (which Contacts does not have) which I see neither on F-Droid not in my phone to grant. Why is that? 
Also when attempting to call, it asks to make it default and do not call if that is not granted. Why don't I have option to choose dialer app every time if I want to? Is it Android "standard" way or the way Simple Dialer programmed, then why?
TIA

**Comment by tibbi** [comment]
That permission is used only at default Phone apps I guess, only those can initiate calls. It works differently than some default video player or so.

**Comment by alex-ie** [comment]
@tibbi, that permission ("MANAGE_OWN_CALLS") is in Manifest of your Simple Dialer. I want to understand whether I can make calls with Simple Dialer w/out making it default app for calls... TIA

**Comment by tibbi** [comment]
no, you cannot. It is a system requirement, only default Phone apps can do it.
