### ISSUE TITLE
Setting for generatig groups from sources

### ISSUE THREAD

**Issue by defini-tiv** [SimpleMobileTools/Simple-Contacts#717]
There are already requests that go in this direction. But i think nobody propused this(in my opinion simple an elegant) solution:

- Make a setting which allows people who want to sync their contacts e.g. over nextcloud to generate groups automaticly for every contact source and assign them accprdingly.

It could look like this:

**Groups:**

- Local Storage
- nextcloud.example.com/work
- nextcloud.example.com/family

**Comment by tibbi** [comment]
we cannot create any contact sources, they should be created by the system

**Comment by defini-tiv** [comment]
@tibbi thats not what i meant, maybe i expained it wrong.
I proposed a setting, for having the app making groups for every already existing source.
In case i have a "work" and a "family" carddav adress book, the app would show me a family and a work group with the contacts from the corresponding source.

**Comment by tibbi** [comment]
that isnt on the roamap, dont really expect having it

**Comment by defini-tiv** [comment]
I understand.
Could you still reopen the issue?
It seems you dont want to invest time in it, but would not rule out such feature if anybothy else would do so.

**Comment by tibbi** [comment]
not really, I dont want to keep such issues open, when I know that I dont want this feature
