### ISSUE TITLE
Question, probably no bug: HowTo reset dialer app selection?

### ISSUE THREAD

**Issue by michaelof** [SimpleMobileTools/Simple-Contacts#718]
Hi Tibbi and all!

For a very long time, when clicking on a contact's phone #, SimpleContacts / Android (?) asked me, which dialer/app should be used, stock Android phone app or Linphone VoIP app, in my case. Options, as usual, "once" or "always". 

I've selected always "once", to be able to select wanted app in future. Except one time, yesterday, without wearing my glasses,
pressed "always", unfortunately :)

NO IDEA how to reset, tried to reset app defaults for Simple-Contacts, Linphone, stock "phone" app. Tried to set "default phone app" in Android settings, only stock phone available for selection. Whatever I've tried, SimpleContacts still now passed the phone # directly to the stock phone app, which dials immediately. No chance to dial via Linphone anymore.
Strange, as e.g. a "tel:...." link on a website, used by Firefox for Android, asks me as wanted which dialing app should be used.
Any hints would be great :)

SC v6.15.1Pro (F-Droid), Android 10 latest sec. patches, Nokia 7.2

Thanks,
Michael

**Comment by tibbi** [comment]
just find the default app in your device settings and do a "Clear defaults" on it.
