### ISSUE TITLE
Supporting more/all(?) contact fields

### ISSUE THREAD

**Issue by just-Nob** [SimpleMobileTools/Simple-Contacts#72]
As mentioned  at issues #60 & #68 (as well as in a comment at atissue #58), Simple Contacts doesn't support much fields up to now.

Art the moment, I'm using the app "Contact Editor free" (which doesn't seem to bee available in the App Store anymore - today, I was only able to find the paid version "Contact Editor Pro" there), which has pretty much fields on the one hand, but other disadvantages.
If you like to have a look, I'd share the APK, because it's free and licenced under the Apache Licence 2.0.

Anyway, if Simple Contacts supported all fields (or even the most common ones, like "Contacts Editor free" does), it would be a really great tool for covering my needs. :grinning: :wink:

**Comment by tibbi** [comment]
I will be adding more fields over time, so Ill close this duplicate issue. I have some contact apps that support more fields, so theres plenty of examples. Thanks
