### ISSUE TITLE
Problems with the default storage

### ISSUE THREAD

**Issue by ibex107** [SimpleMobileTools/Simple-Contacts#720]
I have quite a few problems with storing contacts in the default storage.

- First of all I don't think it should be called default but rather internal storage or something and Phone storage (which is currently the one that is not seen by other apps) should be called something like private contacts or something else. The point is it needs a better name for a better understanding.
- Secondly when I try to import contacts into default storage I am not able to import them. I can import them into USIM and Phone Storage but not default. There is not even an option in the drop-down menu to select default. When I try default I get an error message saying: **An error occurred: java.lang.IllegalArgumentException: Must specify both or neither of ACCOUNT _NAME and ACCOUNT_TYPE; URI: conetnt: //com.android.contacts/raw_contacts, calling user: com.simplemobiletools.contacts.pro, calling package:com.simplemobiletools.contacts.pro**.

The only way for me right now to have contacts stored in the default storage is to donwload Google Contacts which I really don't like and import them from there or import them into USIM which I don't think is a good idea either.

**Comment by tibbi** [comment]
You mean that it is called "default"? That is the name given by your device, not us. What app version are you using at all?

**Comment by ibex107** [comment]
![IMG_20211004_170433](https://user-images.githubusercontent.com/91543573/135875973-8145b2a0-baa0-4966-8861-1cc1b290a477.jpg)
![Screenshot_2021-10-04-17-01-25-597_com simplemobiletools contacts pro](https://user-images.githubusercontent.com/91543573/135875978-cc5eae47-5167-4384-af40-beca9c75193e.jpg)
![Screenshot_2021-10-04-08-06-06-897_com simplemobiletools contacts pro](https://user-images.githubusercontent.com/91543573/135875981-c60fbd58-48d9-4426-b94b-f2912ace3b50.jpg)
![Screenshot_2021-10-04-08-01-20-519_com simplemobiletools contacts pro](https://user-images.githubusercontent.com/91543573/135875985-dda36210-4fa4-46e9-8b1c-3b1e37f3e744.jpg)

**Comment by ibex107** [comment]
I thought that default was the name of the local storage option.

**Comment by tibbi** [comment]
sure, just use the "Phone storage (not visible by other apps)"

**Comment by tibbi** [comment]
what device are you using at all?
