### ISSUE TITLE
Vcf files containing UTF8 characters won't be imported/exported properly

### ISSUE THREAD

**Issue by nulledone** [SimpleMobileTools/Simple-Contacts#73]
Normally when you export contacts from other apps name lines including utf8 chars usually appear like this
>  FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:=52=64=63=52=95=35=C7

But when simple contacts export it is complete plain text. And the output file can't properly be imported even with simple contacts app.
Also simple contacts won't read the example provided above either

**Comment by tibbi** [comment]
What app version do you have? It should be handled properly already. However I ignore the FN field completely, parsing just the "N" one. Can you tell an example of a character that is exported as plain text even tho it shouldnt be? Thanks

**Comment by nulledone** [comment]
Version is 3.1.3

There is no problem in importing vcf created by Simple Contacts, but when I im

port a vcf created by stock Contacts app, contact names including UTF-8 chars imported as number only, this is caused by the example above, your app doesn't read the 'CHARSET=UTF-8;ENCODING=...' I have provided example of a VCF exported by my stock contacts app.


[utf8-sample-stock.zip](https://github.com/SimpleMobileTools/Simple-Contacts/files/1716923/utf8-sample-stock.zip)

Try to import it, if it succeeds you will see the name full of 'ş's. But it will probably import empty. Try with another contact app to confirm.

By the way awesome job doing 'Simple Mobile Apps'.

**Comment by tibbi** [comment]
exporting/importing has been rewritten from scratch, retest with 4.4.0 please.
