### ISSUE TITLE
Added New contact does not inserted until we close and reopen the Simple Contact app

### ISSUE THREAD

**Issue by rockstar96969696** [SimpleMobileTools/Simple-Contacts#74]
#### Expected behavior
- We can add a new contact to the Simple-Contact app. When we add a new contact and click on **Done** then, it should be added to our contacts list after a few seconds of processing. At most, it takes 1 or 2 minutes. And the new contact will show if we search for that without closing the App.

#### Actual behavior
- Today I add a new contact I put a name and number and add it. It shows an inserting dialogue which is good. I didn't close the app and search for the same contact after a few seconds it didn't found. I tried again after a few minutes I didn't close the app, still, it does not found in my contact list. Then I close the app and open it again then the new contact was found in my contact list. The new contact does not found in contact list until we close and reopen the App.

#### How to reproduce
- Install Simple Contacts App Version 3.2.0
Google Play Store [Download Link](https://play.google.com/store/apps/details?id=com.simplemobiletools.contacts&hl=en)
- Add a new contact and don't close the app 
![IMG-20180209-WA0040.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518201174/kwpar7h7xkhy6kimqui9.jpg)
- Give it a name and any number and click on done as shown in this screenshot.(Be sure that you didn't close or minimize the app after add new contact)

![IMG-20180209-WA0041.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518201412/qd1a3wgj2lujhkanypal.jpg)
- Now search for the contact you added, the contact was not found until you close and reopen the Simple Contact app
![IMG-20180209-WA0042.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518201738/ayinow4bkhd8j4lxhbsl.jpg)
* Operating system: Android Naught  7.0
*  Simple Contacts: Version 3.2.0
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@faisalamin/bug-in-simple-contacts">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tibbi** [comment]
Hey, do you see the contact on the list without using search? To what contact source are you storing the contact? I mean the last field at the contact creation screen.

**Comment by tibbi** [comment]
apparently it was happening at first launch, when granting permissions. It will be fixed in the next version.
