### ISSUE TITLE
Contacts security like with Open Contacts

### ISSUE THREAD

**Issue by Siltaar** [SimpleMobileTools/Simple-Contacts#752]
Hi,

I'm a fan user of Open Contacts : https://gitlab.com/sultanahamer/OpenContacts

It features:
- app-internal only contacts
- display-over other apps for contact name when a call incomes
- and automatic encrypted zip exports

It's great but its limitation is about handling contact names for SMS apps (ex: Silence app can't read a contact name in Open Contacts).

With Simple-Contacts associated to Simple-SMS Messenger, it exists a possibility to achieve what Open Contacts can't do alone.

I personally prefer using Open Contacts instead of stock Contacts apps because it might avoid unwanted leaks by spyware (even authority operated ones during lawfull street demonstrations or right after) targeted to the default option.

Still, Simple Contacts and Open Contacts are sister projects that might learn from each-other.

With regard,

**Comment by Aga-C** [comment]
> app-internal only contacts

Simple Contacts already has it. It can store contacts in "Phone storage (not visible by other apps)". Also, it allows accessing contacts for Simple SMS Messenger, Simple Dialer and Simple Calendar, but no other apps. So if you'd be using a full bundle of Simple apps, you don't need to have a display-over.

**Comment by Siltaar** [comment]
Great, so this all-in-one installer idea is even more meaningful : https://github.com/SimpleMobileTools/General-Discussion/issues/172

I'll have to check Simple Contact export feature (and migrate, I can't dream of a ciphering SMS feature in Simple SMS Messenger… like in Silence).

(Just for the record, Open Contacts also features a dialer).
