### ISSUE TITLE
Changing Ringtone

### ISSUE THREAD

**Issue by GithubContributor832** [SimpleMobileTools/Simple-Contacts#756]
After changing the ringtone for a selected contact it becomes changeable via contact view without entering into edit mode which is fine. If I change to none it says null instead of none; I have to go into edit mode then click none then save to get it to say none which is the problem. Also if I click default ringtone it does change to proper ringtone but leaves out default like it says with a freshly created contact. This then leaves changing ringtone visible via contact view to change. I want it not visible via contact view like a freshly created contact saying default then ringtone. Also the bolded circle doesn't show when on none or default ringtone option even though enabled. Small bugs and hope not bothering. Only trying to help better your product.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by GithubContributor832** [comment]
Latest.

**Comment by tibbi** [comment]
which is that? I mean the number at the bottom of the About section.

**Comment by GithubContributor832** [comment]
6.16.3 Pro
