### ISSUE TITLE
Contact photos with low resolution

### ISSUE THREAD

**Issue by marcelscode** [SimpleMobileTools/Simple-Contacts#758]
I am using version 6.16.3.
There are two problems:
1. When setting a new photo for a contact, still the old one is shown in simple contacts until I clear the app's cache.
2. When setting a new photo, its resolution is lowered way too much. It looks fine in the contact overview, but when showing the photo in the contact details it looks ugly as it is low resolution.

Both problems do not appear with other apps. Photos changed in simple contacts appear immediately in other contact apps. Photos added in other contacts apps result in contact photos with nice resolution even in simple contacts. Contact photos changed/added in simple contacts have also low resolution in other apps.

**Comment by tibbi** [comment]
report the issues one by one please, they cannot be managed like this
