### ISSUE TITLE
Show nickname in details view

### ISSUE THREAD

**Issue by mibe** [SimpleMobileTools/Simple-Contacts#763]
It would be nice if the nickname of a contact would be shown in the contact details.

Version: 6.16.3 Pro on Android 10
Steps to reproduce:
1. Make sure that the nickname field is enabled in settings/manage shown contact fields.
2. Add a contact with first-, last- and nickname, just like so:
![Screenshot_20211229-022344](https://user-images.githubusercontent.com/573529/147709395-6d2daba7-8183-4318-a272-c9e436c83c0c.png)
3. After saving click on the new contact to show its details. The nickname is not displayed:
![Screenshot_20211229-022335](https://user-images.githubusercontent.com/573529/147709468-1e0c643e-f332-410a-8f4e-59b6691d3a49.png)

If I may suggest a design, I'd like the nickname displayed in parenthesis, below the first- and lastname. Basically like the groups, they are also below each other.

**Comment by tibbi** [comment]
will be added in 6.17.0

**Comment by mibe** [comment]
Thanks!
