### ISSUE TITLE
Deleting contacts error: Unknown authority com.android.contacts

### ISSUE THREAD

**Issue by ThiloteE** [SimpleMobileTools/Simple-Contacts#765]
Version 6.16.3 Pro (From F-Droid) on Huawei P20 Pro;
Android 10,
EMUI 10.0.0 Build number 10.0.0.197(C432E8R1P3)

**How to reproduce:**

1. Select all contacts (in my case ~300)
2. Delete them all

**What happens:**

- All contacts do get deleted
- This error message pops up:
   ```
   Es ist ein Fehler aufgetreten:
   java.lang.illegalArgumentException:
   Unknown authority com.android.contacts
   ```
   
**Additional info:**

- stored within phone storage (not visible by other apps)
- I removed a few android programs via adb and if i remember correctly, i removed the native android contacts app as well.
- Simple-Contacts has the following permissions: contacts; phone

**Comment by tibbi** [comment]
you are not supposed to remove system components, of course it will break your device
