### ISSUE TITLE
Import contacts error: unknown authority com.android.contacts

### ISSUE THREAD

**Issue by ThiloteE** [SimpleMobileTools/Simple-Contacts#766]
Version 6.16.3 Pro (From F-Droid) on Huawei P20 Pro;
Android 10,
EMUI 10.0.0 Build number 10.0.0.197(C432E8R1P3)

**How to reproduce:**

1. Import contacts from .vcf file
2. Choose `phone storage` (i think this is the one that is visible by other apps?)

**What happens:**

- No contacts do get imported
- This error message pops up:
   ```
   Es ist ein Fehler aufgetreten:
   java.lang.illegalArgumentException:
   Unknown authority com.android.contacts
   ```
   
**Additional info:**

- I removed a few android programs via adb and if i remember correctly, i removed the native android contacts app as well.
- Simple-Contacts has the following permissions: contacts; phone

**Comment by ThiloteE** [comment]
If i choose `phone storage (not visible by other apps)` i can import the contacts successfully.

**Comment by tibbi** [comment]
you are not supposed to remove system components, of course it will break your device

**Comment by ThiloteE** [comment]
I can understand where you are coming from, but at the same time i think you can understand my goal to not have two apps on my phone that do almost the same thing, while both use CPU, RAM, battery and potentially my internet. I was under the impression that Simple-contacts could replace the native contacts app and i was not aware you are using at least part of it under the hood.

**Comment by tibbi** [comment]
not always, you cannot just remove some system apps

**Comment by ThiloteE** [comment]
Thanks for the fast response, i will keep that in mind.

**Comment by ThiloteE** [comment]
Partly duplicate of https://github.com/SimpleMobileTools/Simple-Contacts/issues/720
