### ISSUE TITLE
can't pick email from contact for k9

### ISSUE THREAD

**Issue by nutpantz** [SimpleMobileTools/Simple-Contacts#78]
When I try to use simple contacts to provide email address to k9mail it crashes k9mail.

**Comment by tibbi** [comment]
hah it actually crashes gmail too

**Comment by tibbi** [comment]
hah it actually crashes gmail too, I won

**Comment by tibbi** [comment]
it will be fixed in 3.3.0 but make sure you grant the Contacts permission to K9 manually in settings before requesting the email, K9 is not handling it properly.
