### ISSUE TITLE
[Privacy] Although I a paid some money to allow importing .VCF files I can no longer use your app for my contacts because I realized you were not importing to your own SQLLite DB but Android's Global contact manager.

### ISSUE THREAD

**Issue by firepacket** [SimpleMobileTools/Simple-Contacts#785]
The whole point of using your app was that other apps could not see the contacts I imported into YOUR app.

Unfortunately, that is not the case. Once they are imported into your contacts app, you use the  Android API to store them so ALL OTHER APPS requesting contact access will get access to contacts I gave YOUR app.

This is unacceptable, and would be considered RUDE under normal circumstances. (But nobody cares on mobile) Telegram does not share its contacts, it maintains it's own database of contacts when you don't give it access to the Android Contact API.

Your software is not privacy aware and will leak contact information to pretty much any app downloaded most of which force contact access. I am very disappointed and will continue to look for another contact app or build one myself.

**Comment by firepacket** [comment]
If anyone knows a contact app that keeps imported contacts within its own protected SQLLite DB please let me know.

**Comment by tibbi** [comment]
you can customize what contact source do the contacts get stored in. Just pick "Phone storage (not visible by other apps)" if thats what you want

**Comment by firepacket** [comment]
Thank you
