### ISSUE TITLE
GUI Enhancement

### ISSUE THREAD

**Issue by GithubContributor832** [SimpleMobileTools/Simple-Contacts#797]
Please change the spelling of Import contacts from a .vcf file, Export contacts to a .vcf file, Send SMS to contacts, and Send email to contacts. It should be Import from a .vcf file, Export to a .vcf file, Send SMS to, and Send email to in order to prevent wrong English when selecting one contact.

**Comment by tibbi** [comment]
that is not clear enough

**Comment by GithubContributor832** [comment]
![Screenshot_20220308-184305_Contacts_1_1](https://user-images.githubusercontent.com/92182796/157344922-b8ca9299-03a4-4ab9-a98c-a05da0445a26.png)
![Screenshot_20220308-184233_Contacts_1](https://user-images.githubusercontent.com/92182796/157344925-16ffe8bf-b2f2-4f28-813f-a0ba1410a30a.png)

Hope you'll reopen wrong spelling in menu items if happen to deal with only one contact for any specific reason.

**Comment by tibbi** [comment]
How could I know how many contacts will there be in the .vcf file...

**Comment by GithubContributor832** [comment]
Its no biggie I shouldn't have posted this as the more I thought on it I look dumb as like no one does this. Just be my thing if I wrote code to specify if a label could be singular or plural with an (s) at the end of the label if it could be singular or plural. Please ignore me as I know its picking at the app to much without intent to offend. My opinion all.
