### ISSUE TITLE
change default source location

### ISSUE THREAD

**Issue by wieluk** [SimpleMobileTools/Simple-Contacts#799]
Hey I could not find any way to change the default source. Is there anyway? I would like to save my contacts to nextcloud on default.

**Comment by tibbi** [comment]
Just store one contact there, then it will be set as the default for the next ones.

**Comment by 6801318d8d** [comment]
> Just store one contact there, then it will be set as the default for the next ones.

This is not obvious at all.

It would be useful to have an option in the settings.

Can we reopen this?

**Comment by tibbi** [comment]
not really, changing it isnt on the roadmap now
