### ISSUE TITLE
Set default phone number for contact.

### ISSUE THREAD

**Issue by dotancohen** [SimpleMobileTools/Simple-Contacts#807]
There is currently no way to set a default phone number per contact. Please add this feature.

**Comment by tibbi** [comment]
such things are handled by Dialer apps, not Contacts

**Comment by tibbi** [comment]
or nevermind, it could be in Contacts too. Sadly there is no support for it on Android though, so we can add only some solution that will work with our apps only

**Comment by dotancohen** [comment]
When a user clicks a contact and is sent to the dialer, the full contact is sent, not the phone number? Then why is the phone number chooser shown in the Simple Contacts app UI, and not in the Dialer's UI?

A solution might be to use a `tel:` URL scheme, which does send a telephone number to the dialer.
