### ISSUE TITLE
Favorites tab showing cnotacts from all accounts.

### ISSUE THREAD

**Issue by dotancohen** [SimpleMobileTools/Simple-Contacts#808]
In the Favorites tab, though I have selected the filter to only show contacts from the two DavX accounts, contacts are shown from all accounts.

**Comment by tibbi** [comment]
that is currently the expected behaviour

**Comment by dotancohen** [comment]
As a user, if I've configured a filter to show only items from specific account, then I would expect that only items from those accounts are shown. But it's not a hill I'll die on. ))
