### ISSUE TITLE
[feature request] field for clickable web links

### ISSUE THREAD

**Issue by gbdomubpkm** [SimpleMobileTools/Simple-Contacts#825]
Hello.
Thank you for this app which improves regularly.
Could you create a field that would allow you to enter one or more clickable web links? Would be useful for professional contacts. Currently as a workaround from a contact, I enter the web link in the 'notes' field, then copy and paste it into the browser.
Thank you

**Comment by tibbi** [comment]
you can already enable Website field in the app Settings -> Manage shown contact fields.

**Comment by gbdomubpkm** [comment]
I didn't see that ! Thanks
