### ISSUE TITLE
Starred contacts not filtered by when address books are hidden

### ISSUE THREAD

**Issue by TownCube** [SimpleMobileTools/Simple-Contacts#828]
When applying a source filter the contacts from hidden address books disappear from the first tab as expected.

However if you switch to the starred contact tab all the contacts from all the address books are visible enough though the filter menu shows these addresss books should be hidden.

I tried unstar-ing the duplicate I didn't want to see but unstar-ing any single contact makes both disappear.

Can workaround this with turning on "merge duplicate contacts" but I think both tabs should work the same way.

**Comment by tibbi** [comment]
the filter should be applied there too, thats how it works to me with 6.18.2. Update whenever it becomes available.
