### ISSUE TITLE
330 crashes trying to provide email address

### ISSUE THREAD

**Issue by nutpantz** [SimpleMobileTools/Simple-Contacts#83]
When using k9mail and trying to get email address from contacts phone storage I get an error.
An error occurred: java.illegalstateexceptiin:address must not be null.

When in k9 I pick add from contacts, then contacts simple comes up, empty list and the error is shown in a toast.

**Comment by nutpantz** [comment]
It will however work if not using phone storage for the contact list.

**Comment by nutpantz** [comment]
The error shows up regardless of what filter is picked.. I'll keep trying to test

**Comment by nutpantz** [comment]
If not using an secondary account for contacts(for me that would be essential pim pro) there is no error, but no contacts are shown from "phone storage"

**Comment by tibbi** [comment]
what app version do you have? It should work. Just make sure K9 has the Contacts permission

**Comment by nutpantz** [comment]
Version 3.3 fresh from fdroid. And I made sure k9 had contacts permission. When k9 switches to simple contacts I can change the fuller and see the list populate or disappear when I switch to phone storage (it disappears on phone storage)

**Comment by tibbi** [comment]
retry with 5.1.0, reopen if it still isnt fixed
