### ISSUE TITLE
Sync issue with cardDAV, DAVx5/Nextcloud: Changes are visble only after SimpleContacts App restart

### ISSUE THREAD

**Issue by michaelof** [SimpleMobileTools/Simple-Contacts#830]
6.18.1 F-Droid

Reproducible:
1. Make some changes to contact(s) in Nextcloud, e.g. create a new contact
2. Sync to Android via DAVx5
(changes immediately after sync visible in (stock) Google Contacts app)
3. try to search within SimpleContacts: NOT visible

Workaround: Go to SimpleContacts App props, terminate/kill app, start SimpleContacts again. Changes are now visible.

**Comment by michaelof** [comment]
Sorry, my mistake, corrected first post. It's all about Contacts, not Calendar

**Comment by tibbi** [comment]
well, contants arent being refetched in the background, you have to restart the app to see new items

**Comment by michaelof** [comment]
OK, but is this a new behaviour? Because of newer Android versions? I'm pretty sure that this worked different for older versions of SimpleContacts, or?

**Comment by tibbi** [comment]
not really, thats how it always worked, I dont plan background refreshing now
