### ISSUE TITLE
New Feature: Seperate last name and first name with a comma

### ISSUE THREAD

**Issue by 0815horsti** [SimpleMobileTools/Simple-Contacts#831]
See above - last name and first name should be seperate by a comma.

If you display your contacts with the last name first and sort them it is sometime not easy to differ between first and last name. The complete list does not end with the last contact, it is continued with those whose last name is not filled... this rule should only apply if the field "last name" is not empty

Example (complete name)
Peter Miller
=> Miller Peter
=> Better: Miller, Peter

**Comment by tibbi** [comment]
it will be added already in the next app version released soon
