### ISSUE TITLE
Incorrect display of name or organization

### ISSUE THREAD

**Issue by sebastian0119** [SimpleMobileTools/Simple-Contacts#838]
When a contact has a name and organization, the contact list is displayed correctly, but the contact card does not show the organization, the logo seems to make reference to the organization and the name is not displayed, either.

I'm here on a Samsung A53 5G, with Android 12.

Here the vcard source code:
![Screenshot_20220618-095713_Total Commander](https://user-images.githubusercontent.com/52871458/174452248-435b798e-8b3a-4922-a545-7074462c4409.jpg)

The contact list:
![Screenshot_20220618-100103_Contacts](https://user-images.githubusercontent.com/52871458/174452258-4423dbac-7ae7-463a-8788-a8f588a52efb.jpg)

 And the contact card:
![Screenshot_20220618-100221_Contacts](https://user-images.githubusercontent.com/52871458/174452299-4f6c31f1-a54e-4dcf-9a85-e378fd22c4c2.jpg)

If you need some additional information, just let me know. Cheers

**Comment by sebastian0119** [comment]
App version is 6.19.0 from F-Droid, just in case

**Comment by VibrantTreeStump** [comment]
I can confirm this issue for v6.21.0 from F-Droid

**Comment by tibbi** [comment]
should be fixed already
