### ISSUE TITLE
Removing characters minus spaces and brackets when grouping numbers

### ISSUE THREAD

**Issue by OmlineEditor** [SimpleMobileTools/Simple-Contacts#840]
other contact programs group numbers in different ways and add space characters, parenthesis characters "( )" and minus characters to the number.

sometimes, after grouping, it is not possible to display the number correctly because there are extra characters in it. I ask you to make a function that cuts out all the extra characters from the phone number.

when cutting, I ask you to delete only:
-  space characters
- parenthesis characters "( )" 
- minus characters

at the same time, do not touch the symbols: 
- `*`  - star
- `#` - grid
- `P` - symbol P (pause)

**Comment by tibbi** [comment]
we are doing no grouping ourselves

**Comment by OmlineEditor** [comment]
I know, that's why I added two tickets at the same time. here's the second one for the future: https://github.com/SimpleMobileTools/Simple-Contacts/issues/839

please open a ticket and make it in the future.
