### ISSUE TITLE
Calling option doesn't work in Android 11

### ISSUE THREAD

**Issue by nemoskapetanos** [SimpleMobileTools/Simple-Contacts#850]
Hi,

My wife has an Android 11 phone and the call option doesn't work when you open a contact and click the call icon. Just a floating window appears with the name of the contact and a headset icon but it doesn't connect the call. Same issue with the dialer.

This option works completely fine on my Android 10 phone, so it must be an issue with how call management has been implemented in Android 11. Yes, the manage calls permission has been enabled on my wife's phone for both apps. Actually, all of the permissions needed have been enabled. 

If you need any other info to troubleshoot this issue, let me know.

**Comment by tibbi** [comment]
guess you enabled call confirmation in the app settings, just click on the icon

**Comment by nemoskapetanos** [comment]
Thanks for that! I have now disabled the call confirmation option in the settings and everything works fine. My wife enabled all the call options, I have no idea why. She would also like to thank you for making an easy to use phone/contact app for Android!
