### ISSUE TITLE
 not work delect contact in androdi1 12 xiaomi

### ISSUE THREAD

**Issue by tennisEZ** [SimpleMobileTools/Simple-Contacts#865]

**Comment by tibbi** [comment]
Hello, not sure what you mean. You have some issues?

**Comment by tennisEZ** [comment]
I was unsuccessful when deleting a designated contact on Android12 Mi

**Comment by tennisEZ** [comment]
https://static.dingtalk.com/media/lQDPJxaT4twEh8DNBQDNAkCwUXitss2fTd4C81ztswA9AA_576_1280.jpg_720x720g.jpg?renderWidth=576&renderHeight=1280&renderOrientation=1&isLocal=0&bizType=im

**Comment by tennisEZ** [comment]
![Screenshot_2022-08-10-16-58-33-355_com simplemobiletools contacts pro](https://user-images.githubusercontent.com/38183937/183861026-ee823adb-5467-49b2-906e-197142561253.jpg)

**Comment by tibbi** [comment]
are you getting some error or what happens?

**Comment by tennisEZ** [comment]
Nothing happened, except that the contact wasn't deleted

**Comment by tennisEZ** [comment]
When I hit OK

**Comment by tibbi** [comment]
what app version are you using? what contact source are you saving the contact to? I mean the last field at the contact details screen. Does it say your email, Phone, SIM or something like that?

**Comment by tennisEZ** [comment]
I'm using the latest version of the program and it shows

**Comment by tennisEZ** [comment]
Now I know what the problem is isPrivate=false

**Comment by tibbi** [comment]
what?
