### ISSUE TITLE
Can't scroll full-range of contact card when editing lower fields with virtual keyboard

### ISSUE THREAD

**Issue by maze88** [SimpleMobileTools/Simple-Contacts#866]
### Steps to reproduce

1. Select a contact and press the _Edit_ button.
2. Note the large red (in screenshot 1, below) initial letter at the top of the screen.
3. Pressing one of the text fields to edit, will bring up the virtual keyboard
3. If it's a text field from the **_bottom_** of the screen (such as "_Notes_") then one can only _scroll up_ part-way of the screen (can't reach all the of header (red in screenshot below).
4. Workaround: Only after closing the keyboard, can one scroll the full range of the screen.

### Expected behavior

After editing a field, one should be able to scroll on to any other field (even if at the other end of the screen) - **without needing to close** the virtual keyboard.

### Screenshot

Editing a contact card, with keyboard open, whilst editing the "_Notes_" field, scrolled farthest **_to top_** of screen.

![Screenshot_20220810-max-up](https://user-images.githubusercontent.com/16841581/184076786-4350749a-d33e-45d9-83c6-906d5c6868c1.png)

**Comment by tibbi** [comment]
should be fixed already
