### ISSUE TITLE
No details when the contact is also on Telegram

### ISSUE THREAD

**Issue by happyreacer** [SimpleMobileTools/Simple-Contacts#87]
I use Telegram on my smarfone and synconaise my contacts with a carddav server. Normaly i see all details of the contacts like birthday and adress. But i see nothing like this in my contacts with an telegram acout. I see only the Telegram ID.
I think it is a bug

**Comment by derlucas** [comment]
I can confirm this Bug.

**Comment by ReekyMarko** [comment]
Same issue here also

**Comment by tibbi** [comment]
should be tweaked in 4.0 released soon, reopen if still broken

**Comment by diagus65** [comment]
It seems that this issue is in the current version (6.21.1) again.
