### ISSUE TITLE
Alternative Phone numbers not shown  when trying to edit

### ISSUE THREAD

**Issue by qnxdev** [SimpleMobileTools/Simple-Contacts#870]
![WhatsApp Image 2022-08-21 at 2 29 03 PM](https://user-images.githubusercontent.com/47214790/185784635-0af3180f-fabd-4517-86b6-346da660b52d.jpeg)
![WhatsApp Image 2022-08-21 at 2 29 04 PM](https://user-images.githubusercontent.com/47214790/185784639-e59f204e-35e7-4b62-98b6-7fdec7f5351f.jpeg)

alternate phone numbers are shown when contact is opened but when trying to edit only primary number is visible

Android 11.

Contact app version : 6.20.0 Pro

**Comment by tibbi** [comment]
thats caused by duplicate contact merging, the View screen shows all numbers from all sources that are listed at the bottom. But at editing you are editing only one specific contact source.
