### ISSUE TITLE
Add URI scheme for XMPP

### ISSUE THREAD

**Issue by jcperil** [SimpleMobileTools/Simple-Contacts#877]
Simple Contacts can redirect email addresses to email clients on my phone. But it fails to redirect jabber ids to XMPP clients on my phone.

**Comment by tibbi** [comment]
not sure what you mean at all, where should be what?

**Comment by jcperil** [comment]
1. Create a contact.
2. Add an email address, e.g. `daniel@gultsch.de`
3. Add an XMPP address (also known as [jabber id](https://en.m.wikipedia.org/wiki/JID_(Jabber))), e.g. `daniel@gultsch.de`
4. Save the contact.
5. Click the email address `daniel@gultsch.de`
See screenshot for expected result.
![mailto](https://user-images.githubusercontent.com/89805719/188314366-d8452771-6d4a-4fc9-b5fb-7a5a926bfa2f.jpg)

As you can see, user is presented with a list of available (email) clients that can compose a new email with the recipient `daniel@gultsch.de`

6. Click the jabber id `daniel@gultsch.de`

Nothing happens when you click the jabber id.

**Expected result**:
Show the list of XMPP clients on the user's device to compose a new message with recipient `daniel@gultsch.de`

**User speculation:**
A [URI scheme](https://en.wikipedia.org/wiki/List_of_URI_schemes)  redirects the addresses to their respective clients. `mailto` is the URI scheme for emails which I found it in your code appear [thrice](https://github.com/search?q=mailto+repo%3ASimpleMobileTools%2FSimple-Contacts&type=code). The URI scheme for jabber ids is `xmpp` which is [not present](https://github.com/search?q=xmpp+repo%3ASimpleMobileTools%2FSimple-Contacts&type=code)  in your code. Perhaps that is the reason.

**Comment by tibbi** [comment]
right that is too advanced, not really on the roadmap. As it is an email address, opening an email client is the expected behaviour.
