### ISSUE TITLE
Reposition contact photos so that they are not truncated or covered by toolbar buttons

### ISSUE THREAD

**Issue by nathanzachary** [SimpleMobileTools/Simple-Contacts#880]
Hello,

Thank you very much for creating such wonderful minimalistic apps!  A feature that I would really like to see is repositioning a contact's photo so that it is neither truncated at the top of the image nor covered with toolbar buttons (the "back", "edit", "share", "delete", and "menu dot" icons.

My contact photos are all 512x512 (which I believe is the standard for other contact applications including Google Contacts), but a portion at the top of the photo isn't displayed due to the photo being at the very top of the contact display screen.  It would be nice to have the contact photo start directly underneath the toolbar buttons so that the full photo is displayed and not covered by those buttons.

Thank you again for your time and work.

Cheers,
Nathan Zachary

**Comment by tibbi** [comment]
Hey, I dont want to move those, just click on the photo to see it enlarged.
