### ISSUE TITLE
Option to save contacts in multiple locations.

### ISSUE THREAD

**Issue by chisbroad** [SimpleMobileTools/Simple-Contacts#881]
Moto G52 Android 12

It seems like when the contacts are saved in phone, other apps like Telegram and Signal can't access them. 

And going individually in each of contact numbers and changing the stored location is a hassle as well as problematic because if I uninstall that particular app, it will remove all the associated contacts along with it.

I also can't save a contact in multiple locations. Currently, only one is allowed.

I understand that Google counterparts come with special privileges but maybe you could do these things- 
1. Give the option, while creating new contacts, to save in multiple locations. Or make this an automatic feature like it detects the accounts and adds in automatically at the time of new contact creation. Make some kind of default location option in settings. People there could choose as per their liking.
2. In case someone installs such apps like Telegram or Signal later on, maybe you could give a universal option within the app to save them there as well. So the old ones could also be accessible.

Thanks a lot for all the hard work you go through for all of us. Really appreciate it.

**Comment by tibbi** [comment]
saving at multiple places isnt on the roadmap, where exactly are you storing them? Telegram and Signal should see them just fine by default.

**Comment by chisbroad** [comment]
They are being stored in Phone Storage but are not accessible by other apps. It also states- not visible by other apps.
And if I change the location to Signal or Telegram then in case I uninstall those apps, my contacts saved with them will also disappear. 
Not to mention I can only choose one place which causes syncing problem with the other.

**Comment by tibbi** [comment]
what app version do you have? There should be something like "Phone" too. If it isnt there, just store a contact there first with some preinstalled app, then it will show up in our app too.

**Comment by chisbroad** [comment]
I'm currently on v6.21.0
It worked but upon uninstalling that Google contact app, that option also went away.
I don't want to keep that spyware on my system. 
Is there is fix which could remove this dependency from it?

**Comment by tibbi** [comment]
just create a single contact on "Phone", you dont have to use that app afterwise.

**Comment by chisbroad** [comment]
Yes, I did exactly what you asked and it worked but I don't want to keep any Google app on my system. 
Will it be possible for you to remove this dependency in future releases or something?

**Comment by tibbi** [comment]
that is not a dependency, some apps just cannot detect contact sources without any contact in them. Only the preinstalled apps can do it in some cases.

**Comment by chisbroad** [comment]
Ok, I found a fix. 
Save one contact there so that the storage is detectable and afterwards and change the location of any one of the contacts to phone. Afterwards, you can remove the Google contact app.

Thank you so much for giving me your time. I really appreciate it a lot.
