### ISSUE TITLE
Importing vcf file only possible to closed internal storage

### ISSUE THREAD

**Issue by fabykr** [SimpleMobileTools/Simple-Contacts#883]
![Screenshot_20220921-093705532 (1)](https://user-images.githubusercontent.com/88263135/191444019-4428e2a7-7266-4dcb-adc1-168d70e03483.jpg)

![Screenshot_20220921-093837102 (1)](https://user-images.githubusercontent.com/88263135/191444230-1cecb0ed-094e-4d2f-bf80-542f6c140ebc.jpg)

I have the problem that I only see the internal storage not seen by others apps as an option. So i cannot add new contacts with others apps. I don't know where the already shared contacts come from. Maybe I imported them top the stock contact app before installing Simple Contacts. I am on a degoogled custom rom (crDroid) and the app version 6.21. Happy to provide more infos if needed.

**Comment by tibbi** [comment]
try creating a single contact into "Phone" or some other storage with the preinstalled app, then it will show up in this one too.

**Comment by fabykr** [comment]
Halleluja, it worked! Thank you very much
