### ISSUE TITLE
Monochrome / Themed Icons

### ISSUE THREAD

**Issue by we3ve** [SimpleMobileTools/Simple-Contacts#884]
Monochrome/Themed Icons support Is lacking for Simple Contacts Pro using Android 13.

Per the "What's New" section of GPlay, update 2022-08-18, Simple Contacts Pro added Monochrome Icons / Themed Icons support. This does not appear to be the case.

Checked against Simple File Manager Pro and Simple Gallery Pro. Both of these apps properly implemented the feature.

**Comment by tibbi** [comment]
it works just fine to me and it is done the same way as other apps, make sure you really use 6.21.0
