### ISSUE TITLE
Unresponsive right sidebar (quickscroll)

### ISSUE THREAD

**Issue by Pablohn26** [SimpleMobileTools/Simple-Contacts#89]
Normally there is no problem when using right quick scroll. It is also useful when you search (filter). But it is unresponsive when you scroll it till a blank contact and press on search to type your search/filter. It is stuck on the blank and moving it makes no sense. 

I do not know if my description is understandable or not, I could provide a video about how to reproduce the buggy behaviour.

**Comment by tibbi** [comment]
ye it makes sense, the scrollbar can be glitchy when the scrollable content changes. I will improve it in the future, but it isnt a priority for now.

**Comment by tibbi** [comment]
should be improved in 4.0.x

**Comment by Pablohn26** [comment]
Fixed
Thanks! 
:)
