### ISSUE TITLE
Handle RAW_CONTACT_IS_READ_ONLY / Data.IS_READ_ONLY flags

### ISSUE THREAD

**Issue by rfc2822** [SimpleMobileTools/Simple-Contacts#894]
Hi,

It's possible that sync adapters like DAVx⁵ sync contacts with the [RAW_CONTACT_IS_READ_ONLY](https://developer.android.com/reference/android/provider/ContactsContract.RawContactsColumns#RAW_CONTACT_IS_READ_ONLY) flag (respectively [IS_READ_ONLY for data rows](https://developer.android.com/reference/android/provider/ContactsContract.DataColumns#IS_READ_ONLY)). It causes the contacts provider to reject changes for these rows that are not coming from sync adapters.

Unfortunately, no contacts app that I know (including Simple Contacts) handles this flag correctly. So users can edit the contacts in the UI, but when they click _Save_, the changes are lost.

It would be awesome if Simple Contacts could read the read-only flags and disallow editing in the UI for the affected contacts.

**Comment by tibbi** [comment]
our app doesnt handle any syncs, it just shows already existing contacts
