### ISSUE TITLE
Unable to import contacts from .vsf file

### ISSUE THREAD

**Issue by peter099** [SimpleMobileTools/Simple-Contacts#897]
I reinstalled my LineageOS 17.1 rom and after that i tried to import my contacts from vcf file, exported from Simple Contacts, to the stock contacts app, but it say: `Couldn't import vCard. The format isn't supported.`

**Comment by tibbi** [comment]
that isnt an issue on our side

**Comment by peter099** [comment]
I can't import them to Device, only as hidden contacts. The same happens when i am exporting contacts.

**Comment by peter099** [comment]
I managed to save my contacts to phone storage by using Google Contacts app which has option to save to device. But if i try to export my contacts in Simple Contacts it export only with the option as hidden contacts: https://imgur.com/JG7iRoD
