### ISSUE TITLE
Extensions seem to be ignored on import

### ISSUE THREAD

**Issue by contrapunctus-1** [SimpleMobileTools/Simple-Contacts#90]
Thanks for this application, it's been a lifesaver! (e.g. importing my contacts on an older phone which declared the contacts file as being an "unsupported format")

I imported a VCF file containing extensions e.g. X-JABBER and X-SIP fields. None of them were imported, the contacts were simply created without said fields. v3.3.2 from F-Droid on a Moto G, Android v5.1.

**Comment by tibbi** [comment]
such fields are not supported at all yet, not just skipped at importing

**Comment by Mannshoch** [comment]
Mockup:
![mockup_protocol_support](https://user-images.githubusercontent.com/7795891/40772627-c8d0c8c0-64c0-11e8-8ba2-d463cd028498.png)

**Comment by tibbi** [comment]
will be added in 4.4.0
