### ISSUE TITLE
When choosing a contact from another application, the column CommonDataKinds.Phone.NUMBER is not present

### ISSUE THREAD

**Issue by xfarrow** [SimpleMobileTools/Simple-Contacts#905]
When choosing a contact from your app, the result of which is processed by another app (using Intents), some columns are missing. One of those is the important `CommonDataKinds.Phone.NUMBER` containing the phone number.

For more information, I opened a question on StackOverflow [here](https://stackoverflow.com/questions/74244787/android-unable-to-retrieve-contact-info-if-third-app-contacts-is-being-used) explaining the issue in more detail, but I am afraid it can be fixed solely by editing this app.

**Comment by xfarrow** [comment]
@tibbi first of all, thank you for your precious FOSS work, amazing.

For the sake of debugging purposes, you can execute my app https://github.com/xfarrow/locatemydevice and try to add a whitelist number using Simple-Contacts.
The cursor [here](https://github.com/xfarrow/locatemydevice/blob/main/src/app/src/main/java/com/xfarrow/locatemydevice/WhitelistContactsActivity.java#L130) will not have `CommonDataKinds.Phone.NUMBER` which is explained [here](https://developer.android.com/reference/android/provider/ContactsContract.CommonDataKinds.Phone#NUMBER).

I am not experienced enough to fix this.

**Comment by tibbi** [comment]
so you cannot reproduce it in any real app, just your own project? It wont be an issue on our side then
