### ISSUE TITLE
dot removed from name in whatsapp contacts

### ISSUE THREAD

**Issue by diagus65** [SimpleMobileTools/Simple-Contacts#908]
When a whatsapp contact has a dot in the name, the dot is removed and the contact is not merged.
![Screenshot_20221106-121905_Contactos](https://user-images.githubusercontent.com/115782118/200174854-d790553a-f608-42de-b0b7-694bc3508432.png)

App version: 6.21.1 Pro

**Comment by tibbi** [comment]
we arent doing any removing ourselves, it must be caused by something else

**Comment by diagus65** [comment]
@tibbi, sorry for the inconveniences
It seems that there was some error in the data stored by whatsapp (but the AOSP Contacts app works fine with it!).
Solved by editing whatsapp contact entry to force matching.
