### ISSUE TITLE
Unable to select a contact in the emergency mode

### ISSUE THREAD

**Issue by Primokorn** [SimpleMobileTools/Simple-Contacts#91]
Hi,
Go to the Emergency mode from the lockscreen, where you can add information in case of emergency.
There's an option select contacts. I can open Contacts app and select a contact but it's really selected. It doesn't show up.

I have a OnePlus 3T running Oreo 8.1.0 (Resurrection remix custom rom). I removed the stock contacts app.
Do you confirm there's a bug or is it just me?

Thank you.

**Comment by tibbi** [comment]
Ill take a look at it later
