### ISSUE TITLE
[FEATURE REQUEST] Homescreen direct dial widgets

### ISSUE THREAD

**Issue by user8446** [SimpleMobileTools/Simple-Contacts#916]
Hi,

I switched from the stock Android Contacts to Simple Contacts. Everything in the app works great and as expected but when I went to add my direct dial contacts to the home screen, I then noticed that Simple Contacts doesn't even have homescreen widgets.

Since this a must for daily frequently called contacts, I unfortunately had to revert back to Android Contacts.

I think it would be great if this was a feature added. This is similar to https://github.com/SimpleMobileTools/Simple-Contacts/issues/553 and https://github.com/SimpleMobileTools/Simple-Contacts/issues/554 requests.

Thank for for the development!

**Comment by Aga-C** [comment]
You can already create a shortcut of the selected contact on a homescreen.

**Comment by tibbi** [comment]
for calling you have to use Simple Dialer

**Comment by user8446** [comment]
Thanks for the reply... I currently need the spam calling protection in the Google Phone app so I wouldn't be able to use that and Simple Dialer at the same time.
