### ISSUE TITLE
[Feature] Add option to import to multiple "Phone Books".

### ISSUE THREAD

**Issue by Rexadev** [SimpleMobileTools/Simple-Contacts#917]
### Use Case

1. User got a synced account that they share with family. And a personal account.
2. User wants to be able to search contacts from family account but not share their personal contacts.
3. Add option to create a local phonebook and import .vcf, .csv to it.
4. Able to search each separately.
5. If there is a conflict show personal account/phone-book
6. Able to export each separately.
7. multiple phone books will require to use Simple Contacts App Data and not Local Storage for Contacts

### UI

I like AOSP UI with side panel on left side

**Comment by tibbi** [comment]
you can already filter visible contact sources and select the wanted ones at exporting too
