### ISSUE TITLE
feature request: delete entries in contact details

### ISSUE THREAD

**Issue by volker-raschek** [SimpleMobileTools/Simple-Contacts#92]
Hello, 
I have a suggestion for improvement. It's would be great, if Simple-Contacts has a same button how the add button, but to delete an entry. For example to delete an email entry.

See my screenshot. I would like to delete "max.mustermann@example.com2". Actually I must delete tthe value of the textbox, to delete "max.mustermann@example.com2". A button would be better.

[Screenshot](http://666kb.com/i/drso6tewdd439w6ww.png)

**Comment by tibbi** [comment]
Sorry, but I dont want to spam the app with unnecessary buttons. Maybe just doubletap the email and select Cut, that will remove it.
