### ISSUE TITLE
Support offer

### ISSUE THREAD

**Issue by rlieger** [SimpleMobileTools/Simple-Contacts#920]
Hi,

I am a experienced programmer and fan of simple mobile tools.

I would like to support you and implement the following features for SimpleContacts:
.) Add FullName field (FN field of vCards as distinct editable field with autolink to structured fields)
.) Add structured address fields (rather than cramming all address information into the street field)
.) Switching between portrait and landscape mode while editing a contact should not reset all changes already made
.) Leaving the edit dialog using the "back arrow" should offer a choice to save or discard all changes made (rather than simply discarding them)
.) If a contact contains organisational information, the item information should still be read
.) Use more display formats for names in the main tab than just "start with last name yes/no"
.) Smarter selection of characters for placeholder character (Sir Elton Hercules John, HC, CBE should be 'E' (start names with first name) or 'J' (start names with last name) but not 'S')

Are you interested?

Regards,
  Roland Lieger

**Comment by tibbi** [comment]
Hi, sure, you can do the last one
