### ISSUE TITLE
"Main" telephone type is not correctly exported/imported

### ISSUE THREAD

**Issue by cubernetes** [SimpleMobileTools/Simple-Contacts#925]
**Environment:**
Android 13
OxygenOS 13.0 (OnePlus 10 Pro 5G)
Simple Contact Pro v6.22.0

**Steps to reproduce:**
- Create a new test contact and enter a phone number of type "Main"
- Export that contact using the share function, it will be exported as a vcf
- Delete the test contact
- Import the vcf

**Actual result:**
- The phone number type field is empty

**Expected result:**
- The phone number type field should say "Main", as previously selected

**Possible reason for this behaviour:**
When looking at the exported vcf, the culprit line says
`TEL;PREF=1:+123456789`
Whereas a phone number with type "Work" would yield
`TEL;TYPE=WORK:+12345555678`

So I tried substituting "PREF=1" with "TYPE=MAIN". **And this actually worked.** Importing it after that change yields "Main" in the type field. So either changing the importing or the exporting will fix this issue.

**Comment by Mylloon** [comment]
Hello, I'll submit a PR soon
