### ISSUE TITLE
[Feature Request] A option to resize contact feld icons

### ISSUE THREAD

**Issue by oomfiee** [SimpleMobileTools/Simple-Contacts#928]
add a option to allow resizing of contact feld icons (aka Large, Medium, Small, etc..)

**Comment by tibbi** [comment]
what field icons you mean?

**Comment by oomfiee** [comment]
> what field icons you mean?

this
![Contacts](https://user-images.githubusercontent.com/80048740/212316391-cd798436-cbf4-4a37-935b-451da255c515.png)

**Comment by tibbi** [comment]
customizing that isnt really on the roadmap
