### ISSUE TITLE
feature request: customize key values for entry groups in contact details

### ISSUE THREAD

**Issue by volker-raschek** [SimpleMobileTools/Simple-Contacts#93]
Hello, 
I have an suggestion for improvement again. It's would be great, if I could customize the key->label->values in contact details, for example see my [screenshot](http://666kb.com/i/drsohws961ccdv3eo.png). I designate label as "Privat", "Work", "University", value as the value, for example the private, university or work email address, the key as the key which is defined in the vcf file.

Here is for test use cases my Max Mustermann contact. 
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Thunderbird.org/NONSGML Thunderbird CardBook V25.6//EN
UID:urn:uuid:acda46ee-2ae7-4cf1-8c5b-263422fe26f1
CATEGORIES:Test
N:Mustermann;Max;;B.Sc.;
FN:Max Mustermann
REV:2018-02-25T17:20:50Z
EMAIL;TYPE=PREF;TYPE=HOME:max.mustermann@private.local
EMAIL;TYPE=UNIVERSITY:max.mustermann@university.local
EMAIL;TYPE=WORK:max.mustermann@work.local
X-THUNDERBIRD-ETAG:"146b2afc5c0c4e90c351d64901e9ef3b"
END:VCARD  
```

**Labels:** Privat, University, Work
**Keys:** HOME, UNIVERSITY, WORK
**Values:** max.mustermann@private.local, max.mustermann@university.local, max.mustermann@work.local

The reason is, I synchronize my contacts over the app DavDroid to my CardDav-Server and then to my computer and laptop, where I use Cardbook, a Thunderbird addon, to manage my contacts.  

Every android contact app use their own key->label->values and is terrible to manage. So, please implement a feature, that I can set up on every device the same key values. 

Install the Cardbook addon in Thunderbird to see, how they have implement this feature. It's would be nice, if Simple-Contacts would provide the same function.

**Comment by tibbi** [comment]
custom types have been added in 4.4.0
