### ISSUE TITLE
Feature Request: Whitelist third party apps to access contacts stored inside Phones storage (not available by other apps)

### ISSUE THREAD

**Issue by W1zardK1ng** [SimpleMobileTools/Simple-Contacts#930]
Hi Team,

I don't store any of my contact on the traditional phone storage which every apps can access, instead i store my contacts in additional Phone storage (not visible by other apps) option which is provided by simple contacts.
It sync perfectly with all the Simple apps(Simple Dialer and Simple SMS Messenger).
The only problem currently having is that, Messenger apps like Whatsapp and Signal doesn't show any contacts inside them since i didnt store any contacts in the traditional phone storage. 
I believe it will be a great feature to add an option to share the contacts stored inside the simple contacts with other apps at least for Whatsapp and Signal.

Thanks.

**Comment by tibbi** [comment]
that cannot be done, they are stored in a whole different way. Thats the point of it...

**Comment by W1zardK1ng** [comment]
@tibbi Thanks for clarifying, so this case will you be able to add an option open whatsapp/signal chats directly from the contacts or dialer app?
something slimier to OpenContacts https://f-droid.org/en/packages/opencontacts.open.com.opencontacts/
In the current setup it is very much difficult to start a chat in messaging apps.
