### ISSUE TITLE
Back button does nothing

### ISSUE THREAD

**Issue by favdish** [SimpleMobileTools/Simple-Contacts#934]
I can't find a way to exit Simple Contacts other than going to Recent Apps and terminate it there -- which is a hassle. Why doesn't SC stop when the back button is pressed once or twice? Or am I overlooking something?

Other than that and the other issue it works fine. I especially appreciate the local storage option.

**Comment by tibbi** [comment]
update to the latest version 6.22.1, guess you use the previous broken one

**Comment by favdish** [comment]
Well, I d'loaded it just an hour ago from f-droid... but I will now switch to the github version.

**Comment by tibbi** [comment]
f-droid is usually a couple days behind

**Comment by favdish** [comment]
Well, f-droid is my go-to app provider and normally I am fine with their offers. I had at that point not realised there's a github repo as well.

Anyway, the GH version works. Thanks.
