### ISSUE TITLE
Unable to share contact to whatsapp

### ISSUE THREAD

**Issue by test2a** [SimpleMobileTools/Simple-Contacts#942]
The format of this vcard is not supported

V.6.22.1

**Comment by tibbi** [comment]
what do you mean, where are you getting that error?

**Comment by test2a** [comment]
F droid install

**Comment by test2a** [comment]
When I search a contact and select and share, selecting WhatsApp says toast

**Comment by test2a** [comment]
https://ibb.co/X5dF9DY

**Comment by Merkost** [comment]
@test2a could you please share more details about the issue. Does your contact has any name filled? And phone number? Any specific details about the contact will help to solve the issue. Thanks
