### ISSUE TITLE
Import fails with `Error:java.lang.NullPointerException: address must not be null`

### ISSUE THREAD

**Issue by schreven** [SimpleMobileTools/Simple-Contacts#948]
I am seeing this on version 5.3.1. I get `Error:java.lang.NullPointerException: address must not be null`.
The error appears when attempting to import the following vcard:
```
BEGIN:VCARD
VERSION:4.0
N:;John;;;
ADR;PREF=1:;;;;;;
END:VCARD
```
However the following can successfully be imported
```
BEGIN:VCARD
VERSION:4.0
N:;John;;;
ADR;PREF=1:;;street;;;;
END:VCARD
```
Thus it seems that the missing `ADR-component-street` is the cause of this error.

When this error occurs, the import stops then and there and I see "importing some entries failed". It would be nicer if the import attempted the remaining vcards.

**Comment by Aga-C** [comment]
On the latest version (6.22.1) it's working.

**Comment by schreven** [comment]
Good to hear thanks
