### ISSUE TITLE
How to share more than one VCF card in one email?

### ISSUE THREAD

**Issue by bigboipete** [SimpleMobileTools/Simple-Contacts#959]
Maybe this is already possible, but I wasn't able to find out how to achieve this. I want to share two (i.e. more than one) contacts as vcf card as attachment in the same email.

If this isn't possible, I'd like to suggest this as an improvement for Simple Contacts. I'm not sure how much this depends on the mail app, but if sharing via mail is possible in general, there should take place some communication between Simple Contacts and the mail app already.

**Comment by michaelof** [comment]
This is already possible. Go to contact's list view, select AND HOLD first contact. Doing this, you stay on list view, with selected first contact, ready to select as much additional contacts as you like. When "sharing" the selected contacts, SimpleContacts creates a combined "contacts.vcf" file an attaches this.
