### ISSUE TITLE
Deleting contacts in this app also deletes from original source

### ISSUE THREAD

**Issue by notxasj** [SimpleMobileTools/Simple-Contacts#960]
Using Simple Contacts version 6.22.1 Pro
Phone is Motorola G Stylus 
Android 11

Exported contacts from Google contacts on phone and imported to Simple Contacts app specifically targeting Phone storage (not visible by other apps) 
Clearly there is some link still in place between this app and the Google app for contacts because every deletion made to contacts in Simple app also deleted them from Google app. 
If I'm utilizing the source that is from my phone and not visible to other apps then why is Google seeing that I am deleting a contact in simple app and removing the contact from there also? 

I then used setting option in Google to undo changes recently made and restored the contacts in Google back to prior from when I made updates so the deleted contacts would show in Google again since I did not want to make any changes with what is stored with google. 
After the deleted contacts were restored in Google the Simple Contacts app updates the favorite list automatically without any additional input from myself to now show duplicate listings and one even a third time as it was entering contacts into favorites from my gmail and telegram even though when I look at the filter option I still only have selected phone storage not visible to other apps. 

If the simple apps will share my data back to Google then there is really no point using any of them as an alternative

**Comment by tibbi** [comment]
are you deleting from the View or Edit screen?

**Comment by notxasj** [comment]
This fails to address the issue that in establishing contacts to be Not Visible to other apps that the user would be under the impression that there will no longer be communication with any other apps. So deleting from the original source regardless what screen I am on should not be the intended behaviour. And in restoring the deleted data with Google should not import the data again and create duplicates into an area that has been designated not visible to other apps.

If the problem is not considered a problem and won't be corrected then maybe the wording it filtering should be changed so that users won't be misguided into believing that phone storage option will prevent communications between other apps since the read/write capabilities are clearly still there and apparently is how you intend for it to continue functioning.

I'll be deleting the app as it does not function in the way I interpreted it would based on the language used

Mar 21, 2023 3:04:00 AM Tibor Kaputa ***@***.***>:
