### ISSUE TITLE
buttons are not pressed due to the upward movement in the status bar

### ISSUE THREAD

**Issue by OmlineEditor** [SimpleMobileTools/Simple-Contacts#961]
If I edit the contact card and edit the phone number, then everything is fine and I can press the edit completion buttons. But if you edit the lower fields, for example, a note, then everything is bad, I can't press the buttons, the buttons are on the line of the position. make sure that the buttons do not move up they can be pressed

Simple Contacts Pro 6.22.2 (f-droid)
Android 10
Phone: Redmi Note 7

![a](https://user-images.githubusercontent.com/13348933/226638195-4bfc372f-7c61-4d70-a994-318eb1eb58ce.jpg)
![b](https://user-images.githubusercontent.com/13348933/226638206-7eb57611-93f6-4e16-bf2c-d369d7114783.jpg)

**Comment by tibbi** [comment]
how did those buttons get behind the top status bar, does it always happen at opening the keyboard?

**Comment by Aga-C** [comment]
I think it's related to https://github.com/SimpleMobileTools/Simple-Contacts/issues/866.

**Comment by OmlineEditor** [comment]
> how did those buttons get behind the top status bar, does it always happen at opening the keyboard?

The buttons only move up only if I change the lower fields. if the upper fields is everything is fine

**Comment by tibbi** [comment]
should be fixed already
