### ISSUE TITLE
Add button to send Signal message (and other messangers)

### ISSUE THREAD

**Issue by rubo77** [SimpleMobileTools/Simple-Contacts#963]
Since Signal removed SMS support, the message button opens the default SMS app instead of Signal.

please add a Button to send a Signal message directly from the contact page.

(It would be probably good to add a message button to all connected messenger accounts)

**Comment by Aga-C** [comment]
There is already a button in the Contact source field.
<img src="https://user-images.githubusercontent.com/85929121/228144304-3a8ffebd-ef56-4c37-8590-e476bce2ece5.png" width="350">
