### ISSUE TITLE
Feature: Add new LIST VIEW option - Show Organisation

### ISSUE THREAD

**Issue by Protofall** [SimpleMobileTools/Simple-Contacts#971]
Feature Request:

This would behave similarly to the existing "Show phone numbers" option, if the contact has an `ORG` field then render it under the name.

I'm willing to work on this, although I'll be busy for a few weeks so I won't have time to look into/work on this.

**Comment by Protofall** [comment]
From a quick search of the repo, it appears these files will be relevant when implementing this. I'll leave the links here so I remember when I come back to this:
- The code that render the contact's phone number on the main view, [here](https://github.com/SimpleMobileTools/Simple-Contacts/blob/3e542bbf7d18455a41698c8b240e18ab63d66006/app/src/main/res/layout/activity_settings.xml#L315)
- The kt code for the toggle logic for a phone's contact, [here](https://github.com/SimpleMobileTools/Simple-Contacts/blob/11f3b0f3e87efe4c8e9788aaf58cdf65c9208599/app/src/main/kotlin/com/simplemobiletools/contacts/pro/activities/SettingsActivity.kt#L139)
   - Also need to call the new toggle in `onResume()` so this option is accessible from the settings menu

There might be more files I'd need to change, I'll figure that out when I start working on this.

**Comment by tibbi** [comment]
dont really expect having that, it is a way too edge case that someone needs it

**Comment by Protofall** [comment]
> dont really expect having that, it is a way too edge case that someone needs it

My friend and I both used this on our old contact managers (Now he just includes the org in the last name field to get the desired result in this app).

If I implemented this feature myself and it met the coding standards for this repo, would you accept a PR for it?

**Comment by tibbi** [comment]
not really, I dont think we need it in this app

**Comment by Protofall** [comment]
I am confused, I don't understand why you don't want this. There are users who find this very useful. I agree most users wouldn't use this, but that's why it would be an option (Off by default so it doesn't affect users who don't want it). Plus, this option would behave similarly to an existing option, so it wouldn't just be a "random feature".

**Comment by tibbi** [comment]
casual users just dont need it, our apps are built for the casual 99% of users, not handling extreme edge cases

**Comment by Protofall** [comment]
I wouldn't call this an extreme edge case, especially since showing the org on the main view is the default on some contact apps, including the default contact app on some phones. And given its a small feature that wouldn't require much more maintenance than the existing LIST VIEW options, I feel its fine to cater to the 1%.
