### ISSUE TITLE
Error when trying to change contact photo

### ISSUE THREAD

**Issue by MiracoleWorker** [SimpleMobileTools/Simple-Contacts#973]
When trying to change a contact's photo, I get an error message that says "No application available" (original error text: "Aucune application disponible"). I click on the contact, click edit, click on the picture, click on "Choose a photo," select a photo from my gallery, and that's when the error message pops up. 

I tried using Aves gallery and Simple Gallery Pro with the same result both times. I tried force quitting and clearing the cache of the galleries and contact app and got the same result. I tried changing from within Simple Contacts Pro and within Aves and neither worked. I've been able to change them in the past (e.g. Months ago), so am not sure what changed. 

I'm using a OnePlus 5 running LineageOS + microG 20, and using version 6.22.3 of Simple Contacts Pro.

**Comment by tibbi** [comment]
havent you disabled some system services or limited your system in a similar way?

**Comment by MiracoleWorker** [comment]
I disabled a few apps that came with the OS (eg Agenda, Contacts) but nothing else. For good measure, I tried reenabling the original Contacts app, but Simple Contacts still gave me the same error message.

Is there a specific system app that is supposed to handle this action?

**Comment by tibbi** [comment]
some system file manager or so, hard to say. It isnt an issue on our side though
