### ISSUE TITLE
Feature idea: Add call history in contact

### ISSUE THREAD

**Issue by Ptaski** [SimpleMobileTools/Simple-Contacts#976]
Add call history under contact information
Like this: 
(screenshot from another app)
![this is cropped](https://user-images.githubusercontent.com/132298731/235523455-9bbffde2-bb62-4c88-91bd-3a361aa84196.jpg)

I wasn't sure whether this should go to here or to Simple-Dialer repo. I figured this should go here.

**Comment by Aga-C** [comment]
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Dialer/issues/380.
