### ISSUE TITLE
Birth Year in Simple Contacts Pro

### ISSUE THREAD

**Issue by durgakali** [SimpleMobileTools/Simple-Contacts#977]
Hello there,

when adding a birthday I can no longer scroll to the Birth year. It just let me scroll only a few years back. E.g. from 2023 to 2021.

Can you help?

Thanks and kind regards,
iris

**Comment by tibbi** [comment]
just click on the year if thats what you want to change

**Comment by tibbi** [comment]
that is a system issue then, not anything on our side
