### ISSUE TITLE
Ability to set default values for new contacts

### ISSUE THREAD

**Issue by xeruf** [SimpleMobileTools/Simple-Contacts#987]
Currently I am going with the stock contacts app, because I haven't found sufficient differences and last time I tried there was a little thing nudging me back.

Anyways, there would be one very simple killer feature making me switch immediately:
The ability to set default values for new contacts - for example:
- country calling code: I tend to prefix my contacts with `0` out of convenience, but as a German it would be better to use `+49` so I can also call my contacts from another country. If it would be prefilled by default in the phone number field, I would actually use it consistently.
- suffix/label/note: When I get to know a few people at an event and save them, it is a hassle to properly annotate them so I remember where I know the person from. If I could set either of these before the event and change it again afterwards, that would be very helpful.
- automatic location annotation: The city/county I added that person at in a note or something like that (more advanced, just an idea, surprised Google does not even have something like this)

**Comment by tibbi** [comment]
oh thanks, but dont really expect having such advanced features in this app
