### ISSUE TITLE
Favorites aren't included in the .vcf export. App settings not included in export

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [SimpleMobileTools/Simple-Contacts#989]
I'd like a way to export the configurations of the entire app, and I thought the VCF export would include my favorites list, but it doesn't. Could we please get a way to backup everything in the app, including contacts, app settings, and the favorites list? 🙏

**Comment by tibbi** [comment]
vcf exports all contacts, doesnt care if favorite or not. Settings will be backed up through another button in the app settings, like it already is in the gallery and calendar. But Ill close this issue as it is a generic one affecting all apps already reported on another place.
