### ISSUE TITLE
Building instructions

### ISSUE THREAD

**Issue by ZenKyma** [SimpleMobileTools/Simple-Contacts#992]
Hello and thank you for this awesome foss app collection.

I am trying to build an apk from source, figured you would need android sdk and gradle for that. But my `gradle assemble` command fails after initialising:

```
(base) zenkyma@wergon:~/Downloads/Simple-Contacts$ gradle assemble --info
Initialized native services in: /home/zenkyma/.gradle/native
The client will now receive all logging from the daemon (pid: 109624). The daemon log file: /home/zenkyma/.gradle/daemon/4.4.1/daemon-109624.out.log
Starting 2nd build in daemon [uptime: 15.336 secs, performance: 98%]
Using 4 worker leases.
Creating new cache for fileHashes, path /home/zenkyma/Downloads/Simple-Contacts/.gradle/4.4.1/fileHashes/fileHashes.bin, access org.gradle.cache.internal.DefaultCacheAccess@32964f4

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

Are there any build instructions available? :pray:

**Comment by tibbi** [comment]
hi, no idea what is that about, you seem to have something misconfigured. Try starting with some hello world first.

**Comment by ZenKyma** [comment]
Thanks for the quick reply. I never coded in Kotlin before, just trying to build your repository from source so I can fork and add more standard fields to the Instant Messengers, particularly Matrix, Fediverse and Instagram.

**Comment by tibbi** [comment]
start with some Hello World projects first, not real apps..

**Comment by ZenKyma** [comment]
Can you recommend me a Hello World project to start with?

**Comment by tibbi** [comment]
just google some...

**Comment by ZenKyma** [comment]
Quite disappointed about the lacking support for building from scratch. Anyway, good luck with your self-proclaimed "awesome-kotlin-apps". I was about to contribute at some point but being confronted with such an arrogant rudeness made my enthusiasm about your projects evaporate.
